### ISSUE TITLE
用户反馈

### ISSUE THREAD

**Issue by zoffyzhang** [Binaryify/OneDark-Pro#100]
- peek implementation (Ctrl+Shift+F12) 的背景色为橘色看不清楚
- 我感觉斜体并不适合中文，所以注释的font-style能不能改成normal？

---

（我有修改本地配置但是每次插件更新后都被删掉了）

**Comment by Binaryify** [comment]
默认的橘色确实看不清楚,有什么颜色推荐吗,注释下次更新可以改为 normal

**Comment by zoffyzhang** [comment]
不好意思，对颜色搭配没有研究

**Comment by Binaryify** [comment]
我今晚调下

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/27313187-47f1deaa-559f-11e7-8f48-2c43af7c0f5f.png)
这样如何

**Comment by zoffyzhang** [comment]
看起来可以，you're the author, you decide

2017-06-20 10:00 GMT+08:00 阿发 <notifications@github.com>:

**Comment by Binaryify** [comment]
@zoffyzhang 
已更新
