### ISSUE TITLE
missing style for `support.variable.property.process.js`/ts

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#101]
can't contribute it myself, because I have limited internet bandwidth atm.

**Comment by Binaryify** [comment]
Can you provide some code?

**Comment by jens1o** [comment]
```js
if (path.basename(process.argv[1]) === 'update-grammar.js') {
	for (var i = 3; i < process.argv.length; i += 2) {
		exports.update(process.argv[2], process.argv[i], process.argv[i + 1]);
	}
}
```
![image](https://user-images.githubusercontent.com/11234139/27366313-949b1694-5645-11e7-8b05-b45f16ed6106.png)

**Comment by Binaryify** [comment]
你觉得它应该是什么颜色

**Comment by Binaryify** [comment]
In Atom it was red
![image](https://user-images.githubusercontent.com/12221718/27366577-a0ab82be-5679-11e7-87c5-d84f66064274.png)

**Comment by jens1o** [comment]
Hmm... Maybe some yellow? Because then it's clear it's a special variable.

**Comment by Binaryify** [comment]
How about this ?
![image](https://user-images.githubusercontent.com/12221718/27383708-be5dd9ca-56be-11e7-8523-f2dc9910f84a.png)

**Comment by jens1o** [comment]
Yes, that's good!
