### ISSUE TITLE
Color debug toolbar/popup

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#105]
![capture](https://user-images.githubusercontent.com/26769888/27389345-b84671bc-56bb-11e7-9090-d810d4f24771.PNG)

**Comment by Binaryify** [comment]
Can you provide detail info?

**Comment by ajitid** [comment]
`"debugToolBar.background"` isn't colored.

**Comment by Binaryify** [comment]
Thx ~
Will look like this
![image](https://user-images.githubusercontent.com/12221718/27390188-3bb0fde4-56d3-11e7-834b-0f9598e5ec78.png)

**Comment by Binaryify** [comment]
Will update tomorrow

**Comment by ajitid** [comment]
Okay thanks. There are more elements not colored. Do I put them here or make a new issue for them?

**Comment by jens1o** [comment]
Rather create a new issue.

**Comment by jens1o** [comment]
@Binaryify Could you push these changes please and reference it here?

**Comment by Binaryify** [comment]
@jens1o 
Wait for minutes

**Comment by Binaryify** [comment]
@jens1o 
Done

**Comment by jens1o** [comment]
https://github.com/Binaryify/OneDark-Pro/commit/c51f1337e9e3d8e0b5b7ad5da83af186c9cd36aa
