### ISSUE TITLE
Coloring few theme elements

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#106]
Coloring (in the pic) "1 Unsaved" and "Total 450 settings" with 
```
"badge.background"
"badge.foreground"
```

![capture](https://user-images.githubusercontent.com/26769888/27391899-ccbedc4a-56c2-11e7-973c-d2fa8e1ec0ac.PNG)

--------------------

Coloring "Go to next error or warning" (Keyboard shortcut: F8) popup

![capture](https://user-images.githubusercontent.com/26769888/27392078-4578e2fc-56c3-11e7-96a8-a16b800685f0.PNG)

That whole red border and background inside it can be colored. Same for warning

**Comment by Binaryify** [comment]
Will fix it tomorrow

**Comment by Binaryify** [comment]
Seem only can change background color
![image](https://user-images.githubusercontent.com/12221718/27413979-1ce79c3e-5731-11e7-93ca-79d74c6b8fef.png)

**Comment by ajitid** [comment]
Okay color these then.
