### ISSUE TITLE
php font style italic does not work on comments

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#108]
explicitly setting font style to `italic` resets the behavior here: 
![image](https://user-images.githubusercontent.com/11234139/27440659-b2c619f8-576b-11e7-8586-b8b5b5884a46.png)

(Note the line in the middle is not italic)

**Comment by Binaryify** [comment]
Some people doesn't like italic in comment
https://github.com/Binaryify/OneDark-Pro/issues/100
It use Chinese language, but you can use transform software to read it
