### ISSUE TITLE
Request color change in Python

### ISSUE THREAD

**Issue by Deltatiger** [Binaryify/OneDark-Pro#111]
Is it possible to change the single line comment in Python to the same of the docstring or something that is little brighter. Currently it is blending with the background and makes it hard to read sometimes.

Especially when that is the current line the highlight makes it even more difficult to read.

![one dark pro - python - single line comment](https://user-images.githubusercontent.com/1459811/27650525-db1da9c0-5c52-11e7-9656-54a1503123a0.png)

**Comment by Binaryify** [comment]
Can you provide the code in your screenshot?

**Comment by Deltatiger** [comment]
"""
    Module that contains the grouping of various configuration keys used to store important information
    """
    from enum import Enum
    
    class GoogleSheetConfigKeys(Enum):
        '''
        Contains the Keys used with reference ot the Google Sheet details
        '''
        # This is for Students Form
        StudentsFormName = 'StudentsForm'
        StudentsFormURL = 'StudentsFormURL'
        # This is for Faculty Form
        FacultyFormName = 'FacultyForm'
        FacultyFormURL = 'FacultyFormURL'
        # This is for Report Submission Status
        ReportSubmissionFormName = 'ReportSubmissionForm'
        ReportSubmissionFormURL = 'ReportSubmissionFormURL'

**Comment by jens1o** [comment]
@Binaryify Are you working on this? Otherwise I'll give it a shot.

**Comment by Binaryify** [comment]
@jens1o 
Not yet

**Comment by jens1o** [comment]
Okay, I took a look. Actually, it's a bug that the docstrings aren't marked as comments...

BUT!

I think we should consider whether we can darken the background current-line color... I think that would solve many other bugs...
