### ISSUE TITLE
Seems minimap doesn't work in this awesome theme?

### ISSUE THREAD

**Issue by bidiu** [Binaryify/OneDark-Pro#115]
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|tortoise-svn-for-vscode|cdsama|0.1.1|
|tslint|eg2|0.16.0|
|vscode-icons|robertohuertasm|7.10.1|
|Material-theme|zhuangtongfa|2.9.3|;

**Comment by jens1o** [comment]
Can you elaborate, please?

It's working fine for me:
![image](https://user-images.githubusercontent.com/11234139/28223897-6d56fb6c-68cd-11e7-95ca-64ef668263be.png)

**Comment by bidiu** [comment]
@jens1o today I updated my VS Code to 1.14.1, and it works! I am not sure if it's because of my VS Code update, but I will close this issue. Thanks a lot for your information.
