### ISSUE TITLE
JS coloring has issues with strings that have double quotes

### ISSUE THREAD

**Issue by Sartan4455** [Binaryify/OneDark-Pro#116]
version 2.9.3
comments should be grey, variables red, but mixing in strings and what not causes issues
It looks like it doesn't handle single quoted strings with double quotes inside.
![gone-wrong](https://user-images.githubusercontent.com/1134294/28232727-906f8a38-68af-11e7-8735-e42d60de306a.png)

**Comment by jens1o** [comment]
Can you please give us the code? I don't like to copy it with my hand... :/

**Comment by Sartan4455** [comment]
Wrote some code that gives examples of this issue


	/**
	 * Normal comments, colored correctly
	 *
	 * @namespace Some.NameSpace
	 *
	 * @class Some.NameSpace.Class
	 */
	window.coloringIssue = new Class({

		'optionHash': {		
			'stringWithHtml': '<div id="filterCards"><div class="cards"></div></div>',
			'incorrectlyColoredVariableShouldBeRed': Some.NameSpace.Class.variable, // incorrectly colored
		},

		/**
		 *  These are some comments after strings with quotes
		 *  They are colored incorretly
		 * 
		 */
		'nextOptionHash' : {
			'nope' : 'not fixed'
		},
		// double slash comments broken too.  using 'brackets' '[' ']' for the next part "fixes" this coloring issue
 		'moreOptions': [
			 'a', /* comments work again */
			 'b', // comments are working again
			 Some.NameSpace.Class.variable // this is correct again too
		],

		'ohNoAgain': {
			'moreHtml': '<div id="id"></div>'
		}
		// here we go again...
	
		 
	});

**Comment by Sartan4455** [comment]
I don't recall seeing this until recently - perhaps 2.9.2 caused some regressions?

**Comment by jens1o** [comment]
On the first look, this looks like a `vscode` bug. I'll look into this later.

**Comment by Sartan4455** [comment]
I think you are right.  I tried a few other themes(including the default) and they have the issue too.

**Comment by jens1o** [comment]
Yes, it is. I had a look and when you try it out in insiders version, it works:
![image](https://user-images.githubusercontent.com/11234139/28281999-2bf107cc-6b29-11e7-9bef-4e2565a68c7e.png)

So this will be fixed with 1.15 next month. I'm afraid, but there's nothing we can do.

**Comment by Sartan4455** [comment]
No worries.  Thanks for the responses!

**Comment by jens1o** [comment]
Thanks for the example :P
