### ISSUE TITLE
Possible to have some settings as default in settings.json?

### ISSUE THREAD

**Issue by niamleeson** [Binaryify/OneDark-Pro#117]
Thank you for the best theme ever made.

I really don't like italics so I've edited OneDarkPro.json and I've been copy pasting every update. It's kind of annoying to update it every week. Is it possible to have some scope defaults in settings.json so I don't have to worry about them?

**Comment by jens1o** [comment]
No, that's not possible. Can you post your changes? Maybe we can consider them using them natively?

**Comment by niamleeson** [comment]
I used to just remove these two blocks, but setting them to `normal` also seems to work. I might be using them incorrectly, but here are the changes:

```
{
  "name": "js/ts italic",
  "scope": "entity.other.attribute-name.js,variable.parameter.js,variable.language.super.js,entity.other.attribute-name.ts,variable.parameter.ts,variable.language.super.ts,entity.other.attribute-name.jsx,variable.parameter.jsx,variable.language.super.jsx,entity.other.attribute-name.tsx,variable.parameter.tsx,variable.language.super.tsx",
  "settings": {
    "fontStyle": "normal"
  }
}

{
  "name": "js ts this",
  "scope": "var.this.js,var.this.ts,variable.language.this.js,variable.language.this.ts",
  "settings": {
    "foreground": "#e5c07b",
    "fontStyle": "normal"
  }
}
```

**Comment by jens1o** [comment]
Well, I understand your changes, and personally, I'm also for removing these blocks. But this is not my theme, but @Binaryify ones. I'm just helping and contributing to him... :/

Maybe we reconsider this @Binaryify @will-stone ?

**Comment by Binaryify** [comment]
Seem it can't been a setting in "settings.json"
Everyone's aesthetic is different. Some people doesn't like italic, some people like italic

**Comment by will-stone** [comment]
Hmmm, I think I'd go with the opposite and make italics opt-in; from what I can tell, Atom doesn't use italics and so would follow this first. Add a second theme file with the following.

```
{
  "name": "OneDark Pro with Italics",
  "include": "./OneDark-Pro.json",
  "tokenColors": [
    {
      "name": "js/ts italic",
      "scope": "entity.other.attribute-name.js,variable.parameter.js,variable.language.super.js,entity.other.attribute-name.ts,variable.parameter.ts,variable.language.super.ts,entity.other.attribute-name.jsx,variable.parameter.jsx,variable.language.super.jsx,entity.other.attribute-name.tsx,variable.parameter.tsx,variable.language.super.tsx",
      "settings": {
        "fontStyle": "italic"
      }
    },
    {
      "name": "js ts this",
      "scope": "var.this.js,var.this.ts,variable.language.this.js,variable.language.this.ts",
      "settings": {
        "foreground": "#e5c07b",
        "fontStyle": "italic"
      }
    }
  ]
}
```

I've done something similar with my theme. It allows you to add customisations without having to maintain two whole themes.

**Comment by Binaryify** [comment]
@will-stone 
Good idea

**Comment by hoovercj** [comment]
FYI: You can now modify themes in settings.json

Anybody that wants to modify this themselves can simply add this:

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [{
            {
                "name": "js/ts italic",
                "scope": "entity.other.attribute-name.js,variable.parameter.js,variable.language.super.js,entity.other.attribute-name.ts,variable.parameter.ts,variable.language.super.ts,entity.other.attribute-name.jsx,variable.parameter.jsx,variable.language.super.jsx,entity.other.attribute-name.tsx,variable.parameter.tsx,variable.language.super.tsx",
                "settings": {
                  "fontStyle": "normal"
                }
              },
              {
                "name": "js ts this",
                "scope": "var.this.js,var.this.ts,variable.language.this.js,variable.language.this.ts",
                "settings": {
                  "fontStyle": "normal"
                }
              }
        }]
    }
```

**Comment by jens1o** [comment]
@hoovercj Nice catch. And thanks for the heads up ;)

I think this issue can be closed, because you can manually overwrite it.
