### ISSUE TITLE
color issue for some CSS values and selectors for sass (SCSS)

### ISSUE THREAD

**Issue by vikrantnegi** [Binaryify/OneDark-Pro#118]
I've noticed that there are some properties and selectors that are showing the wrong color for SASS(SCSS)

Following are the one I've found.

1. Cursor: pointer;
2. Date

<img width="947" alt="screen shot 2017-07-18 at 12 02 57" src="https://user-images.githubusercontent.com/3294287/28303553-691cc068-6bb1-11e7-825d-6d8f565a1c12.png">

**Comment by Binaryify** [comment]
'cursor' really had wrong color
'date' is not a standard tag

**Comment by Binaryify** [comment]
@vikrantnegi 
This is a bug for vscode
https://github.com/Microsoft/vscode/issues/30907

**Comment by vikrantnegi** [comment]
Ok thanks. Didn't knew that.
