### ISSUE TITLE
background color on select

### ISSUE THREAD

**Issue by bardiarastin** [Binaryify/OneDark-Pro#119]
first of all, thanks for this awesome theme !

in vscode when i click on a variable, editor by default makes it's background blue, then when i select some characters of it, the selected part is not enough obvious.
![download 5](https://user-images.githubusercontent.com/20615964/28357473-c328a37c-6c80-11e7-82af-21914be5f496.png)

**Comment by Binaryify** [comment]
Got it

**Comment by Binaryify** [comment]
@bardiarastin 
Done

**Comment by bardiarastin** [comment]
@Binaryify , really quick ! great work :)

**Comment by bardiarastin** [comment]
it's gone worse ! actually i can't see selected characters of variables anymore !
below i've selected 3 characters in middle of travelers const but i can not see what i've selected :(
![download 6](https://user-images.githubusercontent.com/20615964/28358818-852e3276-6c85-11e7-9a1c-f3b46cf2888d.png)

**Comment by Binaryify** [comment]
Wait for minutes

**Comment by Binaryify** [comment]
What background color do you want?

**Comment by bardiarastin** [comment]
maybe something more light or more dark, so i can recognize characters that i've selected easily ...

**Comment by Binaryify** [comment]
How about this
![image](https://user-images.githubusercontent.com/12221718/28359857-35476f9a-6ca6-11e7-872a-17ef6622fda2.png)

**Comment by bardiarastin** [comment]
this is the actual problem, you've selected "tra" in const ">tra<"velers and it's not highlighting that 3 characters

**Comment by Binaryify** [comment]
I saw it

**Comment by Binaryify** [comment]
How about this 
![image](https://user-images.githubusercontent.com/12221718/28361006-dd64afc8-6ca9-11e7-993b-bde9452bc93a.png)

**Comment by bardiarastin** [comment]
really good ! would you please say my name in change log ? having contribution on a package which has over 1.2 million user is super exciting ... ;-)

**Comment by Binaryify** [comment]
@bardiarastin 
Will like this
![image](https://user-images.githubusercontent.com/12221718/28361261-d26eb70c-6caa-11e7-8682-ec7e81fd6cc9.png)

**Comment by bardiarastin** [comment]
thanks :+1:

**Comment by Binaryify** [comment]
@bardiarastin 
Done
