### ISSUE TITLE
Comments are not easy to read for the low contrast to the background

### ISSUE THREAD

**Issue by Naruto-Sasuke** [Binaryify/OneDark-Pro#121]
I think it is better to darken the comments a little bit.

**Comment by Binaryify** [comment]
Could you provide some screenshot?

**Comment by Naruto-Sasuke** [comment]
![_101](https://user-images.githubusercontent.com/7830725/28398079-116b87d6-6d38-11e7-9cf9-3bfaf823fe37.png)
I think it is a bit hard to read the comments.

**Comment by Naruto-Sasuke** [comment]
![_102](https://user-images.githubusercontent.com/7830725/28398124-4f4d60ba-6d38-11e7-8bbe-b610558391ec.png)
I think it is a little hard to read the comments

**Comment by jens1o** [comment]
@Binaryify What do you expect, should we make the comments a little bit brighter?

I'm busy, but I try to figure out the best-fit color as soon as possible.

**Comment by Binaryify** [comment]
@jens1o 
Actually I don't think make the comments be brighter is a good idea
How about you

**Comment by vvs** [comment]
@Binaryify, @jens1o I actually agree that the current comment color is way too close to the background, and it doesn't match the color in the original Atom's theme.

There, the color is: `#818998`.
In OneDark pro the color is ; `#5c6370`

If you wish, I could create a PR that fixes this and brings the comments in sync with the original theme, and it will make them much easier to read.

**Comment by Binaryify** [comment]
@vvs 
Yes

**Comment by vvs** [comment]
Ah, sorry for the confusion. The brighter color in Atom (`#818998`) was my own setting overriding the original `#5c6370`.

So, I am not sure what to do. OneDark Pro is already currently fully in sync with Atom theme w.r.t. comments.
I'd assume it would be good to be in sync with the original theme, and not divert from it too much. So the issue of hard to read comments should be reported to the original theme author (upstream).

Personally, I just keep the local (forked) tweaks that suite my tastes even though they divert a bit from the upstream Atom theme.

In case you want to see the brighter comments, here's my changes for that: vvs/OneDark-Pro@a983b4abf42879415cd10d64237f827dcb38f31e

**Comment by jens1o** [comment]
I also don't know what to do, sorry.
