### ISSUE TITLE
Is this color scheme package will update to new Atom's One Dark colorscheme?  

### ISSUE THREAD

**Issue by ergenekonyigit** [Binaryify/OneDark-Pro#122]
As you can see, atom's new updated one dark colorscheme is more vivid then current vscode version. Any plan for update colors?
* Left - VS Code | Right - Atom
![screen shot 2017-07-21 at 23 24 43](https://user-images.githubusercontent.com/7110136/28481194-9bacc04c-6e6c-11e7-87e4-468704283d0f.png)

**Comment by jens1o** [comment]
Good catch! But this is up to @Binaryify

**Comment by niamleeson** [comment]
The new color looks way too vibrant... Is it just me?
