### ISSUE TITLE
Theme more vibrants than on Atom

### ISSUE THREAD

**Issue by customht** [Binaryify/OneDark-Pro#125]
Hi,

This theme is more vibrant than the Atom theme. Is VSCode not using the same display color profile as Atom? Atom is softer (which I prefer and matches the screenshots).

TIA!

VSCode left, Atom right

<img width="792" alt="screen shot 2017-07-25 at 3 25 10 pm" src="https://user-images.githubusercontent.com/28520174/28557038-8a3906c0-714d-11e7-8f94-7ca461891ab9.png">

**Comment by Binaryify** [comment]
Will improve this when I merge this PR
https://github.com/Binaryify/OneDark-Pro/pull/123

**Comment by lprhodes** [comment]
I don't believe so,  that pull request looks to make VSCode even more vivid.

At the moment the colors used are correct but VSCode is still more vibrant.

It could be related to this https://github.com/Microsoft/vscode/issues/24569

**Comment by lprhodes** [comment]
I misread sorry, hopefully you can solve the issue but it looks like VSCode's version of electron is older than Atom's which may be cause issues on the P3 capable displays

**Comment by Binaryify** [comment]
Maybe, I'll pay attention to it

**Comment by vvs** [comment]
Hi folks, I tried the latest color changes from the master, namely #123 and I must say, it is now painful for me to look at my code. WAAY too vivid.

Even before the change the colors in VS Code were a bit more vivid as compared to Atom, but with these even more vivid colors from #123 is is painfully obvious the difference.

If possible, could you please make those more vivid colors as a separate theme, not the main/default one.

Thank you!

**Comment by vvs** [comment]
Here's what I see on my PC.

First, for the reference, the Atom 1.19 beta5:
![atom-1 19 betea5](https://user-images.githubusercontent.com/9781/28678506-deb6ca44-72f0-11e7-9f40-bc009959a20f.png)

Then VS Code with Dark One theme v. 2.9.8:
![vs_code_2 9 8](https://user-images.githubusercontent.com/9781/28678535-ed5d462c-72f0-11e7-8257-820263b180ce.png)

And this is from the latest master, with even more vibrant/vivid colors:
![vs_code_master_vivid](https://user-images.githubusercontent.com/9781/28678550-f78681e0-72f0-11e7-8df6-6f9f58c11f51.png)

Pay attention to the red color for variables. It is certainly over-vibrant esp. when compared to the original Atom colors.

Please consider moving these extra-vibrant colors to separate theme and not release them as a main theme. Thank you!

**Comment by jens1o** [comment]
That's a good idea @vvs ! I thought @Binaryify impleented it like you said, in an external theme, as long as we're still exploring it...

**Comment by vvs** [comment]
@jens1o I checked the latest freshly released version and it is so, there are two themes, the main one and another one.

But for some reason, the vivid theme is called `One Dark Pro xxx` and not really enabled, since it references the wrong file name.

**Comment by jens1o** [comment]
Thank you, we'll fix that with the next recovery release... @Binaryify Do you do that or should I fix that problem?

**Comment by Binaryify** [comment]
Oh, my mistake, will fix that tomorrow

**Comment by Binaryify** [comment]
@jens1o 
Done

**Comment by vvs** [comment]
@Binaryify I'd also change the name of the vivid theme. Currently, it is rather cryptic `One Dark Pro xxx`

Something like `One Dark Pro Vivid` would be much better, I think.

**Comment by Binaryify** [comment]
@vvs 
I just publish a new version, sorry

**Comment by jens1o** [comment]
I think we can get rid of this issue, since Visual Studio Code allows doing this since July release:
https://code.visualstudio.com/updates/v1_15#_workbench

Thoughts? @Binaryify

**Comment by Binaryify** [comment]
@jens1o 
Yup, What do you think we should do, update the docs?

**Comment by jens1o** [comment]
Yeah, I think we should do that. Do you take that job?

**Comment by Binaryify** [comment]
@jens1o 
yes

**Comment by Binaryify** [comment]
@jens1o 
maybe will update at this weekend
