### ISSUE TITLE
Bring JavaScript constants color in sync with Atom

### ISSUE THREAD

**Issue by vvs** [Binaryify/OneDark-Pro#126]
Currently, in 2.9.8, JavaScript's constants color is: `#e5c07b`

In the latest Atom 1.19-beta5, the color for JS constants in Dark One theme is: `#d19a66`, which is much more pleasant to my eyes (and less vivid and not so out-of-place for this dark theme).

**Comment by Binaryify** [comment]
You can see this
https://github.com/Binaryify/OneDark-Pro/pull/123

**Comment by vvs** [comment]
@Binaryify thanks for the quick response!

But #123 does not in fact changes these colors (for JS constants). Not to mention that the whole change in #123 is way, way too vivid for me to be usable :(

**Comment by Binaryify** [comment]
Oh, I misunderstand that, will improve that, thx~

**Comment by Binaryify** [comment]
I improve it, please update and check it, thx~

**Comment by vvs** [comment]
@Binaryify, almost there, thank you!

I've created a PR to fix the remaining part (JS math colors): #130

**Comment by Binaryify** [comment]
@vvs 
I see it

**Comment by vvs** [comment]
And this issue can be considered fixed now. Thanks!
