### ISSUE TITLE
PHP: $this is now splitted into two parts (and italic)

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#128]
this looks really ugly...

![image](https://user-images.githubusercontent.com/11234139/28718460-67bfe2ac-73a6-11e7-9249-42caf177c69a.png)

**Comment by Binaryify** [comment]
I had been fix that

**Comment by jens1o** [comment]
thanks for the rapid response, will check.

**Comment by jens1o** [comment]
fixed, thanks!
