### ISSUE TITLE
(S)CSS selectors shown in italics

### ISSUE THREAD

**Issue by danielpost** [Binaryify/OneDark-Pro#131]
In my .scss files, the selectors are now shown in italic font. Is this expected behavior? If so, is there an easy way to change this?

![image](https://user-images.githubusercontent.com/1713699/28761696-8a4311c6-757e-11e7-91d0-8f8f209c81e5.png)

**Comment by Binaryify** [comment]
That was a mistake, will fix it soon

**Comment by Binaryify** [comment]
@danielpost 
Done

**Comment by danielpost** [comment]
That was fast! Thanks!

**Comment by danielpost** [comment]
It seems to still be in italics for pseudo-elements. Is that on purpose?

**Comment by Binaryify** [comment]
How about now

**Comment by danielpost** [comment]
Perfect!

I hope I'm not bothering you too much but I encountered some color issues as well:

![image](https://user-images.githubusercontent.com/1713699/28762360-dd8619be-7583-11e7-932a-c4f297c41eb0.png)

![image](https://user-images.githubusercontent.com/1713699/28762375-fb67171c-7583-11e7-99d4-323edc8c5677.png)

![image](https://user-images.githubusercontent.com/1713699/28762378-0228ac6e-7584-11e7-8e6e-a56dcb2f5dd1.png)

**Comment by Binaryify** [comment]
Can you provide your code in the screenshot?

**Comment by danielpost** [comment]
What do you mean exactly? In pseudo-elements, 'content' is colored weirdly and in transition 'top', 'bottom', 'background' are off (maybe also 'left' and 'right', haven't tested).

**Comment by Binaryify** [comment]
you can see this issue 
https://github.com/Microsoft/vscode/issues/30907

**Comment by Binaryify** [comment]
"content" & "cursor" color wrong issue had been fix at vscode version 1.7, please check it
