### ISSUE TITLE
Add php screenshot to the extension's readme

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#133]
since it is pretty well maintained by me, I think we can show that to the public, because not many themes are supporting php like this.

**Comment by Binaryify** [comment]
How about this?
![image](https://user-images.githubusercontent.com/12221718/28805352-02d3a100-769c-11e7-933b-90e5f132141d.png)

**Comment by jens1o** [comment]
Maybe something with more docblocks? Like this file: https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/WCFACP.class.php

**Comment by Binaryify** [comment]
Like this?
![image](https://user-images.githubusercontent.com/12221718/28825750-1f3863a4-76fa-11e7-9b6a-e7d5cb9ff9ce.png)

**Comment by jens1o** [comment]
Yeah, like this. But it seems you're don't have latest version installed, because then `boolean` and `string` would be styled.

**Comment by Binaryify** [comment]
@jens1o 
I sure I have latest version installed

**Comment by jens1o** [comment]
Ah... sorry. You need to have the latest insider version installed too. So, at the moment, it looks like this...

![image](https://user-images.githubusercontent.com/11234139/28863619-028bd270-776a-11e7-97e6-b0c02eb73fc7.png)

**Comment by Binaryify** [comment]
Like this?
![2017-08-02 4 10 07](https://user-images.githubusercontent.com/12221718/28863885-2b894814-779d-11e7-9c1a-326f5a4a6321.png)

**Comment by jens1o** [comment]
Yeah, that's it. 1.15 will arise soon, so that shouldn't be a problem.

**Comment by Binaryify** [comment]
OK, will add this screenshot

**Comment by jens1o** [comment]
Thanks!

**Comment by Binaryify** [comment]
@jens1o 
Done

**Comment by jens1o** [comment]
Thx. ~~
