### ISSUE TITLE
Java looks ugly.

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#134]
![image](https://user-images.githubusercontent.com/11234139/29002760-151b7006-7aaa-11e7-8e71-31ec2abb2207.png)

definitly need to work on it.

**Comment by Binaryify** [comment]
I just got back from my holiday, will fix it soon~

**Comment by jens1o** [comment]
Perfect, because I lack time...

**Comment by Binaryify** [comment]
@jens1o 
Done

**Comment by jens1o** [comment]
thx ~~
