### ISSUE TITLE
hard to find mouse cursor in dark theme 

### ISSUE THREAD

**Issue by Yensan** [Binaryify/OneDark-Pro#135]
https://github.com/Microsoft/vscode/issues/32132
- VSCode Version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e,2017-07-19T23:34:09.706Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 
include-autocomplete|ajs|0.0.4
python|don|0.7.0
cpptools|ms-|0.12.2
Ruby|reb|0.13.0
vscode-icons|rob|7.12.0
---
Most of IDE's mouse cursor ( Not that insert cursor) is dark. When editor's background is dark, it is painful to find where is my mouse course ( although we use keybord in programing most of time).
this is what jetbrains' users said ( I am also a Pycharm user)  https://youtrack.jetbrains.com/issue/IDEA-68995   
VS code with dark theme ( such as OneDark-Pro) have this problem, too. And the pain is same. Hope you guys fix it  :)

**Comment by jens1o** [comment]
Can you show a screenshot? Personally, I don't "see" the problem.

Then we'll do a fix.

**Comment by Yensan** [comment]
@jens1o 
![2017-08-09 00 56 54](https://user-images.githubusercontent.com/16527206/29084187-c8177fca-7c9d-11e7-91e7-0521b1713ea6.png)
Insert cursor : the cursor that means "you input someting here"
Mouse cursor : the cursor that means "where is my mouse"
In Mac，all of them is bright ( or just white) which is obvious.
But in Windows, ehm..... Insert cursor is bright, Mouse cursor is dark. So it is painful to find Mouse Cursor all the time.

**Comment by jens1o** [comment]
Err, I'm sorry, but unfortunately there's nothing we can do as far as I understand, this is a more vscode issue, and I even don't know whether there is a way to fix it. 😢

**Comment by Yensan** [comment]
@jens1o 
hi jens1o, I have fixed this issue. This issue is not OneDark-Pro nor vs code, it is Windows system. In default mouse cursor, it is always hard to find cursor in dark color software UI. Just install and change the mouse cursor, such as "20 color.exe"

**Comment by jens1o** [comment]
Perfect, thanks! :)
