### ISSUE TITLE
PHP highlight problem

### ISSUE THREAD

**Issue by tradzero** [Binaryify/OneDark-Pro#136]
This [file](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Testing/TestCase.php) has highlight issue, maybe because using `use` in multi-line, and problem screenshot below.
![qq 20170815103624](https://user-images.githubusercontent.com/13845447/29300066-a6aa9086-81a5-11e7-8ddb-d29c0c3bb8cc.jpg)
![qq 20170815103633](https://user-images.githubusercontent.com/13845447/29300071-ab61d184-81a5-11e7-8ccb-3d137bf28fdc.jpg)

**Comment by tradzero** [comment]
I found XML files has likely problem 
![image](https://user-images.githubusercontent.com/13845447/29301552-8fea8de2-81af-11e7-9b7b-3bdee27174b1.png)

**Comment by jens1o** [comment]
First of all, please don't show just a screenshot(and XML is different than PHP, isn't it?). When I'm trying to reproduce, I need code examples. The first is a vscode issue(https://github.com/Microsoft/vscode/issues/32495). I don't know the second one, but this is also a vscode issue. Please file an issue there and link it to here.

**Comment by tradzero** [comment]
@jens1o got it,  thanks for explain.

**Comment by jens1o** [comment]
Thanks for creating the issue! I'll keep subscribing to it, when they explore they need to break a thing.
