### ISSUE TITLE
Python string color inconsistency

### ISSUE THREAD

**Issue by noahleigh** [Binaryify/OneDark-Pro#138]
Extension Ver: **2.10.8**
VSCode Ver: **1.15**

In Python, when enclosed by parentheses, certain strings like `%e`, `%f`, `%d` and others are colored differently from the rest of the string. This is annoying for things like [datetime format strings](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior).

![capture](https://user-images.githubusercontent.com/5957867/29338930-b16d17ce-81e5-11e7-9107-21e6ab173ebf.PNG)

**Comment by jens1o** [comment]
Please provide, in general, a code snippet, not just a screenshot. Will check(and fix) this tomorrow.

**Comment by noahleigh** [comment]
Snippet:
```
'abc%dbfd'
('abc%dbfd')
```

**Comment by jens1o** [comment]
I'm sorry, but my `vscode - Insiders` is not working anymore. :/ Have to wait for Microsoft for a fix in the extension Host....

**Comment by noahleigh** [comment]
@jens1o Any luck getting your vscode to run?

**Comment by jens1o** [comment]
Ah, good ping. It works again since a week, and I forgot about it. Will look into this now. :)
