### ISSUE TITLE
Integrated terminal font colors not styled

### ISSUE THREAD

**Issue by mmase** [Binaryify/OneDark-Pro#141]
Are there plans to style the integrated terminal font colors?

**Comment by jens1o** [comment]
Can you show an example? For me, it's styled...?

**Comment by mmase** [comment]
Apologies, yes it is styled, but the color pallet does not match that of One Dark - it is the same color pallet used for a dozen other pre-installed themes.

**Comment by jens1o** [comment]
Okay, that makes sense... I'll take a look at it. Do you know a command with that you can get all color codes?
