### ISSUE TITLE
Provide coloring to heads-up notification

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#143]
New keys are here: https://github.com/Microsoft/vscode/issues/28280

**Comment by jens1o** [comment]
That's cool, but personally, I lack of what we could do there... @Binaryify Thoughts?

**Comment by Binaryify** [comment]
will improve it

**Comment by bsvipas** [comment]
I will improve it after 1.21 version will be released. Because notifications UI was reworked. https://github.com/Binaryify/OneDark-Pro/issues/194

**Comment by svipben** [comment]
@Binaryify this can be closed because all colorings in Notification Center are correct and like it's with the editor.

![image](https://user-images.githubusercontent.com/10441177/37153336-0f7edb90-22e5-11e8-9c65-c52a73d226f8.png)

**Comment by Binaryify** [comment]
@svipben thank you for your help, I really appreciate it

**Comment by svipben** [comment]
@Binaryify No problem. This is the best theme for me, thank you for creating and maintaining it!
