### ISSUE TITLE
not work with vscode 1.16.0

### ISSUE THREAD

**Issue by cwtuan** [Binaryify/OneDark-Pro#144]
After upgrade to vscode 1.16.0, this theme doesn't work

![image](https://user-images.githubusercontent.com/3455798/30236743-6d597b0e-94e6-11e7-977a-4cb6dd1b78b2.png)

![image](https://user-images.githubusercontent.com/3455798/30236744-77a73a6a-94e6-11e7-92f3-ad13646fcf02.png)

**Comment by Binaryify** [comment]
look like you don't enable it

**Comment by cwtuan** [comment]
Enable it and reload vscode. But still not work

![image](https://user-images.githubusercontent.com/3455798/30258875-ac6ee75a-9682-11e7-8360-f610f9c6dc49.png)

![image](https://user-images.githubusercontent.com/3455798/30258893-c72727ec-9682-11e7-822c-585481b1282f.png)

**Comment by Binaryify** [comment]
you need apply it 
https://binaryify.github.io/OneDark-Pro/#/?id=apply

**Comment by cwtuan** [comment]
Thanks
