### ISSUE TITLE
ERROR syntax color

### ISSUE THREAD

**Issue by Schvifty** [Binaryify/OneDark-Pro#145]
Hi,

WARNING syntax in .log/txt files seems to be red color but ERROR syntaxes is green.
Is it possible to change this to red also and maybe set them as **bold** text?

![image](https://user-images.githubusercontent.com/18008933/30428441-dc4b56e2-9953-11e7-87b4-1e167b5f9fed.png)

![image](https://user-images.githubusercontent.com/18008933/30428466-f1a59cdc-9953-11e7-82a1-99e0c9a46729.png)

**Comment by jens1o** [comment]
May you send the code please?

**Comment by svipben** [comment]
@k4nai Can you reproduce this again? And if there is the same problem could you please send us the code or that log file to test?

**Comment by markypython** [comment]
@Endilus You could try some custom configuration in settings.json like this:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "scope": "log.error",
      "settings": {
        "foreground": "#af1f1f",
        "fontStyle": "bold"
      }
    },
    {
      "scope": "log.warning",
      "settings": {
        "foreground": "#f4ad42"
      }
    },
    {
      "scope": "log.info",
      "settings": {
        "foreground": "#98c379"
      }
    }
  ]
}
```
