### ISSUE TITLE
Some ligatures not rendering

### ISSUE THREAD

**Issue by rensa** [Binaryify/OneDark-Pro#146]
Not all ligatures seem to be rendered when using One Dark Pro. In particular, less than and greater than are not rendered.

Also, in R, some operators that use multiple characters, like `<-`, aren't highlighted as operators.

I'm using macOS 10.12.6, VSCode 1.16.0, One Dark Pro 2.10.11 and the Fira Code font (with ligatures enabled in the user settings).

**Comment by jens1o** [comment]
This seems to be an vscode issue. We do not overrule ligatures at all. Please create a vscode issue and link it to here, so we can track its status.
