### ISSUE TITLE
Comment is too dark

### ISSUE THREAD

**Issue by Yensan** [Binaryify/OneDark-Pro#148]
When I turn on OneDark-Pro, comment text is too dark to see. Please give a brighter color and make an enough color contrast between the background color and comment text color. 
vs code default theme "Default Dark+" is better in color contrast of  comment/background.  Maybe you can just folow the setting of comment text color.

**Comment by garritfra** [comment]
[Fix Request :)](https://github.com/garritfra/OneDark-Pro/pull/1/commits/d425218360179f9d68017a5891cebd2271a65ba7)

**Comment by jens1o** [comment]
merged, closed. Coming in the next release. :)

Thanks @garritfra

**Comment by jens1o** [comment]
<< is an idiot.

**Comment by jens1o** [comment]
tbh, I think the change is too extrem:
Having now:
![image](https://user-images.githubusercontent.com/11234139/31189058-42a42534-a937-11e7-98a4-feeb24974163.png)

Incoming:
![image](https://user-images.githubusercontent.com/11234139/31189065-4a3166c2-a937-11e7-98a3-8e9e39b952c3.png)

**Comment by garritfra** [comment]
maybe make it a little bit darker again?

**Comment by jens1o** [comment]
cc @Binaryify for his opinion.

**Comment by Binaryify** [comment]
@garritfra I think that is good, could you send the PR

**Comment by garritfra** [comment]
Done. Relatively new to GH so I don't know if I have done everything correctly.

**Comment by Yensan** [comment]
Great job ! Thanks all of you.

> cc @Binaryify for his opinion.

Maybe he is right, because colors in this theme is designed for token or var in code, but grey is for comment / block comment.

**Comment by Yensan** [comment]
> <<is an idiot.

May you guys think this issue is not necessary. But for a user, although I can edit the color hex code, but I don't want to edit it every time when it updating. Life is short, we need out-of-the-box theme&thing.

**Comment by jens1o** [comment]
@Yensan Please keep calm. It's not the time to come up with such phrases. Of course we're on it. Remember, that we're doing this in our freetime(and for free). In 20 minutes for example, I need to go to school. You may take a look at custom modifications, [that can be located into your user settings](https://code.visualstudio.com/updates/v1_15#_user-definable-syntax-highlighting-colors).

**Comment by Yensan** [comment]
Thanks you guys for the theme, and thank you for advice.

**Comment by Binaryify** [comment]
@Yensan thank you too 🎉

**Comment by garritfra** [comment]
should this issue be closed?

**Comment by Binaryify** [comment]
@garritfra I think yes

**Comment by jens1o** [comment]
@Binaryify 
![image](https://user-images.githubusercontent.com/11234139/31289115-06428184-aac8-11e7-82da-9ba18d448901.png)

I think you forgot to update one. Do you take that job?

**Comment by Binaryify** [comment]
@jens1o 
oh, I ignore it, wait

**Comment by Binaryify** [comment]
@jens1o 
done
