### ISSUE TITLE
[FIXED] v2.10.15 comments changed

### ISSUE THREAD

**Issue by MaxMilton** [Binaryify/OneDark-Pro#150]
Commit https://github.com/Binaryify/OneDark-Pro/commit/9bc463439e8b28a63220d1a5da433a94cdd7341e drastically changed how comments are styled.

This is just a quick tip for anyone who wants to revert to the old comment style. Add this to your user settings:
```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "comment, punctuation.definition.comment",
                "settings": {
                    "foreground": "#5C6370"
                }
            },
            {
                "scope": "comment.line.double-slash,comment.block.documentation",
                "settings": {
                    "fontStyle": "italic"
                }
            }
        ]
    },
```

Thanks for the great theme, it was a big factor that allowed me to switching to VS Code from Atom :heart:

**Comment by Binaryify** [comment]
thank you❤️

**Comment by jens1o** [comment]
@Binaryify Personally, I would add this to the readme, and close this issue. Users will more likely read the readme than searching in the issues.

**Comment by Binaryify** [comment]
@jens1o you are right, will add it to the README

**Comment by Binaryify** [comment]
@jens1o donw

**Comment by jens1o** [comment]
thx

**Comment by arthurwhite** [comment]
Thanks @MaxMilton for the snippet and @Binaryify for the theme.

However, I still don't understand how 9bc4634 could be an improvement.
On the Vivid version, the comments now have the same color as any other uncolored fragment so identifying them at first sight takes more time:

![capture d ecran 2017-10-12 a 11 25 54](https://user-images.githubusercontent.com/9503891/31489210-41ed6a4c-af40-11e7-9416-d976a68e70a9.png)

**Comment by jens1o** [comment]
@arthurwhite The vivid version is a relict of the past. You may want to end up on using the normal version and modifying your user settings to disable the italic.

**Comment by arthurwhite** [comment]
That's too bad, I really liked this energetic vibe from the Vivid.
But OK, thank you for the clarification.
