### ISSUE TITLE
Typo in OneDark-Pro-vivid.json comment color code

### ISSUE THREAD

**Issue by dcervenkov** [Binaryify/OneDark-Pro#151]
https://github.com/Binaryify/OneDark-Pro/blob/9bc463439e8b28a63220d1a5da433a94cdd7341e/themes/OneDark-Pro-vivid.json#L87

I'm pretty sure this is a typo as hex color codes have 6 digits. You probably wanted to write `#5c6370`.
Without this correction, the comments are the same color as normal text.

**Comment by jens1o** [comment]
@dcervenkov That's a good first pr. Do you want to take it? :)

**Comment by dcervenkov** [comment]
@jens1o A one character pull request? :smile: Sure, I'm on it.

**Comment by jens1o** [comment]
well, apparently @Binaryify was faster ;)

**Comment by dcervenkov** [comment]
Faster than what?

**Comment by jens1o** [comment]
faster than you :(
