### ISSUE TITLE
Single line comments and JSDoc comments not italic

### ISSUE THREAD

**Issue by floriangosse** [Binaryify/OneDark-Pro#153]
In my javascript code the single line and JSDoc comments have a strange behavior: The characters which indicates that the following is a comment are italic but the comment itself is not italic anymore.

![image](https://user-images.githubusercontent.com/3819038/31664454-c2598482-b345-11e7-957b-f59012902685.png)

To make sure that no other extension cause this error I disabled all extensions except the theme itself and tried it again but I didn't change anything.

**Comment by jens1o** [comment]
@Binaryify 

But I think this behaviour is on purpose, and I love it, although I dont use `////` comments

**Comment by floriangosse** [comment]
I only used `////` to show the difference.

I saw italic comments it on different screenshots of the theme so I thought this seems to be a bug. If it's not a bug please close this issue and I will try to find a solution. :-)

**Comment by waterdanceTV** [comment]
@jens1o @floriangosse maybe you are right, will fix it soon

**Comment by Binaryify** [comment]
@jens1o 
@floriangosse 
maybe you are right, will fix it soon~

**Comment by ekfuhrmann** [comment]
It seems odd that comments in JS are not italic, yet everywhere else (html, pug, php) they are italic.

Would you be willing to at least standardize them so that JS commenting works the same as the others, whether that be italic or not?

**Comment by Binaryify** [comment]
@ekfuhrmann 
no, some people like this, if another people don't like this, they also can config that on setting.json

**Comment by ekfuhrmann** [comment]
How would one go about editing this within setting.json? I'm unfamiliar with the terms to make the change and don't see anything in the documentation regarding italics.

**Comment by Binaryify** [comment]
@ekfuhrmann 
you can read this part
https://binaryify.github.io/OneDark-Pro/#/?id=workbench-theming

**Comment by floriangosse** [comment]
@Binaryify you can only change colors but not the style of the token.

**Comment by floriangosse** [comment]
I found out that you can set more then just colors.
```
// ...
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "comment.line.double-slash,comment.block.documentation",
            "settings": {
                "fontStyle": "italic"
            }
        }
    ]
},
// ...
```
