### ISSUE TITLE
No color coding difference between one dark pro and one dark pro vivid after changed to one dark pro vivid

### ISSUE THREAD

**Issue by tangorboyz** [Binaryify/OneDark-Pro#154]
![image](https://user-images.githubusercontent.com/8751130/31845757-1cdb14ea-b637-11e7-9eed-060568c64e13.png)
Version: 2.10.17
VsCode: 1.17.2
It's in one dark pro. In one dark pro, the color for function/constructor parameters should be in white, or that i notice before changed to one dark pro vivid.

**Comment by jens1o** [comment]
@Binaryify

**Comment by Binaryify** [comment]
why the color for function/constructor parameters should be white
in atom like this 
![image](https://user-images.githubusercontent.com/12221718/32159920-6fba821c-bd1d-11e7-80f8-94471a67caf5.png)
