### ISSUE TITLE
Update regexp coloring

### ISSUE THREAD

**Issue by bsvipas** [Binaryify/OneDark-Pro#155]
VS Code improved regexp coloring for Dark+ theme so I guess it can be updated in this theme as well, because new scopes was introduced.

https://code.visualstudio.com/updates/v1_17#_improved-colorization-in-dark-and-light-themes

**Comment by jens1o** [comment]
I'm lacking of time, @Binaryify could you that please?

**Comment by Binaryify** [comment]
oh, I miss this issue, will deal it tomorrow

**Comment by Binaryify** [comment]
done, check if it is good

**Comment by bsvipas** [comment]
Yeah, I like it, it's way better!
