### ISSUE TITLE
can selected word be different from the same word？

### ISSUE THREAD

**Issue by ray0324** [Binaryify/OneDark-Pro#157]
<img width="531" alt="qq20171111-231115 2x" src="https://user-images.githubusercontent.com/5204198/32690697-4e6afafe-c6c0-11e7-88e2-deb627ce4654.png">

**Comment by Binaryify** [comment]
could provide some code

**Comment by darsain** [comment]
I think the issue here is that these 2 colors are the same, which is pretty bad usability vise:

```js
    "editor.selectionBackground": "#484e5b",
    "editor.selectionHighlightBackground": "#484e5b",
```

Forced me to do manual tweaking via `workbench.colorCustomizations` which I really dislike doing.

**Comment by Binaryify** [comment]
will consider it

**Comment by Binaryify** [comment]
@darsain 
what color do you think will be better

**Comment by darsain** [comment]
I've set it for myself to these colors:

```js
"editor.selectionBackground": "#67769660",
"editor.selectionHighlightBackground": "#ffffff10",
```

Which looks like this:

![image](https://user-images.githubusercontent.com/538801/34868624-b02387da-f784-11e7-83a2-5fc2973bbd5b.png)

I'm using colors with alpha channel due to recommendations in this issue: https://github.com/Microsoft/vscode/issues/34105

**Comment by Binaryify** [comment]
@ray0324 @darsain 
I had update it, please check if it's better

**Comment by svipben** [comment]
I can't reproduce this issue I believe it can be closed?

/cc @ray0324 @darsain
