### ISSUE TITLE
Inline code not colored correctly in markdown files

### ISSUE THREAD

**Issue by athrunsun** [Binaryify/OneDark-Pro#158]
Here is how it should be according to README.md of this repo:
![screenshot-markdown](https://raw.githubusercontent.com/Binaryify/OneDark-Pro/master/static/screenshot1.png)

And here is how it is in my current installation:
![screenshot-my-installation](https://i.imgur.com/Z2U1CZK.png)

NOTE inline code is colored grey, which is the same as plain text.

OS: MacOS 10.13.1
VSCode version: 1.18.0
OneDark-Pro version: 2.10.20

Please comment if you need me to provide more information.

**Comment by Binaryify** [comment]
OMG, it's really a bug, will fix it, but working busy now

**Comment by athrunsun** [comment]
@Binaryify Don't worry, take your time.

**Comment by Binaryify** [comment]
already publish, please check it

**Comment by athrunsun** [comment]
@Binaryify Well, the color changes, but:
![Imgur](https://i.imgur.com/tQZmkv3.png)

shoudn't it be the green color instead of grey according to this demo screenshot in README.md? Or you've changed your mind?
![screenshot-markdown](https://raw.githubusercontent.com/Binaryify/OneDark-Pro/master/static/screenshot1.png)

**Comment by Binaryify** [comment]
I think gray is as same as their display in page, but green is good to read in .md file, what color do you think is better

**Comment by athrunsun** [comment]
@Binaryify I think green is better.

**Comment by Binaryify** [comment]
@athrunsun ok, will change it to green

**Comment by Binaryify** [comment]
done

**Comment by athrunsun** [comment]
@Binaryify Looks cool now, thanks for the fix!
