### ISSUE TITLE
Diff syntax is not working anymore

### ISSUE THREAD

**Issue by rafaelmaiolla** [Binaryify/OneDark-Pro#16]
After last updates, the diff syntax highlight is not working anymore.

**Comment by Binaryify** [comment]
I will review it and fix it soon, thx~

**Comment by Binaryify** [comment]
Can you provide a screenshot? @rafaelmaiolla

**Comment by rafaelmaiolla** [comment]
You will probably need to install the [diff](https://marketplace.visualstudio.com/items?itemName=rafaelmaiolla.diff) extension

Then create a new file, set the language to "diff" and add the following code.

```
diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index 2a174b1..7748340 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -97,9 +97,7 @@ build-job:
+      # This is an added line
-      # This is an removed line
```

This was working before and it also works with the default theme.

**Comment by Binaryify** [comment]
@rafaelmaiolla 
I got it,will fix it soon, thx~

**Comment by Binaryify** [comment]
@rafaelmaiolla I fix it, please update and check it, thx~

**Comment by rafaelmaiolla** [comment]
It is working fine now. thanks!

**Comment by IOriens** [comment]
The conflict parts in diff files are not highlighted.
![image](https://user-images.githubusercontent.com/8137136/29500353-a07e15fa-8652-11e7-82a0-67dc9c2effb9.png)
---
vscode: Version 1.15.1 (1.15.1).
one dark pro: 2.10.8
system: macOS 10.12.6

**Comment by Binaryify** [comment]
@IOriens 
Can you provide your code?

**Comment by IOriens** [comment]
Ok, that it. @Binaryify 
[vue-wcc.diff.zip](https://github.com/Binaryify/OneDark-Pro/files/1237730/vue-wcc.diff.zip)

**Comment by Binaryify** [comment]
oh, I got it, will fix it, thanks for your feedback

**Comment by Binaryify** [comment]
@IOriens 
done

**Comment by IOriens** [comment]
@Binaryify 
Just upgraded this plugin, it works now, thanks a lot.

**Comment by Binaryify** [comment]
@IOriens 
OK
