### ISSUE TITLE
Support for italics seems limited to React JSX?

### ISSUE THREAD

**Issue by Manish-Giri** [Binaryify/OneDark-Pro#161]
In Visual Studio Code, I just noticed that for fonts like Operator Mono, italics are not displayed with regular HTML, CSS and JavaScript. Here are some screenshots -

JavaScript - 
![screenshot 2017-11-20 01 51 24](https://user-images.githubusercontent.com/11348778/33005825-a3d78bd4-cd95-11e7-8cd0-c88c2bd85965.png)

CSS -
![screenshot 2017-11-20 01 51 37](https://user-images.githubusercontent.com/11348778/33005836-b67ffaf0-cd95-11e7-8c85-2ee02ed15509.png)

It only seems to work in React JSX (`.jsx`) files -

![screenshot 2017-11-20 01 49 56](https://user-images.githubusercontent.com/11348778/33005869-ec0aeaa4-cd95-11e7-8011-968e629a5d38.png)

---

Here are the italics being displayed using the Monokai color scheme for the same JS and CSS files -

JS -
![screenshot 2017-11-20 01 52 06](https://user-images.githubusercontent.com/11348778/33005893-127ceb06-cd96-11e7-9996-03ddf2b7c49e.png)

CSS -

![screenshot 2017-11-20 01 52 15](https://user-images.githubusercontent.com/11348778/33005907-1dd624ae-cd96-11e7-88c3-48632624f255.png)

**Comment by Binaryify** [comment]
I make this theme's italics part look like as Atom, sorry can't make it look like as sublime

**Comment by Binaryify** [comment]
if you want change it, you can read this
https://binaryify.github.io/OneDark-Pro/#/?id=user-definable-syntax-highlighting-colors
