### ISSUE TITLE
Golang string supports SQL syntax bright

### ISSUE THREAD

**Issue by IIInsomnia** [Binaryify/OneDark-Pro#167]
![afdabb0a-d360-447d-9808-1e0334221fa2](https://user-images.githubusercontent.com/6582246/33978403-7b10c14a-e0da-11e7-9e03-94e4c60f7905.png)

**Comment by Binaryify** [comment]
could you provide the code on your screenshot

**Comment by IIInsomnia** [comment]
like this:
![image](https://user-images.githubusercontent.com/6582246/34970170-c54779ce-faad-11e7-882f-aed821c0c55f.png)

**Comment by Binaryify** [comment]
send that code to this

**Comment by Binaryify** [comment]
the "xxxxxxxxx" scope is string.quoted.double.go in vscode
if support it, need syntax parsing, but that not theme's job

**Comment by IIInsomnia** [comment]
Well, thanks a lot!
