### ISSUE TITLE
cursor's color is better for blue like atom

### ISSUE THREAD

**Issue by IIInsomnia** [Binaryify/OneDark-Pro#168]

**Comment by jens1o** [comment]
So you'd like to have the cursor color in blue and not in yellow?

Feel free to do this in your settings:
https://binaryify.github.io/OneDark-Pro

**Comment by Binaryify** [comment]
will consider it

**Comment by Binaryify** [comment]
@IIInsomnia 
done

**Comment by lixiaoyan** [comment]
![image](https://user-images.githubusercontent.com/1610614/34929578-9adf189e-f9ff-11e7-8454-b2455542b3af.png)

OneDark Pro + VSCodeVim

**Comment by Binaryify** [comment]
@lixiaoyan 
any more detail?

**Comment by lixiaoyan** [comment]
@Binaryify Vim normal mode uses block cursor, which will highlights the whole char next to the cursor. The character highlighted should use white as its text color rather than its original color.

**Comment by Binaryify** [comment]
@IIInsomnia @lixiaoyan 
I think I should change it back

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/34935582-54593d4a-fa19-11e7-9a63-2f75126cb283.png)
![image](https://user-images.githubusercontent.com/12221718/34935592-5ad27394-fa19-11e7-9515-53e47d7eba59.png)
how about this

**Comment by lixiaoyan** [comment]
@Binaryify Looks good, wondering if it will be released soon.

**Comment by Binaryify** [comment]
@lixiaoyan 
it just released, you can check it now

**Comment by IIInsomnia** [comment]
thanks!

**Comment by lixiaoyan** [comment]
![image](https://user-images.githubusercontent.com/1610614/34974244-fbbb9b66-fac6-11e7-8d52-831df7e97306.png)
![image](https://user-images.githubusercontent.com/1610614/34974249-050e538e-fac7-11e7-91b8-b1fca2c76743.png)

Select text in vim mode (visual mode)
