### ISSUE TITLE
Issue in Colors for C#

### ISSUE THREAD

**Issue by ritwickdey** [Binaryify/OneDark-Pro#169]
With OneDark:
![image](https://user-images.githubusercontent.com/18099464/34451926-bc3ca44a-ed5a-11e7-831a-9b38df7514ff.png)

With Default (Dark Plus)
![image](https://user-images.githubusercontent.com/18099464/34451956-04ff2afe-ed5b-11e7-94a9-64e63b70fd20.png)

> No separate color for `new`, `throw`

Is this issue ? or Default behavior?

**Comment by jens1o** [comment]
Could you give us the code please?

**Comment by ritwickdey** [comment]
![image](https://user-images.githubusercontent.com/18099464/34461876-b15ee670-ee5c-11e7-9744-51c34d139c03.png)


code block : 
```cs
namespace Something
{
    class SomeClass
    {
        public static void Main()
        {
            throw new System.NotImplementedException();
           
            // No diffrent color for `new` and `throw`
        }
    }
}
```

**Comment by Binaryify** [comment]
will fix it tomorrow

**Comment by jens1o** [comment]
Okkay :)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/34465706-5794ca72-eef4-11e7-892e-c2890073dec9.png)
how about this @ritwickdey

**Comment by ritwickdey** [comment]
It looks good 👍 ...

Thanks for the awesome extension & of course Happy New Year

**Comment by Binaryify** [comment]
done @ritwickdey  check it 😀

**Comment by ritwickdey** [comment]
Yep! Updated..!! It looks much good!! Thanks Again 😄
