### ISSUE TITLE
Multiline Function Colouring

### ISSUE THREAD

**Issue by iddan** [Binaryify/OneDark-Pro#171]
Because of the line break `interview` is not highlighted in blue

<img width="285" alt="screen shot 2018-01-08 at 22 07 08" src="https://user-images.githubusercontent.com/12671072/34690064-588e6614-f4c0-11e7-8005-34b02131a243.png">

Because of the parentheses `async` is highlighted in blue instead of `interview`

<img width="624" alt="screen shot 2018-01-08 at 22 04 12" src="https://user-images.githubusercontent.com/12671072/34689951-fe0f3e84-f4bf-11e7-810b-4eb54944a953.png">

**Comment by Binaryify** [comment]
I think it's vscode's problem, the scope issue
