### ISSUE TITLE
The color of cursor is a little dark.

### ISSUE THREAD

**Issue by IIInsomnia** [Binaryify/OneDark-Pro#174]

**Comment by IIInsomnia** [comment]
I prefer the previous version of the color. 😊

**Comment by Binaryify** [comment]
could you provide some screenshots

**Comment by pqvst** [comment]
I too find that the cursor color is very difficult to see (especially with colored text).
<img width="439" alt="screenshot 2018-01-18 12 09 22" src="https://user-images.githubusercontent.com/4990657/35095355-742176a2-fc48-11e7-8d7b-d76749c19b36.png">
<img width="388" alt="screenshot 2018-01-18 12 09 12" src="https://user-images.githubusercontent.com/4990657/35095360-7857b966-fc48-11e7-9bed-081b8b18210f.png">
<img width="418" alt="screenshot 2018-01-18 12 08 55" src="https://user-images.githubusercontent.com/4990657/35095362-7a66bf68-fc48-11e7-889c-b2539980f1a0.png">
