### ISSUE TITLE
对象的key和点运算符颜色可以和atom里的一样吗？

### ISSUE THREAD

**Issue by joenil** [Binaryify/OneDark-Pro#175]
![image](https://user-images.githubusercontent.com/11400674/35180485-8ec019b4-fdec-11e7-9ade-113c4174370f.png)
![image](https://user-images.githubusercontent.com/11400674/35180488-99154e7a-fdec-11e7-9aa6-8158a4ef6077.png)
感觉atom里的颜色要丰富一些。

**Comment by Binaryify** [comment]
实际上 atom 的颜色看上去是有点乱的
![image](https://user-images.githubusercontent.com/12221718/35202113-98ac65ac-ff5b-11e7-932e-29620bd7ee8b.png)
![image](https://user-images.githubusercontent.com/12221718/35202127-aaf9c52e-ff5b-11e7-830d-a3b8690a3272.png)

**Comment by joenil** [comment]
嗯，对象属性简写，也被着色成value的红色了。其实现在这样子已经很好了，感谢！
另外，最近鼠标光标的蓝色变暗了，太暗不容易定位到，可以改亮一点吗？

**Comment by Binaryify** [comment]
可能会再调整下
