### ISSUE TITLE
Editor tabs

### ISSUE THREAD

**Issue by svipben** [Binaryify/OneDark-Pro#176]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_20.md#more-themable-colors-for-editor-tabs

I suggest to update it after 1.20 version. Thank you!

**Comment by Binaryify** [comment]
sorry for busy in these days
you can read this https://binaryify.github.io/OneDark-Pro/#/
and this https://code.visualstudio.com/docs/getstarted/theme-color-reference
if you want create a PR, I will very appreciate it

**Comment by svipben** [comment]
@Binaryify Thanks, I didn't know about that website. I will create a PR. 👷

**Comment by svipben** [comment]
@Binaryify Already opened PR: https://github.com/Binaryify/OneDark-Pro/pull/179. Check if colors are good for you.
