### ISSUE TITLE
Can you support pycharm

### ISSUE THREAD

**Issue by tblxdezhu** [Binaryify/OneDark-Pro#177]
love this theme very much , do you have plan support pycharm, thank you very much

**Comment by Binaryify** [comment]
not any plan

**Comment by fdemmer** [comment]
@tblxdezhu https://github.com/yurtaev/idea-one-dark-theme

**Comment by xLI4n** [comment]
> @tblxdezhu https://github.com/yurtaev/idea-one-dark-theme

tks, unexpectedly, the answer I found today was a question I asked four years ago. WTF... My preferences are the same as always...thank you

**Comment by HoseynAAmiri** [comment]
Have you developed it for pycharm yet? @Binaryify
