### ISSUE TITLE
Handlebars if/else coloring

### ISSUE THREAD

**Issue by bsvipas** [Binaryify/OneDark-Pro#178]
![image](https://user-images.githubusercontent.com/30043375/35917050-4ed08f0a-0c15-11e8-87e4-71a28b880953.png)

As you can see there's no color for `table.isEmpty` which is supposed to be the same as `if` I guess.

**Comment by svipben** [comment]
@jens1o I can create a PR, but I need to know which one `scope` I need to use.

**Comment by svipben** [comment]
I can fix this too. I can use these all 3 scopes which are in the screenshot to detect and colorize the `table.isEmpty` like it's with `if`, etc. But I don't know if it's correct if you know which scopes I need to use I can definitely open a PR.

/cc @Binaryify

**Comment by svipben** [comment]
Okay, I see this is VS Code problem so it will not be possible to have correct and clean support for this. The issue can be closed.

**Comment by Binaryify** [comment]
okay
