### ISSUE TITLE
React component tags in JSX

### ISSUE THREAD

**Issue by PhilMcVay** [Binaryify/OneDark-Pro#181]
Hi,

I have just installed the theme and have noticed that the react component tags (see below example) are highlighting yellow instead of red. I assume this is because it thinks it's a class?

![image](https://user-images.githubusercontent.com/25827239/36063289-d10addb8-0e72-11e8-96b3-3c26518fa170.png)

Do I need to change any settings in the JSON file?

**Comment by Binaryify** [comment]
that's a wrong highlight color, i will fix it

**Comment by Binaryify** [comment]
I just fix it, you can check it now

**Comment by PhilMcVay** [comment]
Great, it's fixed now. Thanks!
