### ISSUE TITLE
React components highlighted in a wrong way

### ISSUE THREAD

**Issue by IAmStrong** [Binaryify/OneDark-Pro#182]
Before update the components were highlighted with the yellow color. Now the components highlighted just like other tags!

It is very confusing.

![image](https://user-images.githubusercontent.com/13998035/36077836-37f861d4-0f78-11e8-9233-d6cbb0fdcd4b.png)
![image](https://user-images.githubusercontent.com/13998035/36077843-55067298-0f78-11e8-8760-298be129b953.png)

**Comment by IAmStrong** [comment]
I can't now distinguish between usual tags and Components.

**Comment by Binaryify** [comment]
now it just more look like atom's highlight, and you can custom it on setting.json
![image](https://user-images.githubusercontent.com/12221718/36081115-b9e37550-0fd5-11e8-8f02-c0a31741914a.png)
https://binaryify.github.io/OneDark-Pro/#/?id=user-definable-syntax-highlighting-colors

**Comment by bendersej** [comment]
Add these lines to your editor config to override this change.

```
"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"name": "js/ts support.class.component",
				"scope": "support.class.component",
				"settings": {
					"foreground": "#e5c07b"
				}
			}
		],
	},
```

**Comment by etiennejcharles** [comment]
I beleive the change was made here: 
https://github.com/Binaryify/OneDark-Pro/commit/2616798edbc844d9661dcf8ecd7d567b833d0fda

I'm just curious as of why this is considered an "improvement" @Binaryify 
Could clarify the "why" behind the change ?
