### ISSUE TITLE
Why everything in Javascript React is red now

### ISSUE THREAD

**Issue by zalishchuk** [Binaryify/OneDark-Pro#183]
Why `v2.12.4` update made everything red in `Javascript React` syntax highlight. 

Visual Studio Code highlighting:
![One Dark Pro highlight](https://user-images.githubusercontent.com/2690794/36119943-3ee27ba6-104a-11e8-8811-512c0c9e0969.png)

Atom highlighting:
![Atom One Dark highlight](https://user-images.githubusercontent.com/2690794/36120028-7d489786-104a-11e8-9f68-a54881015049.png)

**Comment by Binaryify** [comment]
but in Atom's JavaScript with JSX look like this
![image](https://user-images.githubusercontent.com/12221718/36135320-6934b86c-10c5-11e8-8e2c-825aaa62ca99.png)

**Comment by zalishchuk** [comment]
My personal opinion is `One Dark Pro` should stick to Atom [language-babel](https://atom.io/packages/language-babel) language package. Your opinion on this matter?
