### ISSUE TITLE
Discuss: JSX's component tags color should be red or yellow

### ISSUE THREAD

**Issue by Binaryify** [Binaryify/OneDark-Pro#184]
I notice that some people think it should be red and others think it should be yellow, but I don't know which one will be better(now is red)
https://github.com/Binaryify/OneDark-Pro/issues/181
https://github.com/Binaryify/OneDark-Pro/issues/182
https://github.com/Binaryify/OneDark-Pro/issues/183
I have not idea now
@PhilMcVay
@zalishchuk
@IAmStrong
@bendersej

**Comment by jens1o** [comment]
Personally I'd stick to yellow, because a little bit more contrast is always good.

**Comment by PhilMcVay** [comment]
I like the red highlighting as it separates the class/component declaration and the JSX/HTML tags. All other HTML elements highlight red as well so I find it reads easier if the JSX tags are the same colour.

I don't mind either way to be honest. If the majority vote yellow it's understandable.

**Comment by keeganstothert** [comment]
yellow please!!! the red is not distinct and differs from the babel-language highlighting in atom

**Comment by zalishchuk** [comment]
As I mentioned in my issue, my personal opinion is `One Dark Pro` should match Atom [One Dark](https://atom.io/themes/one-dark-syntax) syntax used with Atom [language-babel](https://atom.io/packages/language-babel) grammar.

**Comment by IAmStrong** [comment]
Yellow please, as it clearly separates tags from components.

**Comment by svipben** [comment]
I suggest using Yellow. Because right now there's everywhere red color. And as @jens1o said a little more contrast is always good.

**Comment by Binaryify** [comment]
@PhilMcVay I think I should change it back, but I will tell you how to change it to yellow in your setting.json

**Comment by PhilMcVay** [comment]
That's fine @Binaryify. Thanks.

**Comment by zalishchuk** [comment]
@Binaryify so what's about proposal, should not we follow `language-babel` grammar?

**Comment by Binaryify** [comment]
@zalishchuk I will make it look like as atom's language-babel grammar's highlight

**Comment by Binaryify** [comment]
@PhilMcVay 
add this in your setting, it will make it red 
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "js/ts support.class.component",
        "scope": "support.class.component",
        "settings": {
          "foreground": "#e06c75ff"
        }
      }
    ]
  },
```
![image](https://user-images.githubusercontent.com/12221718/36624618-5c7298da-194c-11e8-8b77-ef2fd957b641.png)
