### ISSUE TITLE
Better bracket visibility in code

### ISSUE THREAD

**Issue by nicovak** [Binaryify/OneDark-Pro#185]
Hello,

Sometimes I am experiencing some visibility issues with the caret and matching brackets style.
VS Code now allow to modify some parameters, below an example :

Before

![Before](https://i.imgur.com/iZoSgNB.png)

After

![After](https://i.imgur.com/WinJpd1.png)

We maybe should play with thoses parameters for a better experience.

**Comment by jens1o** [comment]
Would you like to provide a pr?

**Comment by nicovak** [comment]
@jens1o Done :)
