### ISSUE TITLE
Bad cursor visibility, especially when surrounded by current bracketMatch styling

### ISSUE THREAD

**Issue by darsain** [Binaryify/OneDark-Pro#189]
Problem: Find the cursor.

![image](https://user-images.githubusercontent.com/538801/36394456-a7431ec0-15b4-11e8-9a98-513142fe5077.png)

I suggest these colors:

```
"editorCursor.foreground": "#fff",
"editorBracketMatch.border": "#0000",
"editorBracketMatch.background": "#fff1",
```

Result:

![image](https://user-images.githubusercontent.com/538801/36394486-c3bf1ac2-15b4-11e8-8975-dfee61eb65c2.png)

**Comment by bsvipas** [comment]
@darsain for me cursor visibility is good so this is kinda personal preference and I see no point to change it.

**Comment by Or3stis** [comment]
I use this color value #528bff for my cursor. It is the same one as in Atom. It improves the visibility.

Before
<img width="185" alt="screen shot 2018-03-11 at 13 54 58" src="https://user-images.githubusercontent.com/11923550/37254423-937bfd40-2535-11e8-941c-65f1427bd720.png">

After (cursor value #528bff)
<img width="199" alt="screen shot 2018-03-11 at 13 54 18" src="https://user-images.githubusercontent.com/11923550/37254425-99e665da-2535-11e8-9c64-0ffabc0d0ead.png">

Should I make a PR?

**Comment by svipben** [comment]
@Or3stis You're right in Atom cursor color is: `#528bff`. I will create a PR, thanks a lot @Or3stis.

**Comment by svipben** [comment]
Done in this PR: https://github.com/Binaryify/OneDark-Pro/pull/205
