### ISSUE TITLE
Disable JSDoc Comment Coloring

### ISSUE THREAD

**Issue by bwsinger** [Binaryify/OneDark-Pro#190]
I want to be able to disable multicolored JSDoc comments.

The highlighting is cool, but if most of the functions on a page have colored comments, it becomes difficult to differentiate the functions from the comments. For example, this whole comment would be the default color:

![dlxzalj - imgur](https://user-images.githubusercontent.com/16724046/36571740-27b8edde-17ed-11e8-9d66-2d99fd3db980.png)

Is it possible to either add in this option or point out the color options needed to change this?

**Comment by Binaryify** [comment]
add this in your settings.json
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "storage.type.class.jsdoc",
        "scope":
          "storage.type.class.jsdoc,entity.name.type.instance.jsdoc,variable.other.jsdoc",
        "settings": {
          "foreground": "#7f848eff"
        }
      }
    ]
  },
```

![image](https://user-images.githubusercontent.com/12221718/36624674-17cfd1e2-194d-11e8-909c-35a1e149de77.png)

**Comment by bwsinger** [comment]
This is exactly what I wanted. Thank you!

**Comment by Swennet** [comment]
This doesn't seem to work for me. (in PHP files, if that matters)

Any suggestions?

![code_2018-04-13_16-26-38](https://user-images.githubusercontent.com/18725185/38740294-834312bc-3f37-11e8-9569-c7f5573921a9.png)

![code_2018-04-13_16-27-03](https://user-images.githubusercontent.com/18725185/38740300-8517d47e-3f37-11e8-9de9-760342f319eb.png)

**Comment by Binaryify** [comment]
@Swennet 
you need check that code scope first, then change it
![image](https://user-images.githubusercontent.com/12221718/38765002-2f3b60ba-3fec-11e8-852a-1188600044d1.png)

**Comment by Swennet** [comment]
Sorry, I'm fairly new to VS code. How do I bring up this window?

**Comment by Binaryify** [comment]
@Swennet 
you can check this 
https://binaryify.github.io/OneDark-Pro/#/
