### ISSUE TITLE
Different colors in String Interpolation for a nicer visual grepping

### ISSUE THREAD

**Issue by Or3stis** [Binaryify/OneDark-Pro#191]
The current string interpolation configuration is something like this
<img width="274" alt="screen shot 2018-02-25 at 17 52 12" src="https://user-images.githubusercontent.com/11923550/36644704-409d1332-1a56-11e8-8608-cf9cb6cd92ea.png"> (OneDark Pro)
In the first line, it is quite easy to distinguish between the string and the variable. On the other hand, the majority of the second line is colored red, making the visual distinction more difficult.

One Dark in Atom handles string interpolation like this
<img width="272" alt="screen shot 2018-02-25 at 17 53 22" src="https://user-images.githubusercontent.com/11923550/36644744-c90d4098-1a56-11e8-8846-5a8d993f8ce4.png"> (One Dark in Atom)
And the Dark+ in vscode has a different approach
<img width="267" alt="screen shot 2018-02-25 at 17 52 34" src="https://user-images.githubusercontent.com/11923550/36644751-d32e2ce0-1a56-11e8-8a50-ae09642fc9bd.png"> (Dark+ in vscode)

These color themes provide a nice visual grepping for interpolated strings.

In my editor, I have made this adjustment to the OneDark Pro
<img width="277" alt="screen shot 2018-02-25 at 18 18 11" src="https://user-images.githubusercontent.com/11923550/36644875-4b46150c-1a58-11e8-9cec-8228dbd5f003.png">

This color change is closer the Dark+ than One Dark though.

Is this something that you would like me to contribute?

**Comment by jens1o** [comment]
I like it, but let's wait what @Binaryify says.

**Comment by Binaryify** [comment]
good, I will improve it
