### ISSUE TITLE
support.constant.* color not set?

### ISSUE THREAD

**Issue by optikfluffel** [Binaryify/OneDark-Pro#196]
Shouldn't there be a color set for `support.constant.*` (or something similar)? I think [akamud/vscode-theme-onedark](https://github.com/akamud/vscode-theme-onedark) has it and that's where for example Elm constant highlighting comes from:

vscode-theme-onedark:
![vscode-theme-onedark](https://user-images.githubusercontent.com/379915/37030075-da7f21ea-2139-11e8-99cd-31402c846021.png)

vs OneDark-Pro:
![onedark-pro](https://user-images.githubusercontent.com/379915/37030084-e423656c-2139-11e8-85ee-e8c4863513ee.png)

**Comment by optikfluffel** [comment]
@Binaryify I'm not sure of what so here we go:

the corresponding part of [akamud/vscode-theme-onedark/themes/OneDark.json](https://github.com/akamud/vscode-theme-onedark/blob/11ef483921495ea6c086f56149dfa0ca6225ae53/themes/OneDark.json):
```json
{
  "name": "[VSCODE-CUSTOM] Support Constant",
  "scope": "support.constant",
  "settings": {
    "foreground": "#D19A66"
  }
}
```

here's the Elm snippet from the screenshots:

```elm
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    SocketConnected ->
        ( { model | connected = True }, Cmd.none )

    SocketDisconnected ->
        ( { model | connected = False }, Cmd.none )
```

**Comment by Binaryify** [comment]
did you have install some elm extension

**Comment by optikfluffel** [comment]
Yes, [Krzysztof-Cieslak/vscode-elm](https://github.com/Krzysztof-Cieslak/vscode-elm).

**Comment by optikfluffel** [comment]
I just found another example where OneDark-Pro has "less" syntax highlighting than [akamud/vscode-theme-onedark](https://github.com/akamud/vscode-theme-onedark), for `Maybe`, `Nothing` and `Just`.

vscode-theme-onedark:
<img width="410" alt="one-dark" src="https://user-images.githubusercontent.com/379915/38136771-f6e2ea48-3420-11e8-8809-65fb3ef2e312.png">

vs OneDark-Pro:
<img width="415" alt="one-dark-pro" src="https://user-images.githubusercontent.com/379915/38136776-021d2fe0-3421-11e8-8679-c97757eb7365.png">

example code:
```elm
galleryListView : Maybe GalleryList -> Html Msg
galleryListView maybeGalleries =
    case maybeGalleries of
        Just galleries ->
            div [] (List.map galleryView galleries)

        Nothing ->
            p [] [ text "Still Connection.." ]
```

**Comment by jens1o** [comment]
It's always nice to know *which* language that is ;)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/39621477-8235e77e-4fc1-11e8-8150-7066062ad9c0.png)
right?

**Comment by optikfluffel** [comment]
@Binaryify lgtm ❤️

**Comment by markypython** [comment]
@Binaryify Is this issue fixed and if so, can this issue be closed?
