### ISSUE TITLE
The first double slashes are too oblique compared to the others

### ISSUE THREAD

**Issue by gmcinalli** [Binaryify/OneDark-Pro#197]
Here's a screenshot of what I mean with "too oblique":

![image](https://user-images.githubusercontent.com/9024983/37045587-992b2e78-2166-11e8-88fd-84712802231e.png)

The issue is only visible with this theme and with every file type.

**Comment by Binaryify** [comment]
because the other "/" is the part of the comment, if you want all "italic", the comment like also will be italic
![image](https://user-images.githubusercontent.com/12221718/37069848-2068aada-21f0-11e8-8f83-78b1002965b1.png)

**Comment by gmcinalli** [comment]
Ok thanks, and how can I set it in italic or normal? I had tried customizing the theme settings, without success.

**Comment by Binaryify** [comment]
copy this into your setting.json
```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name":"comment.line.double-slash",
        "scope":"comment.line.double-slash",
        "settings": {
          "fontStyle": "italic"
        }
      }
    ]
  }
```

**Comment by gmcinalli** [comment]
Thank you, and if I want it all normal? I've tried to put `normal` instead of `italic` and it doesn't work.

**Comment by Binaryify** [comment]
"none"

**Comment by Binaryify** [comment]
or just remove it

**Comment by gmcinalli** [comment]
No, if I remove it or put `none` it reverts back to this:

![image](https://user-images.githubusercontent.com/9024983/37045587-992b2e78-2166-11e8-88fd-84712802231e.png)

**Comment by Binaryify** [comment]
oh, i misunderstand what you mean
```
 {
        "name":"comment.line",
        "scope":"comment.line.double-slash,punctuation.definition.comment",
        "settings": {
          "fontStyle": "none"
        }
      }
```

**Comment by gmcinalli** [comment]
It works perfectly, thank you very much.
