### ISSUE TITLE
When use #ifdef #endif, code color become gray

### ISSUE THREAD

**Issue by f3wenbo** [Binaryify/OneDark-Pro#198]
When I use #ifdef and #endif in cpp file, the code color will become gray like the following snapshot.
![ws000120](https://user-images.githubusercontent.com/10846537/37066164-65e0f0c6-21e7-11e8-975f-a0e8c292686c.JPG)
Here is the source code.
```
#ifdef UVP_SW_HOME_MENU
	LONG	kind					= 0;				
	LONG	cid 					= 0;				
	LONG	authentication_function = 0;				
	LONG	authentication_id 		= 0;				
	LONG	user_auth				= 0;				
	LONG	dept_mode 				= 0;				
	LONG	display_disable 		= 0;				
	USHORT	dept_id					= 0;				
#endif
```

**Comment by Binaryify** [comment]
What should it look like
