### ISSUE TITLE
Edge Syntax Support

### ISSUE THREAD

**Issue by lffg** [Binaryify/OneDark-Pro#199]
Do you intend to support the [Edge Syntax](http://edge.adonisjs.com/)?
I'm using this [extension](https://marketplace.visualstudio.com/items?itemName=luongnd.edge) but it looks like the conditions do not stay with the default color (purple).

<div align="center"><img src="https://i.imgur.com/e9SyC9o.png" alt="print"></div>

**Comment by Binaryify** [comment]
will support it soon

**Comment by lffg** [comment]
Thanks. I'll wait for it. 😄

**Comment by Binaryify** [comment]
@lffg you can update and check it now

**Comment by lffg** [comment]
Thanks a lot. ;)
