### ISSUE TITLE
The cursor sometimes is thick and sometimes is thin.

### ISSUE THREAD

**Issue by IIInsomnia** [Binaryify/OneDark-Pro#207]
<img width="233" alt="qq20180314-164803 2x" src="https://user-images.githubusercontent.com/6582246/37391986-ed1fca56-27a7-11e8-8a56-3fd6e4e7efb7.png">

<img width="259" alt="qq20180314-164831 2x" src="https://user-images.githubusercontent.com/6582246/37391987-ed528df6-27a7-11e8-9dcf-19dccca4e535.png">

**Comment by Binaryify** [comment]
I think that might VS Code's bug, will figure it out

**Comment by IIInsomnia** [comment]
I think so.
