### ISSUE TITLE
(WIP) Redesign

### ISSUE THREAD

**Issue by svipben** [Binaryify/OneDark-Pro#208]
## Before

<img width="1439" alt="before" src="https://user-images.githubusercontent.com/10441177/37570649-e3af9bd0-2afa-11e8-820f-b631bfee472a.png">

## After

<img width="1439" alt="after" src="https://user-images.githubusercontent.com/10441177/37570651-e7c55e94-2afa-11e8-80b7-ca8c1964fdf7.png">

Still working on this, but the whole theme will be redesigned to match Atom One Dark.

_Currently working on UI redesign, next I will redesign syntax coloring. So I think I will create 2 different PRs._

**Comment by svipben** [comment]
What do you think guys?

/cc @Binaryify @jens1o

**Comment by Binaryify** [comment]
I think that is good

**Comment by Binaryify** [comment]
but maybe need a origin theme option, I not sure if people like the new UI, and one sad thing is json file don't support inherit or import/export

**Comment by jens1o** [comment]
Oh, that's awesome!

(I especially like the icon set you use ;))

**Comment by jens1o** [comment]
@svipben It was more like I maintain the icon set. ;)

Despite that, we do not allow ads.
