### ISSUE TITLE
[FIX] Change the foreground color to the Atom's default

### ISSUE THREAD

**Issue by gmcinalli** [Binaryify/OneDark-Pro#209]
Current:
![image](https://user-images.githubusercontent.com/9024983/37587545-f10cd198-2b5f-11e8-98a9-b0e0d3c1cece.png)

Edited:
![image](https://user-images.githubusercontent.com/9024983/37587607-1ac6bc38-2b60-11e8-8eef-f0aca07c720f.png)

Atom:
![image](https://user-images.githubusercontent.com/9024983/37587632-2b646e32-2b60-11e8-8f6e-283d35d1c865.png)

```javascript
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "js variable readwrite",
                "scope": "variable.other.readwrite,meta.object-literal.key,support.variable.property,support.variable.object.process,support.variable.object.node",
                "settings": {
                    "foreground": "#ABB2BF"
                }
            }
        ]
    },
```

**Comment by Binaryify** [comment]
make it to white isn't a good idea

**Comment by gmcinalli** [comment]
Ok, but in Atom this is the default color, it's mostly gray rather than white. I think that the current implementation is too red.

**Comment by gmcinalli** [comment]
Another question: is it possible to change the color of the constants even if not written completely in uppercase?

**Comment by Binaryify** [comment]
@gmcinalli 
no, because their scope is different

**Comment by IIInsomnia** [comment]
I agree with @gmcinalli , I think that the current implementation is too red.

**Comment by gmcinalli** [comment]
I just noticed that now the constants are colored exactly like in Atom!
@Binaryify Did you find a way to change their color, even if their scope was different?

**Comment by Binaryify** [comment]
@gmcinalli 
no, I think VS Code team just change it
