### ISSUE TITLE
add pointer operator color

### ISSUE THREAD

**Issue by IIInsomnia** [Binaryify/OneDark-Pro#210]
![image](https://user-images.githubusercontent.com/6582246/37950333-b9a8be9e-31ca-11e8-9a1e-a8fd2d03a538.png)

![image](https://user-images.githubusercontent.com/6582246/37950353-cc9593ce-31ca-11e8-8288-5e5f7ced2990.png)

**Comment by jens1o** [comment]
That's `golang`, isn't it?

**Comment by IIInsomnia** [comment]
Yeah！ @jens1o

**Comment by Binaryify** [comment]
how about this 
![image](https://user-images.githubusercontent.com/12221718/39621332-f5720a48-4fc0-11e8-985a-3638a67ed6f2.png)

**Comment by IIInsomnia** [comment]
Thanks！@Binaryify
