### ISSUE TITLE
Vue highlighting doesn't differentiate between html element and {{variable}}

### ISSUE THREAD

**Issue by andreas-groos** [Binaryify/OneDark-Pro#214]
In the template the following line is all in the same color 
```html
<custom-element>{{text}}</custom-element>
```

whereas ideally (like in Monokai etc) the variable would stand out in a different color. Tried different Vue extensions but the behavior seems to be on the theme side, Monokai for example differentiates element and {{expression}}.

**Comment by Binaryify** [comment]
could you provide sone screenshot?
