### ISSUE TITLE
[Javascript] Lowercase reserved keywords being highlighted

### ISSUE THREAD

**Issue by archcorsair** [Binaryify/OneDark-Pro#215]
Some variables that are lowercase versions of their uppercase reserved keywords like `Buffer` are appearing highlighted. Is this expected behavior? If it is, how can I change it in the config?

![image](https://user-images.githubusercontent.com/1036921/39018682-9bcd1b2c-43db-11e8-951d-c1b1b34fd013.png)

**Comment by Binaryify** [comment]
does that normal on new version vscode?

**Comment by archcorsair** [comment]
It is still happening on newest version of vscode, `Version 1.23.0 (1.23.0)`.

**Comment by archcorsair** [comment]
Still happening on `Version 1.28.2 (1.28.2)`

Type `let buffer = 123`, and it will highlight in yellow

**Comment by beastdestroyer** [comment]
I'm assuming this is javascript, also do you have any extensions since I still cannot make it yellow

**Comment by Binaryify** [comment]
@archcorsair 
This theme has been adapted to most ES2015+ syntax highlighting, most of the time you can do without  Babel extension  😁
