### ISSUE TITLE
Blue border around file explorer when focused

### ISSUE THREAD

**Issue by mignz** [Binaryify/OneDark-Pro#216]
Is it possible to remove or change the blue border around the file explorer when you click an empty space?

This is what I mean:

<img width="424" alt="screen shot 2018-04-23 at 22 39 32" src="https://user-images.githubusercontent.com/358114/39157058-8e80b3e6-4748-11e8-9ca0-6d0e7ecbebd8.png">

**Comment by mantyz** [comment]
@mignz You can change the `focusBorder` property in the user settings:
```json
"workbench.colorCustomizations": {
        "focusBorder": "#21252b"
}
```
[Base Colors](https://code.visualstudio.com/docs/getstarted/theme-color-reference#_base-colors)

**Comment by Binaryify** [comment]
@mantyz 
nice, will add this feature on next version
