### ISSUE TITLE
Highlighted indent guides.

### ISSUE THREAD

**Issue by GlenCFL** [Binaryify/OneDark-Pro#217]
Visual Studio Code v1.23 has been released, which includes a new feature that they're calling [Highlighted Indent Guides](https://code.visualstudio.com/updates/v1_23#_highlighted-indent-guides).

This is currently not supported by this theme.

**Comment by Binaryify** [comment]
I just support it, thanks for your advice

**Comment by GlenCFL** [comment]
Thanks for the quick update.
