### ISSUE TITLE
Changes I made to One Dark Pro Vivid

### ISSUE THREAD

**Issue by beastdestroyer** [Binaryify/OneDark-Pro#218]
Before I start, I really love this theme and is my primary theme of VSCode - awesome!

So, I tinkered with the file for ODPV and made some personal changes, which are active in my editor at time of writing. These changes mainly focused on HTML, CSS/SCSS/LESS, and JS as I do Front-End Development. Below is my edited ODPV file (in a zip as GitHub won't let me post .json), I have attempted to label everywhere I made edits with a [EDITED] prefix (though there may be some others), and added Custom styles at the bottom of the file, marked with [CUSTOM].

Some changes include:
• Unit (px, vh, vw, fr ...etc) highlighting for CSS/SCSS/LESS
• Pseudo-elements and classes are different colours from the default orangey to differentiate
• Class selectors are now slightly more greener, to reflect the colour of double quotes in HTML files

• JavaScript string literal `${}` is now differentiable from normal string
• Functions now orangey (this one was more of a personal preference)
• Class names are now red like variable names

I hope some changes here could be considered for a future update, thank you!

[OneDark-Pro-vivid edited.zip](https://github.com/Binaryify/OneDark-Pro/files/1975174/OneDark-Pro-vivid.edited.zip)

PS: ODPV meant One Dark Pro Vivid for those who might have been confused

**Comment by Binaryify** [comment]
new version could custom syntax color more easy now

**Comment by beastdestroyer** [comment]
Yup, thanks, closing
