### ISSUE TITLE
OneDark-Pro theme for Visual Studio 2017

### ISSUE THREAD

**Issue by Hedva** [Binaryify/OneDark-Pro#219]
I'm pretty new to Visual Studio. Using it for 2 weeks now, because I have to. I'm used to work with Atom and like the visual syntax style

I was wondering if there is an easy way for making this work on Visual Studio Professional 2017 (not Code).
Currently it doesn't work on Professional

**Comment by rp0m** [comment]
Would love to see this as well!

**Comment by altyne** [comment]
+1 also but the it was closed :(
