### ISSUE TITLE
`.get` `.post` colors are different

### ISSUE THREAD

**Issue by Voyager-One** [Binaryify/OneDark-Pro#220]
![snip20180512_1](https://user-images.githubusercontent.com/23122353/39954714-30eac7be-55f6-11e8-9aed-8ea655f5b15b.png)

`.get()` and `.post()` should be the same color

**Comment by Binaryify** [comment]
that's vscode bug

![image](https://user-images.githubusercontent.com/12221718/40094436-9032f1b4-58f9-11e8-81db-588fb4b36473.png)
![image](https://user-images.githubusercontent.com/12221718/40094438-92fa5748-58f9-11e8-87a1-6541f6e67ed4.png)

**Comment by Voyager-One** [comment]
it seems that Atom have the similar bug

**Comment by Binaryify** [comment]
I think they use same syntactic parser
like this
https://github.com/atom/language-sass/issues/226

**Comment by Voyager-One** [comment]
one day if they fix this kind of bug that will really be a help of my COD : )
