### ISSUE TITLE
How do I change the word highlight border?

### ISSUE THREAD

**Issue by FrozenHearth** [Binaryify/OneDark-Pro#221]
How do I change the word highlight border from dotted to straight in Visual Studio Code? 

**Using Mac High Sierra 10.3** 

Here's what it looks like:

![screen shot 2018-05-16 at 1 56 28 pm](https://user-images.githubusercontent.com/27160715/40105647-371cbe76-5911-11e8-9693-36611ad7787c.png)

**Comment by Binaryify** [comment]
here is docs https://binaryify.github.io/OneDark-Pro/#/ , sorry for reply late
