### ISSUE TITLE
FlowType support

### ISSUE THREAD

**Issue by wilomgfx** [Binaryify/OneDark-Pro#222]
Hi, when using flow types, i dont get any syntax highlighting.

![image](https://user-images.githubusercontent.com/6611491/40510137-bbdd3a56-5f69-11e8-8241-224b73219394.png)

I guess it should be the same highlighting as `TypeScript` (like below)
![image](https://user-images.githubusercontent.com/6611491/40510186-dd0754c8-5f69-11e8-9575-57c6f5c82a48.png)

**Comment by wilomgfx** [comment]
@Binaryify  :D

**Comment by nextbook** [comment]
Hi @wilomgfx, here is how you could solve this issue!

- Google [vscode syntax highlighting](https://duckduckgo.com/?q=vscode+syntax+highlighting&t=osx&ia=qa)
- Click the first result that leads to [the official VSCode documentation](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers). Here they explain how you can find the TextMate `scope` of a certain part of the language syntax to apply your own formatting
- Select `HTMLButtonElement` in your snippet above and press `Cmd` + `Shift` + `P`, and then type "Inspect TM Scopes"
- Take note of the string `support.type.class.flowtype`
- If you’re using macOS, open the built-in *Digital Color Meter* to grab the desired hexadecimal color code from the One Dark style in Atom (it should be near `#57b6c2`).
- Add the following to your VSCode configuration file:
  ```
  "editor.tokenColorCustomizations": {
     "textMateRules": [
       {
         "name": "flow types",
         "scope": "support.type.class.flowtype",
         "settings": {
           "foreground": "#57b6c2"
         }
       }
     ]
   }
  ```
- Repeat this process for other parts of the Flow syntax. You should arrive at something like this (first entry added as a bonus):
  ```
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "js/ts support.class.component",
        "scope": "support.class.component",
        "settings": {
          "foreground": "#e5c07b"
        }
      },
      {
        "name": "flow types",
        "scope": "support.type.class.flowtype",
        "settings": {
          "foreground": "#57B6C2"
        }
      },
      {
        "name": "flow type primitive",
        "scope": "support.type.builtin.primitive.flowtype",
        "settings": {
          "foreground": "#51B6C2"
        }
      },
      {
        "name": "flow type maybe",
        "scope": "keyword.operator.maybe.flowtype",
        "settings": {
          "foreground": "#51B6C2"
        }
      }
    ]
  }
  ```

Have a great day!
