### ISSUE TITLE
Bug in js view

### ISSUE THREAD

**Issue by justerest** [Binaryify/OneDark-Pro#224]
![default](https://user-images.githubusercontent.com/24754883/40587576-75101b56-61ea-11e8-809e-86bb0009631d.png)
![default](https://user-images.githubusercontent.com/24754883/40587583-8dda525a-61ea-11e8-943f-2b918a521687.png)

**Comment by jens1o** [comment]
I'm sorry but what do you mean exactly?

**Comment by justerest** [comment]
sorry. no problem now. but syntax higlight is faild on the first picture.

**Comment by justerest** [comment]
var `resultMessage` is blue like function. but is just var.
