### ISSUE TITLE
Improving the visibility of the overview ruler 

### ISSUE THREAD

**Issue by Or3stis** [Binaryify/OneDark-Pro#226]
The current color for information blocks on the overview ruler is hard to see.
<img width="38" alt="screen shot 2018-06-01 at 21 39 38" src="https://user-images.githubusercontent.com/11923550/40862425-64495e92-65e4-11e8-873e-17769214a68b.png">

This is a somewhat of an edge case. It is quite relevant if you use the [spell check](https://github.com/Jason-Rev/vscode-spell-checker) extension to highlight misspellings. 

This is my suggestion to increase the contrast. The color is `#4f7098`. It is a more pastel version of Atom's blue (`#61AFEF`), so it won't clash with the rest of the color theme.
<img width="36" alt="screen shot 2018-06-01 at 21 39 27" src="https://user-images.githubusercontent.com/11923550/40862435-6c1faa4a-65e4-11e8-8186-85dc6bb49678.png">

**Comment by beastdestroyer** [comment]
+1 for this @Binaryify
