### ISSUE TITLE
The activity bar and the sidebar have the same color

### ISSUE THREAD

**Issue by hawkgs** [Binaryify/OneDark-Pro#231]
The change is noticeable only with **One Dark Pro**. The new color (`#21252B`) of the activity bar matches with the one of the sidebar making the containers of these two indistinguishable. I believe this is a bug.

Commit: https://github.com/Binaryify/OneDark-Pro/commit/566f638c2661648ecdd7a1d1843d56e62a5e2750

**Comment by bdougherty** [comment]
Luckily there is a setting to override the theme colors. I added this to bring back the previous activity bar color:

```json
"workbench.colorCustomizations": {
    "activityBar.background": "#2f333d"
}
```

**Comment by hawkgs** [comment]
Indeed, I am using the same. But I consider this a workaround since I have to change my workspace settings every time I switch to a light theme when I am outside, for example.

**Comment by hawkgs** [comment]
Apparently, this was an intentional change and those who dislike it (like me) should change the color from the settings. Closing.

@Binaryify the second screenshot in [the markteplace](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) still uses the old color.
