### ISSUE TITLE
Support the new custom titlebar

### ISSUE THREAD

**Issue by guledali** [Binaryify/OneDark-Pro#232]
vscode just released a custom titlebar see https://github.com/Microsoft/vscode/pull/39972
Its right now on insiders @Binaryify I hope this theme will take full advantages of this feature, maybe give us Yosemite icons (titlebar) on windows that will look really good with one dark theme

![screenshot 50](https://user-images.githubusercontent.com/20647282/41587256-0a1d15ca-73af-11e8-8130-6532bd68ab18.png)

**Comment by Binaryify** [comment]
it do support, just need set `"window.titleBarStyle": "custom"`
![image](https://user-images.githubusercontent.com/12221718/41597300-a9be95ea-73ff-11e8-8f99-004db4e886eb.png)

**Comment by guledali** [comment]
Could you add yosemite icons to your theme like this

![40278352-1265254c-5c30-11e8-83fc-835064b10f0e](https://user-images.githubusercontent.com/20647282/41598570-d024cb3e-73d0-11e8-9928-c6d280177a20.gif)

**Comment by Binaryify** [comment]
no, people should can choose the icon theme what they want, but no bind the icon theme in this theme
![image](https://user-images.githubusercontent.com/12221718/41644782-b624cb36-74a1-11e8-84cb-93a1f09eec79.png)

**Comment by guledali** [comment]
@No those are file icon theme, no what I meant are the icons on the titlebar 
![green-maximize-zoom-button-os-x-yosemite](https://user-images.githubusercontent.com/20647282/41649371-b7a386c6-747b-11e8-8af9-98be783d106c.png)

If you could make a custom titlebar that allow yosemite icons instead windows icons which now possible
`"window.titleBarStyle": "custom" ` and will suit your theme better, just a personal taste

**Comment by Binaryify** [comment]
seem like can't change it now

**Comment by guledali** [comment]
Okay thanks anyway
