### ISSUE TITLE
Comments forward slashes are not parallel 

### ISSUE THREAD

**Issue by dnistreanu** [Binaryify/OneDark-Pro#234]
**VS Code:**
```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**OS:**
Windows 10 Pro x64

Small but for me very disturbing thing.  The comment lines are not parallel.

Screenshoot: http://prntscr.com/jyhwge

**Comment by beastdestroyer** [comment]
It seems to be because the comment `//` are in italics, but the actual font is not. Therefore it looks weird as mentioned. In the most recent versions of ODP, it is all italics and looks fixed to me. It could also be dependent on your font too, but that is highly unlikely

**Comment by beastdestroyer** [comment]
@Binaryify Good to close
