### ISSUE TITLE
Workbench Support

### ISSUE THREAD

**Issue by benbrownlol** [Binaryify/OneDark-Pro#24]
With the release of 1.11, more of the editor is now styleable allowing for a more cohesive theme.

https://code.visualstudio.com/updates/v1_11#_preview-workbench-theming

**Comment by Binaryify** [comment]
>There are still several gaps and we have not finalized the new theme file format. For that reason, there's no documentation and we ask theme authors to not use the new theme format yet.

I will support it, but not this VS Code  version

**Comment by Binaryify** [comment]
@benbrownlol 
You can add this snippet in your "settings.json" file   
```json
"workbench.experimental.colorCustomizations":{
  "activeTabBackground": "#282c34",
  "activityBarBackground":"#282c34",
  "editorGroupBackground": "#282c34",
  "sideBarBackground": "#282c34"
}
```

**Comment by Zueuk** [comment]
Putting the same color everywhere makes it look too flat.
I'd adjust them slightly, for example:
```
    "workbench.experimental.colorCustomizations":{
        "activeTabBackground": "#282c34",
        "inactiveTabBackground": "#2D2F33",
        "tabsContainerBackground": "#21242B",
        "activityBarBackground":"#2D313A",
        "editorGroupBackground": "#282c34",
        "sideBarBackground": "#21242B"
    }
```

**Comment by jtheoof** [comment]
Any CSS tweak for the status bar below? I'd love to get rid of that blue.

![screen shot 2017-04-20 at 11 24 52 am](https://cloud.githubusercontent.com/assets/90020/25238683/123f5976-25bc-11e7-8a79-ef614f3e8340.png)

**Comment by Binaryify** [comment]
@jtheoof 
You just add 
```
"statusBarBackground": "Your favorite color"
```
in 
```
"workbench.experimental.colorCustomizations":{
  ...
}
```

**Comment by jtheoof** [comment]
FYI: The naming has changed in a recent commit: https://github.com/Microsoft/vscode/issues/25428 This will probably hit `vscode` in 1.11.3

**Comment by Binaryify** [comment]
I support it !

**Comment by jens1o** [comment]
May it possible that the file explorer have a slightly darker background? I wish there were some contrast...

**Comment by Binaryify** [comment]
@jens1o 
You can DIY it

**Comment by jens1o** [comment]
Yeah, I know. But I don't how how much darker it needs to be. I think you have a color which is X% darker, since you are the designer?

**Comment by Binaryify** [comment]
@jens1o 
No, I am a front-end engineer

**Comment by Zueuk** [comment]
@jens1o check this: #45

**Comment by jens1o** [comment]
Thank you!
