### ISSUE TITLE
Static class variable PHP

### ISSUE THREAD

**Issue by ghost** [Binaryify/OneDark-Pro#240]
Up to commit d3a6fdac801313dc7c940594d963c3fc68029181, PHP static class variables were the same color as the dollar sign (reddish) rather than classes (yellowish).

However this is the current behavior: 
![ntdp8qa 1](https://user-images.githubusercontent.com/6422013/42658540-a142e88e-85f3-11e8-9181-e6277fe474ab.png)

This is the previous behavior:  
![o15d4rq 1](https://user-images.githubusercontent.com/6422013/42658559-ad93c054-85f3-11e8-81e0-18c6e8bf6099.png)

This seem to be caused by the reclassification of variable.other.class. It's unclear to me if it was an intended change, but it looks like it may be a bug?

Thanks

**Comment by beastdestroyer** [comment]
Ah yes it is a bug, that change was mainly intended for JS/TS to unify the colouring, since there are many similarities. I seem to have forgotten to add .js and .ts. I also acknowledge that my changes have affected other languages, and I will uodate with a pull request soon, thanks!

**Comment by beastdestroyer** [comment]
@mikolino An update on this issue, it seems PHP Intellisense and syntax highlighting is kinda broken, it doesn't wprk, do you think you could open a pull request and edit the files instead?

Thanks and sorry, trying to fix this issue is annoying lol

Thx and have a great day!

**Comment by Binaryify** [comment]
I just fix it, please update and check it, thank for your feedback
