### ISSUE TITLE
Python: inconsistent "white" in parentheses

### ISSUE THREAD

**Issue by madig** [Binaryify/OneDark-Pro#241]
Compare the text color of the variable assignments to e.g. "glyph" in the comprehension:

![image](https://user-images.githubusercontent.com/380829/42766399-4b023bec-8912-11e8-9a43-12b5d79c8bb7.png)

**Comment by beastdestroyer** [comment]
@madig I've essentially copied your example, and studied the internal theme code for Python, unfortunately, VSCode's themes doesn't correctly highlight it, but you could edit it yourself or install extensions (listed below) 

This is common in VSCode, but there should be some Python related extensions,
I've linked some stuff, hopefully should be helpful:

Python Highlighter:
https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython

Python Extension by Microsoft:
https://marketplace.visualstudio.com/items?itemName=ms-python.python

To conclude, objects to edit Python (and some other languages too) are currently just not coloured, you can check this by pressing F1, then type in : 'Developer: Inspect TM Scopes', and click around your code, you'll see the same colour (especially in default theme) 

Hope it helps!

**Comment by madig** [comment]
I already use Microsoft's Python extension, it's what you see above. So... does this need correction in the extension?

**Comment by Binaryify** [comment]
@madig 
the bad news is that is vscode itself problem

**Comment by beastdestroyer** [comment]
@madig Based off what @Binaryify said, it seems the scopes defined in the Python extension aren't reaching everywhere. As such yes, you could probably open an issue to the extension requesting more variable highlighting, so that way ODP would be able to highlight correctly. VSCode doesn't define these scopes by itself either.
