### ISSUE TITLE
help comments are bold!!!

### ISSUE THREAD

**Issue by PhoenixNil** [Binaryify/OneDark-Pro#242]
Hello, developer, I hope that you can change the C/C++ comment to bold instead of italic, because under Windows, the Chinese italic display is too ugly, can you change it back? :)

**Comment by beastdestroyer** [comment]
@PhoenixNil Hey there, it is most likepy something due to my pull request, I am. working on a bunch of fixes, is it possible you coupd send me a screenshot, and I'll see if I can fix anything (note, I am not the official dev as you can tell just noting that I may have broken a bunch of stuff when they merged my pull)

Thanks!

**Comment by PhoenixNil** [comment]
![default](https://user-images.githubusercontent.com/33974040/43018278-bf645548-8c8b-11e8-9a68-7b577c180f86.PNG)

I hope they become bold rather than italic ；（ ，italic is very ugly

**Comment by beastdestroyer** [comment]
Yes I do agree with you, unfortunately it seems we can't do character specific changes, ie right now it isn't possible to fix it just for Chinese characters, even if we did just change it overall, many people may or may not like it, and we've yet to get feedback so we'll see how it goes, thanks for some screenshots though, will experiment!

**Comment by Binaryify** [comment]
I just change it @PhoenixNil @beastdestroyer

**Comment by rossnichols** [comment]
@Binaryify, bold doesn't look that great, and also the change doesn't affect /* */ style comments either - those are still italic. If you're moving away from italic (which I'd be sad about, I like the italic), can you at least not make it bold? Just make it gray.

Can themes have settings? Ideally this could just be customized.

**Comment by Binaryify** [comment]
@rossnichols 
here is the docs 
https://binaryify.github.io/OneDark-Pro/#/

**Comment by beastdestroyer** [comment]
@rossnichols It will, you can submit your changes as a pull request or wait until @Binaryify has done it himself (if he chooses to do so)

**Comment by beastdestroyer** [comment]
Crap Im stupid, I have never used that so I completely forgot about that... Ops :>

**Comment by beastdestroyer** [comment]
Also @Binaryify Im going to open an issue on this, but units (px, em, rem etc.) aren't red

**Comment by rossnichols** [comment]
@Binaryify, thanks, I added this to revert the change:

    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "comment.line.double-slash.c,comment.block.documentation.c,comment.line.double-slash.cpp,comment.block.documentation.cpp",
                "settings": {
                    "fontStyle": "italic"
                }
        ]
    }

But couldn't you have just recommended to @PhoenixNil to do this in the first place? Comments have been italic in this theme since I started using it months ago.

**Comment by Binaryify** [comment]
@rossnichols you are right

**Comment by Binaryify** [comment]
@PhoenixNil 
I just change it back to make comments more unified 
you need add this snippet into your settings now
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "scope": "comment.line.double-slash.c,comment.block.documentation.c,comment.line.double-slash.cpp,comment.block.documentation.cpp",
            "settings": {
                "fontStyle": "bold"
            }
    ]
}
```

**Comment by Stone-Zeng** [comment]
I want to mention that, some Chinese fonts, e.g. [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic), are specially designed for programming and thus have italic shape. Hope you may enjoy it.
