### ISSUE TITLE
On HTML tags, "<" is not red along with the rest of the tag. 

### ISSUE THREAD

**Issue by kyiami** [Binaryify/OneDark-Pro#243]
This seems like an issue, although I guess it could be intentional. 

[Image](https://i.imgur.com/b4BjJSk.png)

This would include things like <!, </, <, >, and all the rest.

**Comment by jens1o** [comment]
That's intentional.

cc @Binaryify

**Comment by Binaryify** [comment]
both all editor look like this, that's not bug
