### ISSUE TITLE
Bug in snake case named jsx attributes

### ISSUE THREAD

**Issue by lerran80** [Binaryify/OneDark-Pro#246]
One Dark Pro Version: 2.15.4
VSCode version: 1.26.0

JSX attributes with underscore in the name get colored white:
![image](https://user-images.githubusercontent.com/22422447/44270792-dadda200-a20e-11e8-8ef4-f7e80bc6b44f.png)

**Comment by beastdestroyer** [comment]
@lerran80 Whilst making my pull request, it seems underscored attributes aren't allowed. This is also equivalent to HTML behaviour, underscored attributes are illegal! Use dashes instead

**Comment by beastdestroyer** [comment]
@Binaryify My solution fixes it, feel free to close!

**Comment by lerran80** [comment]
@beastdestroyer I never saw any indication in the React docs that snake case attributes in JSX components are illegal. Our code base has 20k+ lines and we use it everywhere. Changing to dashes is not an option. The strange thing is that this worked before with One Dark Pro theme.

**Comment by beastdestroyer** [comment]
@lerran80 Also, try downgrading to VSCode 1.25 too, if it works completely fine, it might be worthwile to file and issue at [VSCode Issues](https://github.com/Microsoft/vscode/issues) as it is then related to the internals of how it deals with JSX rather than One Dark Pro's fault

**Comment by lerran80** [comment]
Interesting. I am using VSCode 1.26.1, with ESLint v1.5.0 and no errors are raised.

**Comment by beastdestroyer** [comment]
Well I am using 1.27.0-insiders and with or without ESLint it gives the error, also happens with underscored component names too, these issues seem highly likely related to VSCode itself, try posting an issue in their repo (if you haven't already) and just show them screenshots etc.

**Comment by lerran80** [comment]
It looks like they already fixed it in a new insiders version: https://github.com/Microsoft/TypeScript-TmLanguage/issues/648

**Comment by beastdestroyer** [comment]
Yup, I can confirm that it is fixed, I use Insiders on a daily basis, tested both your issues and they are fixed! Just wait a week or 2 for the update (or switch to Insiders, it ain't that bad 😛 ) and you'll be a happy guy again :)

**Comment by lerran80** [comment]
Cool!! Thanks for the follow-up and for all your work in this theme. I really appreciate it!
