### ISSUE TITLE
Bug in snake case jsx component with template strings in attributes

### ISSUE THREAD

**Issue by lerran80** [Binaryify/OneDark-Pro#247]
One Dark Pro Version: 2.15.4
VSCode version: 1.26.0
It makes everything green after the last backtick:
![image](https://user-images.githubusercontent.com/22422447/44287592-bfd95500-a243-11e8-9254-82ff9de39b9a.png)

**Comment by beastdestroyer** [comment]
@lerran80 Again, related to issue #246 , Underscores aren't allowed. This is the same in HTML etc. Stick to dashes!

**Comment by beastdestroyer** [comment]
@Binaryify My solution fixes it, feel free to close!
