### ISSUE TITLE
[Question] Similar shades of colors

### ISSUE THREAD

**Issue by LukasPolak** [Binaryify/OneDark-Pro#248]
Hi @Binaryify, thanks for the awesome theme! 
I have a question about the usage of similar shades of colors, they are almost identical, hardly recognizable at least for me. I'm also attaching an exported color palette without transparent colors. It is a good idea to simplify them and colors that are almost the same merge?
Thanks for your answer.
![color-pallete](https://user-images.githubusercontent.com/17145302/44299753-50736c00-a2fc-11e8-9e1f-d5af01998011.png)

**Comment by beastdestroyer** [comment]
Definitely, especially with Settings GUI, some colours are just too similar and cause accessibility issues. I am thinking of opening a pull request to help with it and some other issues, I woupd definitely like it if you have any areas where you think colours should change!

**Comment by Or3stis** [comment]
We should start on the easy ones and see how the UI improves. I can make a pull request to merge the following colors (pretty similar) and use Atom's One dark color palette as a reference for the prevailing color.

From what I have seen the colors Cyan, Purple, Green are only used in the text editor area for syntax highlighting so the overall UI will not be affected.

![44299753-50736c00-a2fc-11e8-9e1f-d5af01998011](https://user-images.githubusercontent.com/11923550/46414238-59dd5a00-c72b-11e8-8607-e2e9386cbff5.png)

**Comment by Binaryify** [comment]
new version just publish ~
