### ISSUE TITLE
Possible Merging?

### ISSUE THREAD

**Issue by beastdestroyer** [Binaryify/OneDark-Pro#250]
This is just a mini-discussion/question, as you know ODP has 2 themes, ODP and its Vivid sister, however whilst working through my pull of #249, I have found many inconsistencies. Eventually I wish to submit another pull which will be a complete rewrite of the files for the following reasons:
- Easier to maintain and update over time
- There is currently too much overriding and clutter
- Quite big file size (if that matters, but it can definitely be smaller!)

Following the inconsistencies, I've found that styles that may work in one theme but not the other. This creates headaches for people submitting pulls to improve ODP as they have to search and search and test more than necessary, just because of all this overriding. Furthermore, as mentioned by #248 , the colours between both themes are quite similar, one's just a lighter and slightly more contrast-y version of the other, scrapping or merging into one wouldn't make a big deal on the colours, just mix and match right?

Also, it's hard to tell which one is more "popular" if you could put it that way, as the common user won't really notice the varying, subtle shades of colour until they squint or something (me when I first started using this theme). Additionally, Atom (which of course is where this port comes from) only has 1 One Dark theme, not 2 like showcased here, and again, users of Atom migrating to VSCode using this theme probably won't notice the colour change.

Moving on to accessibility, the versions aren't really THAT different either. Someone with more colour deficiencies might see the themes as exactly the same, or some colours may look odd overall. Since the versions don't make a difference in that sense, it would be logical to scrap/merge them together

It is for these reasons I am raising this issue. I do not see this as a definite request, but a discussion to see what you think. Thanks for reading.
@jens1o @Binaryify 

> P.S: #249 is going well :)

**Comment by Binaryify** [comment]
great~
I'm considering if I needed to separate the editor configuration from the syntax highlighting configuration, and then use the tool to combine them into two theme files

**Comment by beastdestroyer** [comment]
@Binaryify Similar to like an "original" file (the one which would come installed with the extension) and then a custom one which people can configure? If you're talking about that, that would be COOL! Power users similar to me would definitely like that feature, especially if we want to contribute, it makes developing easier :)

**Comment by Binaryify** [comment]
@beastdestroyer 
nope, I mean merge when publish theme, but your idea is good too, I will try

**Comment by beastdestroyer** [comment]
Coolio!
