### ISSUE TITLE
Markdown: So much green!

### ISSUE THREAD

**Issue by Splike** [Binaryify/OneDark-Pro#251]
Version 2.16.0 makes all text in a list, green. It's just too much.

Most people who write markdown in vs code will most likely also be using the plugin "Mardown All In One", which uses the same green color for `code snippets`.

I'd like to ask you to please revert the color changes you've made to markdown lists, as it's not pretty with all that green and it clashes with the most popular markdown extension.

Furthermore, it's enough to just color the bullet in lists and not all the text, as "Mardown All In One" does.
I take notes in markdown and use a lot of lists, which makes it all green.

**Comment by Binaryify** [comment]
@beastdestroyer

**Comment by beastdestroyer** [comment]
@Splike Thanka for that! 
@Binaryify I believe this is caused by these lines:
```
   {
      "name": "[VSCODE-CUSTOM] Markdown Lists",
      "scope": [
        "markup.list.unnumbered.markdown",
        "markup.list.numbered.markdown"
      ],
      "settings": {
        "foreground": "#98c379"
      }
    }
```
Since my keyboard is currently dead, I have no real way of correcting this, I believe deleting this should fix the problem

**Comment by Binaryify** [comment]
I just fix it, you could update and check if it fine

**Comment by beastdestroyer** [comment]
Note: Just finished a deep clean of my keyboard and it seems to be working, will fix!

**Comment by beastdestroyer** [comment]
@Binaryify Fixed!

**Comment by Splike** [comment]
Thanks so much guys! Much appreciated 😃
