### ISSUE TITLE
2.16.5 Broke Pull #253

### ISSUE THREAD

**Issue by beastdestroyer** [Binaryify/OneDark-Pro#254]
#253 Was my pull in which I edited a colour of the tab background to be #282c34 (from my memory at least), the update to address #252 has destroyed this change. @Binaryify

**Comment by Binaryify** [comment]
my bad, also can't edit the files on 'thems/' now, need edit 'src/xx.json' then run `npm run build`

**Comment by beastdestroyer** [comment]
Oh that's fine, it's a minor thing that can get fixed with a few types, you should probably also update docs too with how to contribute, now you need to do what you just said instead.

**Comment by Binaryify** [comment]
I'll update it soon~
