### ISSUE TITLE
python render partial italic

### ISSUE THREAD

**Issue by raytroop** [Binaryify/OneDark-Pro#257]
![image](https://user-images.githubusercontent.com/31182666/45592981-2326e600-b9ae-11e8-95ec-0f8e83ea6d86.png)

as you can see,  `for in` clause is not font consistent that `for` italic and `in` is normal.
at a word,  what i need is normal font everywhere except comment. 

Any suggestion?
Thanks

extension version: 2.16.5
vscode version: 1.27.2
OS: Ubuntu 16.04.5 LTS / Ubuntu 18.04.1 LTS

**Comment by beastdestroyer** [comment]
@raytroop This was a change that @Binaryify done for issuw #252. 

@Binaryify It's clear people really like italics. Continuing on from #250, from merging ODP and Vivid, perhaps create an italicised version too?

**Comment by raytroop** [comment]
Thanks
@beastdestroyer but I DONT like italics, maybe I belong to the minority
I indeed like previous version.

**Comment by Binaryify** [comment]
@raytroop 
you can custom theme
check the docs 
https://binaryify.github.io/OneDark-Pro/#/?id=user-definable-syntax-highlighting-colors

**Comment by raytroop** [comment]
I see, thanks @Binaryify

**Comment by raytroop** [comment]
work like a charm @Binaryify @beastdestroyer 
```
{
      "name": "Python Keyword Control",
      "scope": "keyword.control.import.python,keyword.control.flow.python",
      "settings": {
        "fontStyle": "normal"
      }
    }
```

**Comment by beastdestroyer** [comment]
👍

**Comment by stevencollinscn** [comment]
@Binaryify I'm trying to apply the code posted by @raytroop, but I couldn't find the syntax.json in my vs code files founder as mentioned in the [doc](https://binaryify.github.io/OneDark-Pro/#/?id=user-definable-syntax-highlighting-colors). Is there any other way to change everything to non-italic?

**Comment by markypython** [comment]
@stevencollinscn The link to that section of the docs doesn't seem to work right.  If you scroll almost to the bottom of the page you will see a section named **User definable syntax highlighting colors** which explains how to add the overrides.

**Comment by stevencollinscn** [comment]
Doesn't seems working. I already have a setting for `comment`. Am I missing something since I'm not really familiar with json files.

**Comment by markypython** [comment]
@stevencollinscn Can you post the relevant portion of your `settings.json` file containing your change?

**Comment by stevencollinscn** [comment]
Doesn't seems working. I already have a setting for `comment`. Am I missing something since I'm not really familiar with json files.
![image](https://user-images.githubusercontent.com/33796896/51421800-21467c80-1b72-11e9-91fe-238760fe229d.png)

**Comment by markypython** [comment]
@stevencollinscn Ah, I see the problem.  Because this theme applies italics to multiple comment related scopes, the scope of `comment` isn't specific enough.  Try adding the code below and see if that works.

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Comments",
        "scope": [
          "comment",
          "punctuation.definition.comment",
          "comment.line.double-slash",
          "comment.block.documentation"
        ],
        "settings": {
          "fontStyle": "",
        }
      }
    ]
  }```

**Comment by markypython** [comment]
@stevencollinscn Gotcha.  What you can do is find a keyword that you don't want italicized, place your cursor on the keyword, open the command palette, and type **Developer: Inspect TM Scopes**.  This will show you the scopes that are in play for that keyword which you can then check against the syntax.json file in this repo to determine which scopes need to be overridden to get your styles to apply.

**Comment by stevencollinscn** [comment]
@markypython I finally found the syntax.js and changed it to the following, 
![image](https://user-images.githubusercontent.com/33796896/51429196-51296a80-1bda-11e9-9ac4-80288e9f8ac3.png)
but nothing seems changed. 
![image](https://user-images.githubusercontent.com/33796896/51429204-630b0d80-1bda-11e9-9e9f-886ff2b50f8f.png)

**Comment by markypython** [comment]
@stevencollinscn You don't change the syntax.json file.  You need to change the settings in your settings.json file using the information from syntax.json.

From your screenshot the code would be as follows:

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Comments",
      "scope": [
        "keyword.control.import.python"
        "keyword.control.flow.python"
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
}
```

**Comment by Binaryify** [comment]
@stevencollinscn 
syntax.js is the file before compilation, you need run `npm run build` or  change `/themes/OneDark-Pro.json`
or just change settings.json like @markypython  show

**Comment by stevencollinscn** [comment]
@markypython thanks, man. it is finally working!
Is there any way to nest those two, btw:
```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "Python Keyword Control",
                "scope": [
                    "keyword.control.import.python"
                    "keyword.control.flow.python"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    }
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "name": "Comments",
                "scope": [
                    "comment",
                    "punctuation.definition.comment",
                    "comment.line.double-slash",
                    "comment.block.documentation"
                ],
                "settings": {
                     "fontStyle": ""
                }
            }
        ]
    }
```

@Binaryify should've read your docs; the folder is somehow named "marital theme" or something, which really confused me.

**Comment by markypython** [comment]
@stevencollinscn Just merge the scopes like this.

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Non italic",
      "scope": [
        "comment",
        "punctuation.definition.comment",
        "comment.line.double-slash",
        "comment.block.documentation",
        "keyword.control.import.python",
        "keyword.control.flow.python"
      ],
      "settings": {
        "fontStyle": ""
      }
    }
  ]
}
```

**Comment by Binaryify** [comment]
@stevencollinscn 
yes, that's a historical reason and I can't change it because it will lose downloads

**Comment by stevencollinscn** [comment]
@markypython Thanks a lot man...This definitely more "pythonic" to read. Lol...

@Binaryify I see.. That makes sense. I really enjoy this theme as missing Atom and thanks for your work. Btw, I also apply One Dark Bold, it doesn't seem changed anything. Is it design for some other language than Python?

I'm actually curious why many themes now are adapting italics. Is there any design or technical reason? Easy to read? More productive?
