### ISSUE TITLE
Inconsitency of Ruby symbol

### ISSUE THREAD

**Issue by foreverqihe** [Binaryify/OneDark-Pro#258]
Atom: ![image](https://user-images.githubusercontent.com/2378002/45914173-7ef8df80-be84-11e8-9a6d-a637f147a6ca.png)

OneDark Pro: 
![image](https://user-images.githubusercontent.com/2378002/45914217-2d048980-be85-11e8-90ba-e4e985446cb8.png)

**Comment by beastdestroyer** [comment]
@Binaryify

**Comment by Binaryify** [comment]
will improve it on next version

**Comment by foreverqihe** [comment]
Thank you for updating @Binaryify .

 Btw, there is another form of symbol in Ruby which is still inconsistent:
Atom:![image](https://user-images.githubusercontent.com/2378002/46580640-70115000-ca74-11e8-8ace-434a6899a72f.png)

One Dark Pro:
![image](https://user-images.githubusercontent.com/2378002/46580647-90410f00-ca74-11e8-8f57-4f000a69e5fc.png)
