### ISSUE TITLE
Not really a issue

### ISSUE THREAD

**Issue by Rohit-Kudatarkar** [Binaryify/OneDark-Pro#259]
Atom one dark version
![image](https://user-images.githubusercontent.com/36111164/45970924-64c22b80-c055-11e8-9375-cabe3ddb4ed0.png)
Your OneDark Pro
![image](https://user-images.githubusercontent.com/36111164/45970964-7a375580-c055-11e8-85a7-00f18aec613e.png)
Well Its kinda Annoying me for a few day but you can pass if you want to

**Comment by Rohit-Kudatarkar** [comment]
Python

**Comment by Binaryify** [comment]
will improve it

**Comment by Rohit-Kudatarkar** [comment]
Thanks

**Comment by Binaryify** [comment]
for vscode's own problem, `result` and `random` have same scope, so can't let `random` have color, or they both become red
![image](https://user-images.githubusercontent.com/12221718/46298947-e7f1fd00-c5d2-11e8-9d93-67d97ec9b06e.png)
![image](https://user-images.githubusercontent.com/12221718/46299047-1a035f00-c5d3-11e8-81ce-2f974b1f2fbe.png)

**Comment by Rohit-Kudatarkar** [comment]
ok np
