### ISSUE TITLE
You've been featured! 🎉

### ISSUE THREAD

**Issue by auchenberg** [Binaryify/OneDark-Pro#261]
Hi there 👋

It's Kenneth from the VS Code team. I'm writing to let you know that your extension have been featured in our marketplace, https://marketplace.visualstudio.com/VSCode, so expect a bump in installs, usage and incoming issues.

Thanks for building this awesome extension for VS Code!

/k

**Comment by Binaryify** [comment]
wow, thanks  😁

**Comment by jens1o** [comment]
Awesome!

**Comment by Crysys777** [comment]
Congrats!
