### ISSUE TITLE
Colour inconsistencies in elixir

### ISSUE THREAD

**Issue by slapers** [Binaryify/OneDark-Pro#262]
I must have pulled in an update and I noticed overall colours inconsistencies in Elixir.
Mainly all modulenames in elixir turned orange instead of the yellow like atom (top screenshot):

![screen shot 2018-10-05 at 12 39 54](https://user-images.githubusercontent.com/1183105/46531018-03dbf400-c89c-11e8-8695-83e9041b85a6.png)

sample code:

```elixir
defmodule BTNodeTest do
  @moduledoc false

  use ExUnit.Case
  doctest BTNode

  test "node returns a node" do
    BTNode.select([1])
    BTNode.select([2])

    assert 1 == 1
  end
end
```

**Comment by Binaryify** [comment]
I just improve it and release a new version, you can update now and check if it right

**Comment by slapers** [comment]
Hi,
I saw your change, awesome that you did this so quick :-) 
I did notice that the original colour for modules and unknown consts was chalky, so i quickly changed them. Looking at the code with these changes it looks pretty much the same as the original colours i was used to :-)

![screen shot 2018-10-05 at 16 13 51](https://user-images.githubusercontent.com/1183105/46540449-afe00800-c8b9-11e8-8ac4-3cd99016a2bd.png)

**Comment by Binaryify** [comment]
thanks for your feedback   😁
