### ISSUE TITLE
php bug

### ISSUE THREAD

**Issue by jens1o** [Binaryify/OneDark-Pro#27]
![image](https://cloud.githubusercontent.com/assets/11234139/24835521/ae6862e0-1d04-11e7-85b9-14663d7d000a.png)
I expect that `'desktop'` is colored green.

Code:
```php
<?php
new class {
     public static function getUserByLogin(string $userName, string $password, string $app = 'desktop') {
        $request = null;
        try {
            $request = RequestUtil::doRequest(HttpMethod::POST, '/auth/login', [
                'json' => [
                    'login' => $userName,
                    'pass' => $password,
                    'app' => $app
                ]
            ]);
        } catch(HitboxApiException $e) {
            throw new HitboxAuthException('Cannot authenticate with hitbox api! Check username or password.', 0, $e);
        }
    }
}
```

**Comment by Binaryify** [comment]
I think it was a illegal syntax, and it's background color  should be red.
![image](https://cloud.githubusercontent.com/assets/12221718/24836139/6e7d44e2-1d46-11e7-9342-5b9bc4c309e8.png)

Like this
![image](https://cloud.githubusercontent.com/assets/12221718/24836127/3ed0165c-1d46-11e7-8b9c-fe52ce85f421.png)

**Comment by jens1o** [comment]
Well, it's not. That's a new feature introduced in newer versions of php.

**Comment by jens1o** [comment]
Yes, it was a failure. I was in the wrong language.

**Comment by Binaryify** [comment]
Should I update it? 😂

**Comment by jens1o** [comment]
Yeah, please. So it won't irritate me again.

**Comment by Binaryify** [comment]
@jens1o 
Please update and check it

**Comment by jens1o** [comment]
No, that doesn't fix it:

![image](https://cloud.githubusercontent.com/assets/11234139/24836376/a326d496-1d1a-11e7-94a0-9e7b709a8d26.png)
Now it's looking normal, while I expect red background.

**Comment by Binaryify** [comment]
@jens1o 
Oh, I misunderstand your mean

**Comment by Binaryify** [comment]
@jens1o 
VS Code can't change the code background color, so I can't make it's background be red
This screenshot is atom's
![image](https://cloud.githubusercontent.com/assets/12221718/24836459/dfe3b0e6-1d4e-11e7-83b2-ca1b1f5dee78.png)

**Comment by jens1o** [comment]
Okey. Is there any other way?

Do we need the white thing? Maybe make it red?(But I'm not a designer)

**Comment by Binaryify** [comment]
@jens1o 
 I change it pure red color

**Comment by jens1o** [comment]
![image](https://cloud.githubusercontent.com/assets/11234139/24836686/67f67360-1d22-11e7-9828-e1d54bf688e5.png)
Works. Thanks!

**Comment by jens1o** [comment]
I'm pulling this up. From PHP 7 on, this **is** valid syntax. That's why there is an additional class added:
![image](https://cloud.githubusercontent.com/assets/11234139/24968786/afb5486e-1fae-11e7-918a-238afda2a3e6.png)

**Comment by Binaryify** [comment]
@jens1o 
We should wait until VS Code official support it

**Comment by jens1o** [comment]
Okay, where is the grammar repo?

**Comment by Binaryify** [comment]
@jens1o 
I think here it is
[https://github.com/Microsoft/vscode/tree/master/src/vs/workbench/services/themes](https://github.com/Microsoft/vscode/tree/master/src/vs/workbench/services/themes)

**Comment by su348628753** [comment]
@jens1o can you tell me the font name of your php file, its looked nice😲

**Comment by jens1o** [comment]
No problem, it's the free `Fira Mono` from Mozilla! https://github.com/mozilla/Fira

**Comment by su348628753** [comment]
@jens1o thx for your detailed answer,its kind of u.😜

**Comment by jens1o** [comment]
The problem has been fixed, the php grammar has been updated. Anyway, @Binaryify could you consider publishing a new version?

**Comment by Binaryify** [comment]
@jens1o 
Oh~, I forgot it
