### ISSUE TITLE
How to use it in highlight.js

### ISSUE THREAD

**Issue by CatchLife** [Binaryify/OneDark-Pro#272]
This highlight is so beautiful, I want to show this highlight on the web,but there is no highlight theme.

**Comment by beastdestroyer** [comment]
Could you provide  more information, like what is highlight.js, code screenshots and what do you mean in more detail?

**Comment by CatchLife** [comment]
https://github.com/highlightjs/highlight.js
https://highlightjs.org/

**Comment by beastdestroyer** [comment]
So from what I can read, `highlight.js` is simply a JavaScript library which allows code highlighting on a web page. However, it is simple plain JavaScript which is already highlighted. VSCode currently doesn't show detection of languages between `code` tags and currently there are no plans to.

**Comment by woile** [comment]
highlightjs has [css themes](https://github.com/highlightjs/highlight.js/tree/main/src/styles), it would be awesome if this could be converted to highlightjs as well
