### ISSUE TITLE
Prepare for VSCode 1.29 - New Theming options

### ISSUE THREAD

**Issue by beastdestroyer** [Binaryify/OneDark-Pro#273]
From Microsoft/vscode-docs;

Current preliminary changelog for October 2018 (1.29) introduces a feature in which a border is displayed above a dirty file. This has customisations as quoted here:

- `tab.activeModifiedBorder`: Border on the top of modified (dirty) active tabs in an active group.
- `tab.inactiveModifiedBorder`: Border on the top of modified (dirty) inactive tabs in an active group.
- `tab.unfocusedActiveModifiedBorder`: Border on the top of modified (dirty) active tabs in an unfocused group.
- `tab.unfocusedInactiveModifiedBorder`: Border on the top of modified (dirty) inactive tabs in an unfocused group.

Due to improvements made for Debugging, there are also these:
- `editor.stackFrameHighlightBackground`: Background color of the top debug stack frame highlight in the editor. By default this color is yellow.
- `editor.focusedStackFrameHighlightBackground`: Background color of the focused debug stack frame highlight in the editor. By default this color is green.

@Binaryify

**Comment by Binaryify** [comment]
thank for the feedback
