### ISSUE TITLE
How to remove matching word border

### ISSUE THREAD

**Issue by rob-mathieu** [Binaryify/OneDark-Pro#276]
This isn't clear in the docs.

How can I remove the solid 1px border around matching words? 
![screen shot 2018-11-22 at 10 44 22 am](https://user-images.githubusercontent.com/27698728/48912430-9aac4200-ee43-11e8-8ff6-4c7c9a73593a.png)

**Comment by usernamehw** [comment]
Is this `html` or not?

```json
"[html]": {
	"editor.selectionHighlight": false
},
```

**Comment by rob-mathieu** [comment]
That did the trick. Thank You!

**Comment by stevencollinscn** [comment]
I tried to turn off the border. Is there any way to apply it to all language setting? I tried with python: 
``` 
"[python]": {
        "editor.selectionHighlightBorder": false
    }
```
But it doesn't seem working.
