### ISSUE TITLE
Markdown blockquote colored too invisible?

### ISSUE THREAD

**Issue by Huxpro** [Binaryify/OneDark-Pro#277]
Would you consider the blockquotes in markdown is colored too invisible? 
I assume it uses the same color with comments but semantically speaking blockquote is more important and could be colored more like the plain text?

![screen shot 2018-12-05 at 8 49 12 pm](https://user-images.githubusercontent.com/5563315/49555808-44bdac80-f8cf-11e8-8b98-e813a334d1d9.png)

Nice theme, I appreciate your works a lot!

**Comment by Binaryify** [comment]
sorry for fix it late, you can check it now
