### ISSUE TITLE
FR: Add hilight for Python global variables

### ISSUE THREAD

**Issue by gerroon** [Binaryify/OneDark-Pro#281]
Hi

It would be very helpful if you could add highhlighting for the global variables in Python. They have the same color as the local ones.

thanks

**Comment by Binaryify** [comment]
Python high light have some problem in VS Code, still waiting VS Code's team improve it

**Comment by Binaryify** [comment]
you could try new version

**Comment by gerroon** [comment]
thanks!

**Comment by Binaryify** [comment]
I just recover that change because still have some problem , and I also update the docs, if you want custom highlight, you can add this in your setting.json 
```json
"editor.tokenColorCustomizations":{
    "[One Dark Pro]": {
      "textMateRules": [
        {
          "scope":["source.python"],
          "settings": {
            "foreground": "#e06c75"
          }
        }
      ]
    }
}
```
or check the README.MD
