### ISSUE TITLE
Css property name color customization

### ISSUE THREAD

**Issue by Kvek** [Binaryify/OneDark-Pro#285]
Hi,
I am unable to set a custom colour for my css property names. Ideally i'd like to set the property name to one standard colour like blue or green or something.

Could someone point me in the right direction?  Thanks.

![screenshot 2019-02-26 at 13 01 09](https://user-images.githubusercontent.com/8972543/53414486-c56be080-39c6-11e9-9695-14cc9dc74888.png)

![screenshot 2019-02-26 at 13 01 40](https://user-images.githubusercontent.com/8972543/53414475-c13fc300-39c6-11e9-8d63-66402997713f.png)

**Comment by Binaryify** [comment]
you might install Color Highlight extension

**Comment by Binaryify** [comment]
check the docs https://binaryify.github.io/oneDark-Pro/#/
