### ISSUE TITLE
Rust: self is now yellow (used to be red)

### ISSUE THREAD

**Issue by JMS55** [Binaryify/OneDark-Pro#288]

**Comment by jens1o** [comment]
This was intended: https://github.com/Binaryify/OneDark-Pro/pull/287

**Comment by JMS55** [comment]
Oh, imo yellow looks worse, is there a way to set the color manually to be red, outside of forking the theme? Or would you add an option? Up to you on how you want to handle this @Binaryify

**Comment by markypython** [comment]
I would argue that yellow is better as it gives a different color to the special languages variables or keywords making it easier to distinguish between special variables or keywords and traditional variables.

**Comment by JMS55** [comment]
I mean in rust, red isn't used anywhere now.

**Comment by Binaryify** [comment]
It will be set separately in Ruby

**Comment by jens1o** [comment]
For example:

```

impl<'a, 'tcx> LateLintPass<'a, 'tcx> for TypeComplexityPass {
    fn check_fn(
        &mut self,
        cx: &LateContext<'a, 'tcx>,
        _: FnKind<'tcx>,
        decl: &'tcx FnDecl,
        _: &'tcx Body,
        _: Span,
        _: HirId,
    ) {
        self.check_fndecl(cx, decl);
    }

    fn check_struct_field(&mut self, cx: &LateContext<'a, 'tcx>, field: &'tcx hir::StructField) {
        // enum variants are also struct fields now
        self.check_type(cx, &field.ty);
    }

    fn check_item(&mut self, cx: &LateContext<'a, 'tcx>, item: &'tcx Item) {
        match item.node {
            ItemKind::Static(ref ty, _, _) | ItemKind::Const(ref ty, _) => self.check_type(cx, ty),
            // functions, enums, structs, impls and traits are covered
            _ => (),
        }
    }

    fn check_trait_item(&mut self, cx: &LateContext<'a, 'tcx>, item: &'tcx TraitItem) {
        match item.node {
            TraitItemKind::Const(ref ty, _) | TraitItemKind::Type(_, Some(ref ty)) => self.check_type(cx, ty),
            TraitItemKind::Method(MethodSig { ref decl, .. }, TraitMethod::Required(_)) => self.check_fndecl(cx, decl),
            // methods with default impl are covered by check_fn
            _ => (),

        }
    }
```
![screenshot](https://user-images.githubusercontent.com/11234139/54069086-1cd64000-4254-11e9-9c86-9f7b6ce33e27.png)

(taken from https://github.com/rust-lang/rust-clippy/blob/bd6b5a1a36cb7b105bff8c4e2629bf28eca8471e/clippy_lints/src/types.rs#L176-L198)

**Comment by JonGarbayo** [comment]
Hi all!

I'm the author of that #287 pull request.
Sorry for my ignorance about the Rust language, but in the below code (copy-pasted from the above one):

```rust
fn check_item(&mut self, cx: &LateContext<'a, 'tcx>, item: &'tcx Item) {
```

does ``cx`` and ``item`` are variables? If yes, the problem doesn't come from One Dark Pro or any other theme, but from the VS Code Rust syntax definition.

After inspecting their scope with the VS Code "Inspect TM Scopes" tool, it appears they are treated like ``source.rust``; so basically... not recognized as variables :/ If they was, they should be red.

But maybe I didn't understand anything at this Rust code, so please tell me ;)

**Comment by JMS55** [comment]
`cx` and `item` are variables yeah, they're arguments to a function. Are you saying they should have been red all along? I don't know how I feel about that rip

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/54080945-58e1d180-4336-11e9-9b89-158ba50e98ef.png)

@JMS55 @markypython 
Sorry for VSCode's support for Rust is incomplete, so I can't highlight more
![image](https://user-images.githubusercontent.com/12221718/54080953-9e060380-4336-11e9-9dc7-7d5bdd005f65.png)
![image](https://user-images.githubusercontent.com/12221718/54080955-a3fbe480-4336-11e9-960a-88b2a87c2bb6.png)
![image](https://user-images.githubusercontent.com/12221718/54080956-b0803d00-4336-11e9-9b1f-b0c7320a0027.png)

**Comment by JMS55** [comment]
@Binaryify looks good! My only criticism is that `Some` shouldn't be yellow, just leave it as grey. If you think `LateContext`, `TraitItemKind`, and `ItemKind` should be highlighted, definitely go open an issue at https://github.com/rust-lang/rls-vscode/issues

**Comment by Binaryify** [comment]
@JMS55 
I saw the `Some`'s scope is constant, if that right, it should be highlight, have no idea for I don't know Rust syntax
![image](https://user-images.githubusercontent.com/12221718/54094678-a9603a00-43dd-11e9-911c-09bc27f939d5.png)

**Comment by JMS55** [comment]
It's just a std lib type, like Vec, String, or HashMap. It's not that important, shouldn't be highlighted imo @Binaryify

**Comment by Binaryify** [comment]
just publish new version, you can check it now

**Comment by JMS55** [comment]
Looks pretty good, except that macros (functions with ! at the end of the name, such as `println!()`) are the same color as types now. You may want to swap them to blue to match regular functions. You could also swap the turquoise type names for blue, and make functions/macros turquoise. Everything else looks good though, so I'm ready to close once that's fixed. And thanks for all the amazing work on this theme and rust support :D @Binaryify 

![image](https://user-images.githubusercontent.com/47158642/54149418-7aad8800-440c-11e9-8ab2-8d7d7fce23f3.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/54250934-99cd2680-4580-11e9-9aa5-8efe0042b41f.png)
@JMS55 
right?

**Comment by Binaryify** [comment]
@JMS55 
I also change the white color more like Atom's 
![image](https://user-images.githubusercontent.com/12221718/54251431-347a3500-4582-11e9-8483-b26727bdaf34.png)

**Comment by JMS55** [comment]
Looks great!
