### ISSUE TITLE
Python imports and variables turned red?

### ISSUE THREAD

**Issue by plynch-chewy** [Binaryify/OneDark-Pro#291]
Just happened today, not sure when VScode last updated for me. Perhaps related to Feb release?

![image](https://user-images.githubusercontent.com/40441194/54297206-c7b86800-458c-11e9-806e-01cd73a5b29a.png)

**Comment by CrispinLin** [comment]
Same here. I believe it comes with  VSCode Update 1.32.1

**Comment by markypython** [comment]
I think it is related to [this update](https://github.com/Binaryify/OneDark-Pro/commit/17098b8f63c682c23e716a431dba2f45e9b8d3cd).

Based on #61 the maintainer of this repo seems to like the all red look.  I maintain a [fork of this repo](https://github.com/markypython/OneDark-Pro) that removes the red everywhere and also adds italic support for language keywords.  You can check it out if you are interested.

**Comment by CrispinLin** [comment]
> I think it is related to [this update](https://github.com/Binaryify/OneDark-Pro/commit/17098b8f63c682c23e716a431dba2f45e9b8d3cd).
> 
> Based on #61 the maintainer of this repo seems to like the all red look. I maintain a [fork of this repo](https://github.com/markypython/OneDark-Pro) that removes the red everywhere and also adds italic support for language keywords. You can check it out if you are interested.

Thanks @markypython, I'll give it a try!
Mis-blamed VSCode :(

**Comment by plynch-chewy** [comment]
Yeah just saw in the commits that the coral color is now preferred by the maintainer (kinda drastic change, but hey, not my repo). Thanks for the pointers, I don't prefer the italics for keywords, but in #61 the maintainer linked to his docs on how to modify the colors.

**Comment by plynch-chewy** [comment]
BTW, vscode has a way to install previous version (2.20.1):

![image](https://user-images.githubusercontent.com/40441194/54302456-42868080-4597-11e9-8d89-46935e9997ca.png)

**Comment by Binaryify** [comment]
will fix it soon

**Comment by Binaryify** [comment]
sorry for the drastic change
My original intention was to bring python syntax highlighting closer to Atom's, but the VSCode still no support python completely
![image](https://user-images.githubusercontent.com/12221718/54327735-1d9d1680-4646-11e9-961b-c1fc06041702.png)
![image](https://user-images.githubusercontent.com/12221718/54327741-24c42480-4646-11e9-865d-c902ddcd68b2.png)
![image](https://user-images.githubusercontent.com/12221718/54327745-27267e80-4646-11e9-9fb9-edac8fbed860.png)
will change it back in few minutes

**Comment by plynch-chewy** [comment]
No worries, you've done great work with this theme :). Appreciate that you are willing to working on something that is _other people's_ preference for style.

**Comment by Binaryify** [comment]
you guy can update the v2.20.3 to check it now
@plynch-chewy thanks for the understanding
