### ISSUE TITLE
Is new python highlighting correct?

### ISSUE THREAD

**Issue by nmcglohon** [Binaryify/OneDark-Pro#293]
Seems like commit 17098b8f63c682c23e716a431dba2f45e9b8d3cd changed Python syntax highlighting drastically. Is it intended to make the default foreground color of all python code "coral"?

![image](https://user-images.githubusercontent.com/6493858/54322059-10424680-45ca-11e9-813d-d7817341bdbd.png)

**Comment by kylesome** [comment]
+1 , also having this issue

**Comment by Binaryify** [comment]
will fix it soon

**Comment by nmcglohon** [comment]
Thanks! Just wanted to check.

**Comment by kylesome** [comment]
thanks! appreciate the quick response

**Comment by vinlyx** [comment]
Thanks for quick response! Also having this issue after upgrade to 1.32.2.

**Comment by Binaryify** [comment]
sorry for the drastic change
My original intention was to bring python syntax highlighting closer to Atom's, but the VSCode still no support python completely
![image](https://user-images.githubusercontent.com/12221718/54327735-1d9d1680-4646-11e9-961b-c1fc06041702.png)
![image](https://user-images.githubusercontent.com/12221718/54327741-24c42480-4646-11e9-865d-c902ddcd68b2.png)
![image](https://user-images.githubusercontent.com/12221718/54327745-27267e80-4646-11e9-9fb9-edac8fbed860.png)
will change it back in few minutes

**Comment by Binaryify** [comment]
you can update the v2.20.3 to check it now

**Comment by evanheckert** [comment]
I'm still getting a ton of red on 2.20.3, everywhere where there was normally the standard light grey.

**Comment by Binaryify** [comment]
@evanheckert you might need reload vscode

**Comment by iddan** [comment]
It's gorgeous!
 - I think this is still highlighted incorrectly:
<img width="428" alt="Screenshot 2019-03-14 at 9 59 26" src="https://user-images.githubusercontent.com/12671072/54340382-e88dc580-463f-11e9-8926-df09aec93187.png">
 - What about Highlighting capital started variables and calls in yellow? 
Thank you so much!

**Comment by Binaryify** [comment]
@iddan 
yes, still have some problem, will fix that again, but can't highlight more, cause's VSCode doesn't support python completely, so many scope are same
