### ISSUE TITLE
Suggestion as Medical Student

### ISSUE THREAD

**Issue by Riajyuu** [Binaryify/OneDark-Pro#299]
As a medical student who later starting using code editor, I have an advice on your theme for eyesight protection purpose:

- ![image](https://user-images.githubusercontent.com/16912240/54877304-83428d00-4e14-11e9-9c53-57caf2dffc74.png)
Places I squared are too much bright as high contrast (including VSC menu items). I suggest row back to VSC default or a least a little lower bright.

- 
![image](https://user-images.githubusercontent.com/16912240/54877339-ef24f580-4e14-11e9-925a-a481e94bf0f2.png)
comments are too vague.

**Comment by JMS55** [comment]
I think both the files tab bar and the extensions sidebar look fine. If they aren't the same color already, maybe make the menu text color the same as the extensions color, I agree it's too bright.

**Comment by Binaryify** [comment]
just publish new version and improve that, you can check if it better now

**Comment by Riajyuu** [comment]
fine for me. thx

**Comment by Riajyuu** [comment]
Opps, sorry I missed the WIP label.

**Comment by Binaryify** [comment]
@Riajyuu no, it had done, you can check it now
