### ISSUE TITLE
Typescript Parameter Highlighting after Arrow Functions

### ISSUE THREAD

**Issue by andybond006** [Binaryify/OneDark-Pro#303]
After using a "switch/case" statement, all functions defined after the switch/case will have improper highlighting of the parameter type. Example images below.

![image](https://user-images.githubusercontent.com/10934345/57297338-5e8d3680-709d-11e9-8daa-9af7568f1663.png)

Notice the correct highlighting at the top (yellow color for the type). The functions defined below the switch/case have a red type.

I tested this by moving the functions below to above the function that contained the switch/case and they had their correct yellow highlighting when they were moved above. See below.

![image](https://user-images.githubusercontent.com/10934345/57297467-a8761c80-709d-11e9-9179-30b63a81e1d0.png)

**Comment by Binaryify** [comment]
could you provide the code in your screenshots

**Comment by andybond006** [comment]
After some better testing, the problem is not the switch/case as I originally thought, but the arrow-function declarations. I created a simpler example here:

https://gist.github.com/andybond006/49588071f4ded09fb3500d0bfe2de8d3

I made two comments indicating lines that, if they are commented out, will make everything appear in the correct color scheme in OneDark-Pro.

**Comment by Binaryify** [comment]
that might vscode's issues. arrow function change other keyword highlight scope

**Comment by andybond006** [comment]
Fair enough. Just wanted it to be reported in any case. Thanks for looking into it and for the theme!

**Comment by Binaryify** [comment]
you are welcome👌🏻
