### ISSUE TITLE
[Haskell] keywords and typenames have same colour

### ISSUE THREAD

**Issue by SmaugTheTerrible** [Binaryify/OneDark-Pro#304]
Hi, colors look inconsistent in Haskell files. Keywords, names of type classes and type names use the same color. 
![vscodeexample](https://user-images.githubusercontent.com/49841624/57322609-9aabb000-710c-11e9-8392-76c4d15ec099.png)
Example from Atom:
![atomexample](https://user-images.githubusercontent.com/49841624/57322741-f1b18500-710c-11e9-83e9-8c60296aebbc.png)
Code sample:
```
data Action
  = Action
  { actionName :: EntName
  } deriving (Eq, Show, Generic)

instance FromJSON System
instance FromJSON Component
instance FromJSON State
instance FromJSON Action
```

**Comment by Binaryify** [comment]
will support it soon

**Comment by Binaryify** [comment]
you can check it now

**Comment by SmaugTheTerrible** [comment]
Now it looks pretty good. Thank you!
