### ISSUE TITLE
selection text background color and occurrences highlight text background color are extremely undistinguishable

### ISSUE THREAD

**Issue by victorteokw** [Binaryify/OneDark-Pro#305]
When editor.occurrencesHighlight turned on (this is turned on by default), it's very difficult to know where is selection and where is symbol highlighting.

**Comment by Binaryify** [comment]
could you provide some screenshots

**Comment by Dassderdie** [comment]
I noticed this too. This is esspacially irritating when dealing with variables or strings and you want to copy a word in it.
Untouched:
![untouched](https://user-images.githubusercontent.com/18506183/59420392-1fa17d80-8dcd-11e9-8d57-4b8d430c32b0.PNG)

editor.occurrencesHighlight = disabled
Cursor in string:
![cursor-in-string](https://user-images.githubusercontent.com/18506183/59420388-1f08e700-8dcd-11e9-87db-fa0d6f80aa2e.PNG)
word selected:
![word-selected](https://user-images.githubusercontent.com/18506183/59420393-1fa17d80-8dcd-11e9-85ee-acdedbacb0e6.PNG)

editor.occurrencesHighlight = enabled
Cursor in string:
![cursor-in-string-occurences-enabled](https://user-images.githubusercontent.com/18506183/59420389-1fa17d80-8dcd-11e9-9b13-baece790252c.PNG)
word selected:
![word-selected-occurences-enabled](https://user-images.githubusercontent.com/18506183/59420396-203a1400-8dcd-11e9-8b25-dc4451f85240.PNG)

**Comment by Binaryify** [comment]
I saw other themes have this issue too, thinking it's vscode itself issue, still don't know how to fix it

**Comment by Bandit** [comment]
I have this issue too - I just disabled `editor.occurrencesHighlight` for now 👍

**Comment by exploreMax** [comment]
According to [Theme Color Reference](https://code.visualstudio.com/api/references/theme-color) the color of the setting `editor.wordHighlightBackground` *«must not be opaque so as not to hide underlying decorations»*. So I changed it from `#484e5b` to `#d2e0ff2f` and everything works fine.

Demo: [before](https://trello-attachments.s3.amazonaws.com/5d04891fb4a40203a0ed84c8/5c35baec43755b44df3152dc/f9c692122d28b8b51f662f91eaf8ab1f/vscode_onepro_before.mp4), [after](https://trello-attachments.s3.amazonaws.com/5d04891fb4a40203a0ed84c8/5c35baec43755b44df3152dc/847501f00dc6dd4adafdaf5cecae51a5/vscode_onepro_after.mp4)

**Comment by exploreMax** [comment]
Same goes for the color of the setting `editor.findMatchHighlightBackground`. It must not be opaque:

![](https://trello-attachments.s3.amazonaws.com/5d04891fb4a40203a0ed84c8/5c35baec43755b44df3152dc/53f73c14802c2cd48d71ec8c7fea713e/vscode_fix_before_after.png)

**Comment by Binaryify** [comment]
just fixed this issues in v2.8.1
thank @exploreMax for his advice
