### ISSUE TITLE
C++ keyword delete isn't highlighted

### ISSUE THREAD

**Issue by miziaiba** [Binaryify/OneDark-Pro#306]

**Comment by Binaryify** [comment]
could you provide some code and screenshots?

**Comment by miziaiba** [comment]
![捕获](https://user-images.githubusercontent.com/22068960/58298513-5f98c480-7e0e-11e9-9470-c6226a99fc41.PNG)

**Comment by miziaiba** [comment]
VSCode version: 1.34.0 (system setup)
VSCode Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by Binaryify** [comment]
you can check it now
