### ISSUE TITLE
Syntax coloring difference between JavaScript and TypeScript.

### ISSUE THREAD

**Issue by JamieCorkhill** [Binaryify/OneDark-Pro#310]
In JavaScript with VS Code, an example of syntax colors are as follows:

![JS Version](https://user-images.githubusercontent.com/28678855/59546495-07784e00-8ef4-11e9-8eae-3a87aa50d70a.png)

Tn TypeScript with VS Code, that same snippet is colored this way:
![TS Version](https://user-images.githubusercontent.com/28678855/59546500-1959f100-8ef4-11e9-8ebc-f1359dd724a0.png)

I prefer the JavaScript color versions, so what would be the best way to maintain the same color schemes among TypeScript and JavaScript files?

Thank you.

**Comment by Binaryify** [comment]
do you have any other plugins installed, it look like same in my vscode 
![image](https://user-images.githubusercontent.com/12221718/59551118-3f8c9900-8fa7-11e9-935f-b7f9b6f31df8.png)
![image](https://user-images.githubusercontent.com/12221718/59551120-45827a00-8fa7-11e9-83aa-b575b038e447.png)

**Comment by JamieCorkhill** [comment]
@Binaryify Not that I know of. I'm not completely familiar with how you customize VS Code, so might there be a JSON file I can provide you with containing data about VS Code's themes/color schemes?

Thank you.

**Comment by Binaryify** [comment]
Do you have installed  Babel ES6/ES7 extension in your vscode

**Comment by Binaryify** [comment]
if you installed that, you can uninstall it

**Comment by Binaryify** [comment]
or try to uninstall/disable other javascript syntax extension

**Comment by JamieCorkhill** [comment]
@Binaryify

Good catch. Indeed, it is Babel ES6/ES7 that is giving me the red coloring.

With that said, I like the red coloring on the variable name, so is there a way to get that same coloring in TypeScript, do you know of, perhaps by changing in a hex value in the config of OneDarkPro?

Thank you.

**Comment by Binaryify** [comment]
check this
https://binaryify.github.io/OneDark-Pro/#/

**Comment by JamieCorkhill** [comment]
@Binaryify 

Thanks. I looked at that before I opened this issue. I do not have a `themes` directory under `/extensions`, and I couldn't find a `colors.json` and a `syntax.json`.

**Comment by Binaryify** [comment]
you should cd this folder
![image](https://user-images.githubusercontent.com/12221718/59647276-25bca300-91ad-11e9-9f0d-74b7230424c4.png)
![image](https://user-images.githubusercontent.com/12221718/59647288-3240fb80-91ad-11e9-9714-81602cfa9685.png)

change the syntax json then run npm i to install dependencies, then run npm run build

**Comment by JamieCorkhill** [comment]
@Binaryify Thanks.

I have done that, but there is no `syntax.json` file there. I read the instructions on your website before I ever opened this issue. 

See:

![pwd](https://user-images.githubusercontent.com/28678855/59647534-2b7c9f00-9141-11e9-9534-84092971b51e.PNG)

Sorry to be a bother.

**Comment by Binaryify** [comment]
in this dir
![image](https://user-images.githubusercontent.com/12221718/59647587-5d781a80-91ae-11e9-88f8-f988a1ac0846.png)
the theme dir is the folder after build

**Comment by Binaryify** [comment]
after you run `npm run build`, the files in theme folder will change

**Comment by JamieCorkhill** [comment]
@Binaryify 

I see it now. Thank you. So, all I have to do is copy the HEX color of Babel ES6/ES7 into the corresponding section of `syntax.json`?

**Comment by Binaryify** [comment]
you should check the scope
![image](https://user-images.githubusercontent.com/12221718/59647793-2b1aed00-91af-11e9-9ef3-4a50241c1193.png)
then change the foreground or add snippet like this
![image](https://user-images.githubusercontent.com/12221718/59647840-687f7a80-91af-11e9-9028-6a79b4e2a88a.png)
```
 {
      name: 'Classes',
      scope: 'support.class.console',
      settings: {
        foreground: colorObj['coral']
      }
    },
```

**Comment by Binaryify** [comment]
also you can check the color map in the color.json
![image](https://user-images.githubusercontent.com/12221718/59647860-7f25d180-91af-11e9-8214-c3c63709a659.png)

**Comment by JamieCorkhill** [comment]
@Binaryify 

Thank you very much for all of your help.

I'll close this for now, then, barring any unexpected issues.

Again, I appreciate it.

**Comment by Binaryify** [comment]
ok, BTW, after you run the npm run build and no error happen, you should reload vscode window to let it take effect
![image](https://user-images.githubusercontent.com/12221718/59647930-beecb900-91af-11e9-8584-d71fcaffe0bb.png)

**Comment by JamieCorkhill** [comment]
@Binaryify Okay. Thanks.
