### ISSUE TITLE
Class name is no longer colored in VS Code 1.36

### ISSUE THREAD

**Issue by ducalex** [Binaryify/OneDark-Pro#313]
Class names are no longer colored in C++ class implementations in VS Code 1.36:

VS Code 1.35.1:
![alt text](https://i.imgur.com/gmRRe7E.png)

VS Code 1.36:
![alt text](https://i.imgur.com/AT9vvyO.png)

**Comment by Binaryify** [comment]
guess vscode just update C++ extension, will fix it soon

**Comment by Binaryify** [comment]
just release a new version, you can check it now

**Comment by ducalex** [comment]
Thanks for the update!

The constructor is fixed but destructor and normal methods are still wrong:

![](https://i.imgur.com/Fhzg4EZ.png)

**Comment by Binaryify** [comment]
could you provide the code in your screenshot

**Comment by ducalex** [comment]
Here's a stripped down version
[test.zip](https://github.com/Binaryify/OneDark-Pro/files/3363828/test.zip)

**Comment by ducalex** [comment]
I should mention that I have C_Cpp.enhancedColorization disabled.
When it is enabled (default) the colors are correct.

**Comment by Binaryify** [comment]
just release a new version, you can check it now~

**Comment by ducalex** [comment]
It is fixed, thank you!
