### ISSUE TITLE
One dark pro and Vivid theme is the same color

### ISSUE THREAD

**Issue by littlemonster00** [Binaryify/OneDark-Pro#314]
When I opened 2 VScode windows, I suddenly found that there are 2 completely different themes then I proceeded to reinstall the theme for OneDark-Pro but both 2 themes is the same things as color.
Can anyone explain to me understand what is happen here.
Thanks.

**Comment by Binaryify** [comment]
vivid color is a little different
![image](https://user-images.githubusercontent.com/12221718/60754593-d8965900-a015-11e9-9593-9e6bb3da03c4.png)
bold's color is same as default, but some code font weight is more high

**Comment by littlemonster00** [comment]
Thank you.
I have discovered what happened to my Themes which is due to the latest update of VScode 1.36 on ubuntu. 
when i reinstall version 1.35 that disappear.

**Comment by ahsan-a** [comment]
Sorry to disturb but what extension are you using to get the colour as the background of the hex code?

**Comment by Binaryify** [comment]
@ahsan-a  Color Highlight
