### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by giuseppepagnoni** [Binaryify/OneDark-Pro#315]
I get this error after installing the extension on VS code latest stable build.

**Comment by Binaryify** [comment]
that shouldn't be caused by this extensions, could you provide more info

**Comment by vmwell** [comment]
the same problem
my vs code version is 1.40.1

**Comment by vmwell** [comment]
One Dark Pro version: 3.0.3

**Comment by Binaryify** [comment]
@vmwell could you provide some screenshots?
