### ISSUE TITLE
Color change for constant.character.format.placeholder.other.python

### ISSUE THREAD

**Issue by holdenkilbride** [Binaryify/OneDark-Pro#317]
https://github.com/Binaryify/OneDark-Pro/blob/1138b93ea8bf5b646f9f95b3247d8912c7550b83/src/syntax.js#L575

The current color of green is the same as the color for the string syntax.  This should be changed to 'whiskey' to allow syntax highlighting relating to Python string formatters to stand out.

```
{
  name: 'constant.character.format.placeholder.other.python',
  scope: 'constant.character.format.placeholder.other.python',
  settings: {
    foreground: colorObj['whiskey']
}
```

**Comment by Binaryify** [comment]
could you provide the code what it can effect

**Comment by holdenkilbride** [comment]
I'm not sure I follow?  An example of what I am referring to is the following:

```
def hello(something):
    print('hello{something}'.format(something=something))
```
The text in between the curly braces '_{something}_' would be colored whiskey.  Almost all other VSCode themes follow this highlighting model.

Did you want a merge request?

**Comment by Binaryify** [comment]
yes 😃
