### ISSUE TITLE
Go const variable highlight

### ISSUE THREAD

**Issue by iiinsomnia** [Binaryify/OneDark-Pro#322]
![image](https://user-images.githubusercontent.com/6582246/62104535-693d1d80-b2d2-11e9-8a1b-45976130216b.png)

**Comment by Binaryify** [comment]
I also want to highlight that, but bad news  is it doesn't have a special scope, so I can't highlight it now untill vscode add a special scope to it
![image](https://user-images.githubusercontent.com/12221718/62105418-e6699200-b2d4-11e9-86a4-55971cc87421.png)

**Comment by iiinsomnia** [comment]
Thanks !
