### ISSUE TITLE
expression and string should have different color in angular2 template

### ISSUE THREAD

**Issue by zzs1020** [Binaryify/OneDark-Pro#323]
In an angular2+ project, expressions and string are always wrapped by double-quotes, but they should be distinguished by 2 colors because it's confusing.

![Capture](https://user-images.githubusercontent.com/23032993/62231219-9ac8ee00-b391-11e9-93bd-4800bad16e4e.PNG)

for above example, `navbar-mobile-show, _header, logo` are strings, but `true, logoSmall, onclickHeaderMenu` are expressions.

**Comment by Binaryify** [comment]
you should instann https://marketplace.visualstudio.com/items?itemName=ghaschel.vscode-angular-html

**Comment by zzs1020** [comment]
@Binaryify thanks!
