### ISSUE TITLE
Updated VSCode Warning Colors Do Not Match

### ISSUE THREAD

**Issue by travisbashor** [Binaryify/OneDark-Pro#324]
In VSCode update 1.36.1, a color was chosen for `list.warningForeground` and `editorWarning.foreground` - a golden yellow color. Since OneDarkPro does not specify colors for those fields, the same golden yellow shows up by default in the editor, breaking the consistency of the OneDarkPro theme.

See [here](https://code.visualstudio.com/updates/v1_36#_updated-warning-colors) for the change.

I've been using 
```
"workbench.colorCustomizations": {
        "list.warningForeground": "#c24038",
        "editorWarning.foreground": "#c24038"
    }
```
to compensate in the short term.

Consider updating the theme to specify colors for those, so that the theme will be consistent regardless of VSCode updates.

**Comment by Binaryify** [comment]
could you provide a screenshot about what it can change

**Comment by travisbashor** [comment]
Sure thing. Those are the default colors below. I replaced the yellow with the red above, but I think even that red might be a little too dark. It was just better than the yellow :)

![VSCode Default Colors - Editor and List](https://user-images.githubusercontent.com/4589776/62377300-83643f00-b510-11e9-926a-41af234ce42d.png)

**Comment by Binaryify** [comment]
just release a new version,  you can check it now

**Comment by cyberbit** [comment]
I'm confused why `editorWarning.foreground` was changed to (1) red and (2) a red that doesn't even match the rest of the theme:

![image](https://user-images.githubusercontent.com/7350183/62481305-b5c3a580-b777-11e9-8eca-d5f612c41da4.png)

IMHO the switch to a yellow color for warning squigglies was better for visually grepping a file for linter issues vs. compile issues.

**Comment by louis-lau** [comment]
I've been confused for the past day why the hell warnings were showing up as errors in vscode. Guess they weren't. I'm still confused by the choice to make warnings dark red and errors a slightly brighter red.

Warnings aren't red in atom either.

**Comment by grovertb** [comment]
You should think about returning to the yellow warning color, because it is confusing to have the error and warning be red.

**Comment by Dreamacro** [comment]
I spent a lot of time thinking about why `warning` is yellow. please revert this change.

**Comment by ford04** [comment]
I consciously decided to display my tslint erros with warning color (yellow in recent VS Code). Now it's all one big mess; first I wanted to blame VS Code, then tslint.... until I realized it's my favourite theme :( .

**Comment by Binaryify** [comment]
@cyberbit @louis-lau @grovertb @Dreamacro @ford04 sorry for that, will change it be yellow, but not the default yellow for more coordinated

**Comment by Binaryify** [comment]
just release a new version~ thanks for all feedback
