### ISSUE TITLE
Differences between JS and TS in if/for/while statements

### ISSUE THREAD

**Issue by ATiltedTree** [Binaryify/OneDark-Pro#325]
JS
![image](https://user-images.githubusercontent.com/47182955/62486032-7d938580-b7be-11e9-8561-ee31ea4b5267.png)

TS
![TS](https://user-images.githubusercontent.com/47182955/62486054-87b58400-b7be-11e9-94ce-402260d77d37.png)

Notice the difference at `||` and `&&`.

**Comment by Binaryify** [comment]
just fixed it~
