### ISSUE TITLE
js keyword `typeof` highlight incorrectly

### ISSUE THREAD

**Issue by cyphernull** [Binaryify/OneDark-Pro#330]
`typeof` should be highlighted the same as `const`, but: 
![image](https://user-images.githubusercontent.com/23122353/63998767-7dc04000-cb34-11e9-8d45-86cd7e02f99b.png)

**Comment by Binaryify** [comment]
which version are you using

**Comment by cyphernull** [comment]
i'm using 2.27.1

**Comment by Binaryify** [comment]
you can disabled other extensions but Onedark Pro to check if it's Onedark Pro's issue, it's normal in my vscode

**Comment by cyphernull** [comment]
i just disabled [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel), and it looks correct. There must be conflicts then.

**Comment by Binaryify** [comment]
you don't Babel JavaScript if you use this theme

**Comment by cyphernull** [comment]
I should not use Babel JavaScript while I am using this theme ?

**Comment by Binaryify** [comment]
yes
