### ISSUE TITLE
Vivid Bold maybe?

### ISSUE THREAD

**Issue by kris-cloudaccess** [Binaryify/OneDark-Pro#331]
Hello,

I was thinking if it would be possible to do both vivid and bold?
That would be the preferred option for me.

What do you think, are there any possible issues with this?

Regards,
Kris Sibinski

**Comment by mskelton** [comment]
@kris-cloudaccess I maintained a fork of this theme for a while and recently made some major changes to it to use settings for controlling vivid, bold, and italics to allow any combination of the theme variants.  If you are interested you can check it out here: https://github.com/one-dark/vscode-one-dark-theme.

**Comment by Binaryify** [comment]
will support in next version

**Comment by Binaryify** [comment]
just support this in v3.0
