### ISSUE TITLE
Different colors for syntax highlighting from Atom

### ISSUE THREAD

**Issue by pensierinmusica** [Binaryify/OneDark-Pro#332]
Hi,

I'm not sure whether this is intentional or not, but it seems like the original `One Dark` theme in Atom has different syntax highlighting colors than `OneDark-Pro` in VS Code, at least when using JavaScript.

**Atom** - One Dark

<img width="445" alt="atom" src="https://user-images.githubusercontent.com/3594037/64655610-10ae8380-d42d-11e9-9311-faf522812364.png">

**VS Code** - OneDark-Pro

<img width="417" alt="vscode" src="https://user-images.githubusercontent.com/3594037/64655623-1906be80-d42d-11e9-96f3-91c1747eab05.png">

Is this an intentional choice or a bug?

Thanks!

**Comment by Binaryify** [comment]
this theme has improved the origin OneDark theme, so that's no bug but feature

**Comment by pensierinmusica** [comment]
👍
