### ISSUE TITLE
in macOS mojave , themes  seems not like the same with screenshot

### ISSUE THREAD

**Issue by hgwang** [Binaryify/OneDark-Pro#335]
in macOS mojave , themes  seems not like the same with screenshot in your project

macOS version:  macOS mojave,
vscode version: 1.38.1
OneDark-Pro:2.27.2

<img width="480" alt="WX20190926-113538@2x" src="https://user-images.githubusercontent.com/3928634/65656382-40c36c80-e052-11e9-860a-28fe47fa0f6d.png">

**Comment by Binaryify** [comment]
do you have install the Rainbow Brackets or other extensions

**Comment by hgwang** [comment]
extensions: Bracket Pair Colorizer, Vetur,vscode-icons,Project Manager, one Dark Pro, beautify, atom key map, auto close tag, auto rename tag, editorconfig,eslint, git history, language-stylus, markdown all in one, postcss syntax

**Comment by Binaryify** [comment]
you can disabled Bracket Pair Colorizer

**Comment by Binaryify** [comment]
or you can custom the color as the docs of bracket-pair-colorizer 
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer

**Comment by hgwang** [comment]
I reinstall the vscode, and only install the one dark pro extension, then it's still not work

**Comment by Binaryify** [comment]
could you provide some screenshot

**Comment by hgwang** [comment]
i found the reason,  the main problem is font family， thank you very much！

**Comment by Binaryify** [comment]
okay
