### ISSUE TITLE
Why do the variable name display inconsistent colors?

### ISSUE THREAD

**Issue by hua03** [Binaryify/OneDark-Pro#342]
like this:

![image](https://user-images.githubusercontent.com/19561959/66267119-f74bfc00-e85f-11e9-88c7-74cb5c1780ee.png)

**Comment by Binaryify** [comment]
check if you installed Bracket Pair Colorizer

**Comment by hua03** [comment]
I has disabled Bracket Pair Colorizer but it has no effect.

**Comment by Binaryify** [comment]
did you mean this is inconsistent 

![image](https://user-images.githubusercontent.com/12221718/66267605-6440a100-e822-11e9-9606-6a7c1cee2ba0.png)

**Comment by hua03** [comment]
yes, I noticed that other themes have similar problems.

**Comment by hua03** [comment]
But in webstorm, they are consistent

**Comment by Binaryify** [comment]
yes, this is vscode itself issue, the variable have same scope, so the color is same
![image](https://user-images.githubusercontent.com/12221718/66267674-90a8ed00-e823-11e9-900d-d1fe0003b107.png)
![image](https://user-images.githubusercontent.com/12221718/66267678-97cffb00-e823-11e9-80e2-23ef1163443b.png)

![image](https://user-images.githubusercontent.com/12221718/66267741-4ecc7680-e824-11e9-9f6f-eedc6efb169e.png)
![image](https://user-images.githubusercontent.com/12221718/66267744-59870b80-e824-11e9-8495-496e9040a04b.png)

**Comment by hua03** [comment]
OK, sometimes it confuse me.😅
