### ISSUE TITLE
create a darker background version

### ISSUE THREAD

**Issue by mraines4** [Binaryify/OneDark-Pro#345]
I modified the bold version to have a significantly darker background which makes the contrast a lot better. But every time a new update comes out, it deletes it. Can we make a version for this? what I changed is

```
    "editor.lineHighlightBackground": "#1F1F1F",
    "editor.background": "#191919",
```

**Comment by mifas** [comment]
You can overwrite theme's color setting by 
```
"workbench.colorCustomizations": {
"[One Dark Pro Vivid]": {
    "editor.lineHighlightBackground": "#1F1F1F",
    "editor.background": "#191919"
 }
}
```

https://code.visualstudio.com/api/references/theme-color

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/69030739-6433e380-0a13-11ea-9e20-3e6b3de3352e.png)
![image](https://user-images.githubusercontent.com/12221718/69030748-68f89780-0a13-11ea-9a35-27dcb049da11.png)
you can switch other editor theme and keep same syntax highlight in v3.0 now
https://github.com/Binaryify/OneDark-Pro/blob/master/releaseNote.md
