### ISSUE TITLE
After the update to 3.0.0 vivid is gone from menu to choose. Awful file select color

### ISSUE THREAD

**Issue by luluhoc** [Binaryify/OneDark-Pro#348]
After the update vivid is gone from the menu to choose, is this an error or you've removed it?

I get this awful color when selecting a file. The file name is unreadable when it is selected.
![image](https://user-images.githubusercontent.com/22813220/69012513-f89c3880-0976-11ea-9c4d-4b239d0007dc.png)

**Comment by xlxAciDxlx** [comment]
You have to add `"oneDarkPro.vivid": true` or `"oneDarkPro:bold": true` to your VSCode settings.

**Comment by luluhoc** [comment]
I've added it but it doesn't seem to work and the weird highlight is still there. 
![image](https://user-images.githubusercontent.com/22813220/69012721-3732f280-0979-11ea-9dd3-f11e816cfdba.png)

**Comment by xlxAciDxlx** [comment]
Yeah, I had added them and thought it worked, but it looks like a bunch of stuff is currently really weird with the theme. Either that or I'm missing something that should be obvious. lol

**Comment by Binaryify** [comment]
you might no check the release note(will open after update)
https://github.com/Binaryify/OneDark-Pro/blob/master/releaseNote.md
https://camo.githubusercontent.com/0477890abd1d03d2aab95cd54bf85c0f5b277256/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f31372f4a596e6c394852614b7a566279514f2e706e67

**Comment by Binaryify** [comment]
> Yeah, I had added them and thought it worked, but it looks like a bunch of stuff is

**Comment by luluhoc** [comment]
> you might no check the release note(will open after update)
> https://github.com/Binaryify/OneDark-Pro/blob/master/releaseNote.md
> 
> ![](https://camo.githubusercontent.com/0477890abd1d03d2aab95cd54bf85c0f5b277256/68747470733a2f2f692e6c6f6c692e6e65742f323031392f31312f31372f4a596e6c394852614b7a566279514f2e706e67)

thank you so much!

**Comment by Binaryify** [comment]
@xlxAciDxlx check https://github.com/Binaryify/OneDark-Pro/blob/master/releaseNote.md
