### ISSUE TITLE
Is the foreground color too bright when the item is selected in the work tree ?

### ISSUE THREAD

**Issue by liby** [Binaryify/OneDark-Pro#349]
Blue is a bit abrupt and doesn't match the black background.
![image](https://user-images.githubusercontent.com/38807139/69019244-b44a8000-09ea-11ea-82cc-5fb4ddcdb4a6.png)

I think this light grey looks more harmonious, What do you think ?
![image](https://user-images.githubusercontent.com/38807139/69019273-db08b680-09ea-11ea-8a27-de1bdeb6bfc9.png)

Also, your update log appears to have the wrong date.
![image](https://user-images.githubusercontent.com/38807139/69019327-1f945200-09eb-11ea-85c2-33a4c9eed14a.png)

**Comment by Binaryify** [comment]
have you custom the focus text color, default is not that color
like this
![image](https://user-images.githubusercontent.com/12221718/69020365-2fae3080-09ef-11ea-8425-4dc665ee1147.png)

**Comment by Binaryify** [comment]
also consider changing the selected background color

**Comment by Binaryify** [comment]
oh, that's a bug when I update v3.0, lose some config, will fix it soon

**Comment by Binaryify** [comment]
just fixed it

**Comment by liby** [comment]
You solve problems very quickly, Thank you for making such a beautiful editor theme!
