### ISSUE TITLE
Set Color Theme button not working

### ISSUE THREAD

**Issue by darcypaynter** [Binaryify/OneDark-Pro#353]
After updating VS Code, the OneDark-Pro thema was no longer applied and clicking the  "Set Color Theme" button resulted in this toast 
![image](https://user-images.githubusercontent.com/29769088/69103092-8f244300-0ab8-11ea-8e95-d84de66f3959.png)

**Comment by Binaryify** [comment]
are you using linux?

**Comment by darcypaynter** [comment]
I'm using windows 10

**Comment by Binaryify** [comment]
have you try uninstall theme then reinstall it

**Comment by darcypaynter** [comment]
yes and restarting Vscode

**Comment by Binaryify** [comment]
coild you open vscode dev tools then show me rhe logs

**Comment by darcypaynter** [comment]
`

  | onDidNotificationChange | @ | workbench.desktop.main.js:sourcemap:2596
-- | -- | -- | --
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:2596
  | fire | @ | workbench.desktop.main.js:sourcemap:115
  | addNotification | @ | workbench.desktop.main.js:sourcemap:2660
  | error | @ | workbench.desktop.main.js:sourcemap:3923
  | onError | @ | workbench.desktop.main.js:sourcemap:5778
  | fire | @ | workbench.desktop.main.js:sourcemap:115
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:110
  | fire | @ | workbench.desktop.main.js:sourcemap:115
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:110
  | fire | @ | workbench.desktop.main.js:sourcemap:115
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:932
  | fire | @ | workbench.desktop.main.js:sourcemap:115
  | run | @ | workbench.desktop.main.js:sourcemap:141
  | async function (async) |   |  
  | run | @ | workbench.desktop.main.js:sourcemap:141
  | onClick | @ | workbench.desktop.main.js:sourcemap:929
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:928
  | processImmediate | @ | internal/timers.js:439

`

**Comment by darcypaynter** [comment]
![image](https://user-images.githubusercontent.com/29769088/69103648-11613700-0aba-11ea-936a-ba13e26316a2.png)

**Comment by Binaryify** [comment]
it seem like vscode issues 
check this
https://github.com/sdras/night-owl-vscode-theme/issues/176
https://github.com/microsoft/vscode/issues/47550

**Comment by darcypaynter** [comment]
changing theme using command pallet fixed my issue
