### ISSUE TITLE
主题更换出错

### ISSUE THREAD

**Issue by Rengf** [Binaryify/OneDark-Pro#354]
Issue Type: <b>Feature Request</b>

更换主题颜色时报错：Cannot read property 'id' of undefined

Extension version: 3.0.3
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Binaryify** [comment]
https://github.com/Binaryify/OneDark-Pro/issues/353
