### ISSUE TITLE
Scoping for member variables are incorrect when it's a function-call argument

### ISSUE THREAD

**Issue by xeb10154** [Binaryify/OneDark-Pro#355]
This might have been reported before, if so, then my apologies. This issue is specific to Python syntax highlighting.

I was comparing the theme to Atom's python syntax highlighting and I made one minor tweak to ensure the syntax scoped to `meta.member.access.python` in vscode is highlighted as red `(#e06c75ff)`. Before the tweak, it is white by default. See screenshot (line 219) for the result (`title` field is now highlighted red).

<img width="808" alt="Screenshot 2019-11-19 at 11 05 48" src="https://user-images.githubusercontent.com/25885192/69143424-da425400-0ac0-11ea-8a61-04b750f0c5ee.png">

However, it seems the member `recipe` and the member accessor `title` are scoped the same way when it is inserted as a function argument. See line 221, both `recipe` and `title` are highlighted red. In Atom, this is not the case as shown here:

<img width="265" alt="Screenshot 2019-11-19 at 11 07 55" src="https://user-images.githubusercontent.com/25885192/69143468-f5ad5f00-0ac0-11ea-8195-836521f6c050.png">

Is there any way to change the scoping so that the member syntax stays white and the member accessor is red?

**Comment by Binaryify** [comment]
if their scope is same, that should be vscode itself issue
