### ISSUE TITLE
Enums with associated data are colored differently in rust

### ISSUE THREAD

**Issue by JMS55** [Binaryify/OneDark-Pro#357]
![image](https://user-images.githubusercontent.com/47158642/69179641-db33af80-0ad9-11ea-9f2e-dfde577ba475.png)

I would change the blue ones to grey

**Comment by Binaryify** [comment]
I think that is vscode's issue, vscode think it is a function, but it's not
![image](https://user-images.githubusercontent.com/12221718/69300205-7ac57f00-0c4d-11ea-8406-4fca2197bfd5.png)
and this problem also happen in other theme
![image](https://user-images.githubusercontent.com/12221718/69300252-9892e400-0c4d-11ea-8d96-4bf7a8d75be0.png)
![image](https://user-images.githubusercontent.com/12221718/69300275-a5173c80-0c4d-11ea-8806-38041310e2c1.png)

**Comment by JMS55** [comment]
Ok, I'll open an issue with vscode then
