### ISSUE TITLE
V3 does not work in Visual Studio Online or code-server

### ISSUE THREAD

**Issue by JtMotoX** [Binaryify/OneDark-Pro#360]
V3 does not work in [Visual Studio Online](https://visualstudio.microsoft.com/services/visual-studio-online/) or [code-server](https://github.com/cdr/code-server/blob/master/README.md).

I use code-server primarily and something in the new version causes the theme to not be recognized in code-server.  I was able to download previous version and disable extension updates to get it to work again.

For anyone else out there, here is the link to download V2 which works with code-server.  Make sure to disable Extension Updates in your settings.

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/zhuangtongfa/vsextensions/Material-theme/2.28.3/vspackage

**Comment by Binaryify** [comment]
https://github.com/Binaryify/OneDark-Pro/issues/350

**Comment by Binaryify** [comment]
it might fixed in v3.0.3

**Comment by JtMotoX** [comment]
**Solved**: The latest release of code-server still uses VSC 1.39 and One Dark Pro v3 now requires 1.40.  This is not your fault so I am closing this issue.  I found that if I modify the package.json to "vscode": "^1.39.0" that the theme loads so for now I am able to get by. Thanks again for making the greatest theme. 👍
