### ISSUE TITLE
Notification keeps appearing

### ISSUE THREAD

**Issue by misolori** [Binaryify/OneDark-Pro#361]
![image](https://user-images.githubusercontent.com/35271042/69560348-75737780-0f60-11ea-9d62-10a3dfae1834.png)

Over the last few days I've been getting this notification multiple times a day and it's becoming quite annoying. Can you please change it so this only show up once? It's getting so bad that I am close to uninstalling it.

**Comment by Binaryify** [comment]
will improve that in next version

**Comment by Binaryify** [comment]
was improve that in v3.2.0
