### ISSUE TITLE
Bothersome changelog

### ISSUE THREAD

**Issue by DAVIDhaker** [Binaryify/OneDark-Pro#364]
Dear developer(s). Great thanks for work for this Theme.  Its a good project. I'm using this. But to me absolutely is not interested any information about updates. Its just a theme. Nothing more. But notices about updates like in big projects about big changes. No offence was to tell, dear. But, let imagine next: MS will notifying about all little chores. Invalid pointer (C++) - put to changelog. Bad descriptor - put to changelog. Icon added to standart icon library. And any other bug or change in deep core - put to changelog. And after all - send to simple user for read. There is nothing to for the user to know about it. 

Thanks to developer, thanks to all. People can vote to this think or vs.

**Comment by Binaryify** [comment]
will improve that in next version, thank for the feedback

**Comment by Binaryify** [comment]
was improve that in v3.2.0
