### ISSUE TITLE
VIvid does‘t work

### ISSUE THREAD

**Issue by xuanxuan321** [Binaryify/OneDark-Pro#366]
It doesn't work when I plug in the monitor(1080P)and open vscode, but it does work when I open vscode directly on the MACbook pro

**Comment by pmccarren** [comment]
I'm seeing the same thing - when launching VScode on MacOS colors are more vibrant than when launching on a non-retina monitor.

**Comment by cotneit** [comment]
But do colors change when you change the setting? It can be hard to tell the difference and the issues you are experiencing are probably related to the fact that your displays have different color coverage. If that's the case, you can't really do anything about it.

**Comment by Binaryify** [comment]
@scottmwyant 
there have some bug when switch vivid config

**Comment by Binaryify** [comment]
this problem had been fixed in v3.8.5, please update~

**Comment by lromanov** [comment]
@Binaryify Hi, I experience the same problem now on v3.10.14.
Any ideas?

**Comment by pmccarren** [comment]
For an unknown reason, One Dark Pro looses it's vivid settings. Haven't spent any time tracking it down, but have a simple workaround that I use every time Code launches:

1. disable vivid, save and reload Code
2. enable vivid, save and reload Code
