### ISSUE TITLE
embedded YAML list dash is wrong color

### ISSUE THREAD

**Issue by brandonkal** [Binaryify/OneDark-Pro#370]
`punctuation.definition.block.sequence.item.yaml` is incorrectly highlighted. In other themes, the dash is white. This is not an issue in Atom One Dark theme.

Note the dash is green instead of white in line 44 here:
<img width="351" alt="Screen Shot 2019-12-31 at 4 20 09 PM" src="https://user-images.githubusercontent.com/4714862/71636772-bad33680-2be9-11ea-9f3b-a3b726fd6de7.png">

**Comment by brandonkal** [comment]
The required fix
```
{
  "editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
      "textMateRules": [
        {
          "scope": ["source.ts punctuation.definition.block"],
          "settings": { "foreground": "#ABB2BF" }
        }
      ]
    }
  }
}
```

**Comment by Binaryify** [comment]
could you provide the code in your screenshot?

**Comment by brandonkal** [comment]
Here is a simple version for you:
```
const k = y`
map_key:
  containers:
  - name: myapp
```

**Comment by Binaryify** [comment]
could you tell me how to use embedded YAML syntax

**Comment by brandonkal** [comment]
Sure thing, this is my extension that provides syntax highlighting for embedded yaml:

https://marketplace.visualstudio.com/items?itemName=brandonkal.yaml-embed

**Comment by Binaryify** [comment]
just fixed it, you can check it now

**Comment by brandonkal** [comment]
Perfect. Thank you!
