### ISSUE TITLE
Color debug status bar

### ISSUE THREAD

**Issue by JMS55** [Binaryify/OneDark-Pro#374]

**Comment by Binaryify** [comment]
could you provide more infomation

**Comment by JMS55** [comment]
When debugging, the status bar turns purple. Not sure what a better color would be, but I'm not a fan of the purple.
![image](https://user-images.githubusercontent.com/47158642/75612404-04100b80-5af1-11ea-802f-0923ed9f9e21.png)

**Comment by Binaryify** [comment]
I just change that, you can check it later~

**Comment by JMS55** [comment]
Looks good!

**Comment by tristan957** [comment]
Hi @Binaryify, I really like the debug status bar color. Something I noticed in a recent debugging session was that hovering status bar elements during a debug session lost the orange color (One Dark Pro Darker). The hover color was the same or nearly the same as the default status bar color.

Happy to try to provide a screenshot if you can't reproduce what I am talking about or don't understand it.

**Comment by Binaryify** [comment]
@tristan957 are you using flat theme now

**Comment by tristan957** [comment]
No, actually my theme is just the plain "One Dark Pro"

**Comment by Binaryify** [comment]
@tristan957 just fixed that in v3.13.26, you can check it now

**Comment by skilkis** [comment]
I see now that some changes were incorporated by #726 which removed semantics of when the debugger was active

**Comment by tristan957** [comment]
@Binaryify I got a picture of what I was talking about 
![image](https://user-images.githubusercontent.com/11936772/168114436-37857fa6-c565-4a4b-9ab8-fa62e03fc2c7.png)

**Comment by Binaryify** [comment]
@tristan957 I just delete the `statusBarItem.hoverBackground` in v3.13.27, and it look normal now

**Comment by Binaryify** [comment]
@tristan957 in v3.13.29, it look now
<img width="578" alt="image" src="https://user-images.githubusercontent.com/12221718/168199311-d5505ea0-e825-4f4c-aecb-7224d781ad77.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/12221718/168199463-050fb3b5-c6fb-428b-ac83-fbceb9b2f458.png">
<img width="726" alt="image" src="https://user-images.githubusercontent.com/12221718/168199472-27743d83-c5e2-479c-97f4-a0a6da5efe04.png">
