### ISSUE TITLE
Color for functions changes to red

### ISSUE THREAD

**Issue by piotrgredowski** [Binaryify/OneDark-Pro#377]
![Peek 2020-02-09 20-51](https://user-images.githubusercontent.com/4294480/74108803-0defc000-4b7e-11ea-844a-8fab971e78c9.gif)
Really strange behaviour of One Dark Pro theme (or maybe something else causes it?).
Function definitions and calls becomes red (when theme is applied) instead of being blue as declared in theme. Does anybody have some clue what is going on?
When switching to other themes - this problem is not occuring.

**Comment by Jheysoon** [comment]
@piotrgredowski 

https://code.visualstudio.com/updates/v1_42#_semantic-highlighting-for-typescript-javascript

i think you enable the semanticHighlighting.

Set if to false

`"editor.semanticHighlighting.enabled": false`

**Comment by piotrgredowski** [comment]
@Jheysoon
Thank you very much! It was it.
