### ISSUE TITLE
Multiline comments in Python not rendering correctly

### ISSUE THREAD

**Issue by PlanMan1717** [Binaryify/OneDark-Pro#379]
I left a very similar issue on the VSCode repository (Issue #91041). They said to come to you.
In Python, multiline comments render as strings, not as actual comments.
![image](https://user-images.githubusercontent.com/51730258/75616755-78fc3900-5b23-11ea-9dd9-f8a5f9cb0c6b.png)
@alexr00 mentioned changing my settings.json, and I did. But...

1. Uhh. this happened... 
![Annotation 2020-02-29 184925](https://user-images.githubusercontent.com/51730258/75616848-89f97a00-5b24-11ea-83e7-8315b60ffbcf.png)
2. It would be great if the world could see this change made. Think of all the little kids, or pros who use your extension.

**-PlanMan1717**

**Comment by PlanMan1717** [comment]
I may even be able to write a pull request.

**Comment by Nhqml** [comment]
These are not comments but "docstrings" so they should indeed be considered as strings. You can use them as multi line comments where they're not used as "docstrings" but the preferred way is to start each line by a '#' as said in [PEP8](https://www.python.org/dev/peps/pep-0008/#block-comments).

**Comment by PlanMan1717** [comment]
@Nhqml, thank you for the clarification on the matter. I do agree that they should be respected as docstrings. My intent now is to see if the triple quotes can be stylized to match the text. I ***```LOVE```*** this theme, but is there a way?
