### ISSUE TITLE
VsCode February 2020 (version 1.43) update broke syntax highlighting

### ISSUE THREAD

**Issue by RadomirPerisic** [Binaryify/OneDark-Pro#380]
https://github.com/microsoft/vscode/issues/92308

I tested on JS only but I read other languages are affected as well.

Temporary fix is to add
```
"editor.semanticHighlighting.enabled": false
```
in settings.

With semantic highlighting enabled:
![image](https://user-images.githubusercontent.com/5271201/76309017-3b8a6f00-62cc-11ea-9bbf-561b1fe6be27.png)

disabled:
![image](https://user-images.githubusercontent.com/5271201/76308983-2ad9f900-62cc-11ea-95f0-28fc94cdb6dc.png)

**Comment by rebornix** [comment]
thank you for feedback, let's track this issue in https://github.com/microsoft/vscode/issues/92308 for now.

**Comment by jacobdcastro** [comment]
Yeah I'm having the same highlighting problem. Hope it gets fixed soon!

**Comment by Binaryify** [comment]
should wait vscode fix it and release new version, that option shoule be false default

**Comment by RadomirPerisic** [comment]
https://github.com/microsoft/vscode/issues/92308#issuecomment-596912859

I think theme needs to be updated to support new identifiers.

**Comment by kamenivskyi** [comment]
![issue](https://user-images.githubusercontent.com/41705256/76468416-90c1a000-63f4-11ea-8486-b627e10f14cc.jpg)
With imports is the same issue (in React)

**Comment by Binaryify** [comment]
will adapt that in next version, but need some time, so you guy can set it be false, and watiting next version

**Comment by jacobdcastro** [comment]
@Binaryify thanks so much for the hard work! Huge fan of the theme.

**Comment by Binaryify** [comment]
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#as-a-theme-author-do-i-need-to-change-my-theme-to-make-it-work-with-semantic-highlighting
look like vscode will fix this in 1.43.1

**Comment by PandawanFr** [comment]
Great! So will there be a future update that makes use of this semantic highlighting? Theme works fine without it so imo it’s not necessary, but maybe others think differently?

**Comment by Binaryify** [comment]
@PandawanFr I think  it’s not necessary, and I just try to adapt that and found that will make some breaking change

**Comment by mrmckeb** [comment]
Does this mean the theme doesn't need changes to support "semantic highlighting"?

**Comment by Binaryify** [comment]
@mrmckeb I think it doesn't need

**Comment by mrmckeb** [comment]
This is how highlighting looks in the default Dark theme:
![image](https://user-images.githubusercontent.com/5043083/77625987-44767400-6f4d-11ea-9dae-5b0ea797920f.png)

And the same file in OneDark Pro:
![image](https://user-images.githubusercontent.com/5043083/77625934-2c065980-6f4d-11ea-9a9e-51962dfc846a.png)

Maybe it needs a little tweaking?

**Comment by Binaryify** [comment]
@mrmckeb 
i don't think it need and the default dark theme use semantic highlighting but other theme will ignore semantic highlighting after vscode update
