### ISSUE TITLE
Unexpected change of terminal colors

### ISSUE THREAD

**Issue by gsscoder** [Binaryify/OneDark-Pro#384]
It's more easy to attach a picture:
![Screenshot 2020-04-22 at 06 24 07](https://user-images.githubusercontent.com/1194228/79940501-3b03fd00-8462-11ea-88b3-c1374407868a.png)

I remember `write-warning` and its output were yellow.

Am I wrong?

Thanks for **excellent theme**!

Regards,
Giacomo S. S.

**Comment by foreignmeloman** [comment]
This has already been fixed in feee5a3e09429d0f0ff3425dc24e21706fcf8c27.

**Comment by gsscoder** [comment]
Perfect, thank you!
I want to add that it was on **macOS Catalina** machine. On Windows, no problem.

Have a nice day
