### ISSUE TITLE
Support for Semantic Highlighting

### ISSUE THREAD

**Issue by boyedarat** [Binaryify/OneDark-Pro#385]
Can we have full support for Semantic Highlighting as described here?:
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview

To take advantage of this, theming rules for all tokens need to specified, as described here:
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-styling

List of tokens to be covered:
https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview#token-classification-to-textmate-scopes-mapping

**Comment by Binaryify** [comment]
already support semantic highlighting
