### ISSUE TITLE
Markdown preview color matching

### ISSUE THREAD

**Issue by liuzhihangs** [Binaryify/OneDark-Pro#388]
Regarding whether the color style can use the atom style in the markdown preview.

Because I found that the color matching of the code block during the preview, the title color matching is not the style of the atom used.

If you can achieve markdown preview using other styles in other ways, please let me know.

**Comment by Binaryify** [comment]
I don't know how to change that, vscode doesn't provide that way

**Comment by Binaryify** [comment]
well, I just found a way to change code color in markdown preview, might update in few days

**Comment by Binaryify** [comment]
just support that and release a new version, you can check it now, but for the webview limit reason, can't highlight some token

**Comment by al2me6** [comment]
Hmm, it seems like the css files added in 4c2d1c114ce7060fb93ef6b784c656739f991958 are enabled even if One Dark Pro is not used as the current editor themes. This is causing breakage in other themes:

![image](https://user-images.githubusercontent.com/35266431/81485800-f75d1180-921d-11ea-8e83-5918971f3842.png)

**Comment by Binaryify** [comment]
@al2me6 oh, i didn't realized that, will fixed that soon

**Comment by liuzhihangs** [comment]
@Binaryify 
Thanks Reply。

I also found that some styles are different，but now it is much better than before, thank you very much.

``` text
`code`

### title

> quote

```
Atom style

![image](https://user-images.githubusercontent.com/26057042/81559457-0250a700-93c2-11ea-8294-4ea8e8c0748f.png)



Some colors have different styles.
The whole is already very good, especially the table function.

Special thanks, very good.

**Comment by Binaryify** [comment]
@al2me6 just release a new version and limit only active in dark theme, still need to find a way to limit in this theme

**Comment by Binaryify** [comment]
@liuzhihangs will improve that in next version

**Comment by Binaryify** [comment]
I just revert that change in v3.6 for some bug reason, but you could add this into your setting.json
```
"markdown.styles": [
       "https://panda-cdn.oss-cn-shenzhen.aliyuncs.com//base.css",
       "https://panda-cdn.oss-cn-shenzhen.aliyuncs.com//markdown.css",
       "https://panda-cdn.oss-cn-shenzhen.aliyuncs.com//atom-one-dark.css"
    ],
```

**Comment by Binaryify** [comment]
@liuzhihangs 
I just update the markdown css, you could check if it fine

**Comment by liuzhihangs** [comment]
@Binaryify 
Thanks, it's okay now.

**Comment by Binaryify** [comment]
you don't need to set `markdown.styles` now in new version

**Comment by liuzhihangs** [comment]
> you don't need to set `markdown.styles` now in new version

Very good, thank you very much.
