### ISSUE TITLE
C/C++ variables are set red

### ISSUE THREAD

**Issue by w-xy** [Binaryify/OneDark-Pro#390]
In C/C++, all variables are set red. It's too harsh when the C codes are full of variables. 
I wonder if it's a bug, if not, how can I set the variables gray as in python codes?

![捕获](https://user-images.githubusercontent.com/17586945/81551429-68cec880-93b4-11ea-8852-f6caf56970d0.PNG)

----
OS: Win7 Pro SP1
VSCode: 1.44.2
One Dark Pro: 3.5.0

**Comment by sagarbarapatre02** [comment]
Hello, Either you can change your theme to material theme or you can change your IDE. I personally use both Sublime text as well as VS code But in sublime text, the variables are not in red color. So it's completely your choice which  option to choose to.
Happy Coding!!!

**Comment by w-xy** [comment]
@sagarbarapatre02 Thanks for your suggestion, but I don't have a commercial lincense of sublime text, so vs code is the only choise for me. I use atom in my personal computer, and I really enjoy the One-Dark theme. I cannot give up easily...

**Comment by Binaryify** [comment]
could you provide the code in your screenshot

**Comment by w-xy** [comment]
@Binaryify 

```
#include <stdio.h>

void main()
{
   char *name = "Jack";
   printf("Hello, %s\n", name);
}
```

**Comment by Binaryify** [comment]
did you installed other extensions?
that `name` is not red in my vscode
![image](https://user-images.githubusercontent.com/12221718/81666906-389b2e80-9475-11ea-84cf-a4cf0ed0e208.png)

**Comment by w-xy** [comment]
@Binaryify 
I reproduced the problem in my personal computer.
I installed the offcial extension: C/C++, and the `name` turned red immediately. When I disable the extension, it turns gray.
I noticed that there's a wavy line in your screenshot, which seems to mean you didn't install C/C++ extension, or you didn't configure the include path so the header file cannot be identified.
If you have installed the extension, you can just reproduct the problem without any header by this:
`
void main()
{
   char *name = "Jack";
}
`

**Comment by Binaryify** [comment]
ok

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/81704083-02bf6f80-94a0-11ea-9ffc-ca1528a7f266.png)
still can't reproduced, did I miss something?

**Comment by w-xy** [comment]
It seems good in my WSL too. Could you please try it in Windows?

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/81713757-db20d500-94a8-11ea-9821-bec000396a02.png)

**Comment by w-xy** [comment]
![捕获](https://user-images.githubusercontent.com/17586945/81732634-57281680-94c3-11ea-8afe-f2be8915bf12.PNG)
![捕获2](https://user-images.githubusercontent.com/17586945/81732648-5a230700-94c3-11ea-83ab-bdabe2ce2bb0.PNG)

**Comment by Binaryify** [comment]
oh, I see that in my vscode insider
![image](https://user-images.githubusercontent.com/12221718/81768292-2e2c7380-950d-11ea-8d9c-e8321f87774c.png)
will trying fixed that

**Comment by w-xy** [comment]
thank you

**Comment by Binaryify** [comment]
just fixed this in v3.6.1

**Comment by w-xy** [comment]
Thanks. It's fine now in my personal machine. I'll check it tomorrow.

**Comment by Gytobp** [comment]
Hi, it seems that the same problem happens again. All kinds of variable in C are coral now. 

This can be reproduced on both Windows 10 and Ubuntu 16.04 with the only other extension C/C++ by Microsoft.

![image](https://user-images.githubusercontent.com/62336349/143291514-9e511149-9f51-494d-8bef-2282fa05ee99.png)

Local variables are light white only if C/C++ extension is disabled.

**Comment by Binaryify** [comment]
@Gytobp will fix that soon

**Comment by Binaryify** [comment]
@Gytobp you can check v3.12.3

**Comment by e-potashkin** [comment]
In C#, all variables also are set red. Could you please change it too? =)

**Comment by Binaryify** [comment]
@e-potashkin ok

**Comment by MoonChasing** [comment]
@Binaryify Hello，I am accustomed to the coral color of the variables in the C language. Now it was fixed as a bug. I am very uncomfortable. Can you make this an option?

**Comment by Binaryify** [comment]
@MoonChasing 
you can add this in your settings.json
```
 "editor.semanticTokenColorCustomizations": {
    "rules": {
      "variable:c": {
        "foreground": "#e06c75"
      },
      "variable:cpp": {
        "foreground": "#e06c75"
      },
      "variable:cs": {
        "foreground": "#e06c75"
      }
    }
  },
```

**Comment by MoonChasing** [comment]
@Binaryify Thank you very much.

**Comment by tristan957** [comment]
Initially it was a jarring change. Wondering what Atom One Dark Pro does in this situation. It was kind of nice to be able to see the parameters at a glance easily. Don't really care enough to stray from the default behavior however.

**Comment by Binaryify** [comment]
discuss link
https://github.com/Binaryify/OneDark-Pro/discussions

**Comment by BenJSouthwell** [comment]
It should be consistent with the original implementation of the theme. They should be grey. If red is preferred by some it could be a potential option. But if you are to make a clone of a colour theme then you should be consistent with it, otherwise what is the point ?

**Comment by Andreasgdp** [comment]
If you just want to keep using the defaults of one dark pro but still use the c/c++ extension, you can set the following extension setting:

`"C_Cpp.enhancedColorization": "disabled"`
