### ISSUE TITLE
Only enable markdown style when using the One Dark Pro theme

### ISSUE THREAD

**Issue by mjbvz** [Binaryify/OneDark-Pro#391]
**Repro**
1. Install this extension
1. Switch the builtin VS Code light+ theme
1. Open a markdown preview

**Bug**
This extensions's markdown styles are still enabled. This makes light themes very low contrast:

<img width="1311" alt="Screen Shot 2020-05-11 at 2 11 12 PM" src="https://user-images.githubusercontent.com/12821956/81612193-47101a00-9391-11ea-90f0-255bd7854d01.png">

**Comment by Binaryify** [comment]
still trying how to limit that

**Comment by Binaryify** [comment]
just release a new version and limit only active in dark theme, still need to find a way to limit in this theme

**Comment by jcolsen** [comment]
The issue still persists with v3.5.5

**Comment by Binaryify** [comment]
@jcolsen check v3.6.0, i just revert that change

**Comment by jcolsen** [comment]
> @jcolsen check v3.6.0, i just revert that change

It's not available for me yet inside of VSCode, but I'll keep an eye out for it, thanks :D
