### ISSUE TITLE
Improve rust semantic highlighting

### ISSUE THREAD

**Issue by JMS55** [Binaryify/OneDark-Pro#393]
Notable issues:
1. CONSTANTS should have a different color from types (Maybe orange, like numbers?)
2. Enum::Variant (the Variant part) should have a different color from variables (maybe leave it red?)
3. Local variables should not be red. Please change them to white/grey. Maybe make the existing `{}, [], =>, ::` white/grey stuff a darker shade as well?

See also [rust-analyzer's semantic tokens.](https://github.com/georgewfraser/rust-analyzer/blob/57c52bd39732bb910f3e0cb3b39acbf8ef8f5d69/editors/code/package.json#L542-L629) (I'm unsure if this is useful to you or not, but I think this is where rust adds its extra stuff)

Dark+
![image](https://user-images.githubusercontent.com/47158642/82235019-2fd8ab80-9900-11ea-99d0-b5bcccba2609.png)
One Dark Pro
![image](https://user-images.githubusercontent.com/47158642/82235039-36672300-9900-11ea-9aa4-cc62b75bfe3b.png)

**Comment by Binaryify** [comment]
could you provide the code in your screenshot

**Comment by JMS55** [comment]
The code is here https://github.com/JMS55/sandbox, in src/sandbox.rs, line 35.

**Comment by Binaryify** [comment]
how about this
![image](https://user-images.githubusercontent.com/12221718/82422296-da91cb00-9ab4-11ea-9780-a3bc8885b7d7.png)

**Comment by JMS55** [comment]
Looks good!

**Comment by Binaryify** [comment]
just publish a new version, you can check it later
