### ISSUE TITLE
C Highlighting seems incorrect

### ISSUE THREAD

**Issue by cyphernull** [Binaryify/OneDark-Pro#395]
![image](https://user-images.githubusercontent.com/23122353/82472706-2e270780-9afb-11ea-9f34-c600e9fbe5e3.png)

According to the theme definition. I thought that the variables should be colored as red ? and NULL should not be colored the same as functions;

**Comment by Binaryify** [comment]
could you provide the code in your screenshot

**Comment by cyphernull** [comment]
```
#include <stdio.h>
#include <stdlib.h>

typedef struct ListNode {
  int val;
  struct ListNode *next;
} ListNode;

struct ListNode *addTwoNumbers(struct ListNode *l1, struct ListNode *l2) {
  ListNode *r = NULL;
  ListNode *p = NULL;
  r = (ListNode *)malloc(sizeof(ListNode));
  p = r;
  int carry = 0;

  if (l1 == NULL && l2 == NULL) {
    return r;
  }

  if (l1 == NULL && l2 != NULL) {
    return l2;
  }

  if (l1 != NULL && l2 == NULL) {
    return l1;
  }

  while (l1 != NULL || l2 != NULL || carry != 0) {
    int sum = (l1 != NULL ? l1->val : 0) + (l2 != NULL ? l2->val : 0) + carry;
    if (sum > 9) {
      sum = sum % 10;
      carry = 1;
    } else {
      carry = 0;
    }
    p->val = sum;
    l1 = l1 ? l1->next : NULL;
    l2 = l2 ? l2->next : NULL;
    if (l1 != NULL || l2 != NULL || carry != 0) {
      p->next = (ListNode *)malloc(sizeof(ListNode));
      p = p->next;
    } else {
      p->next = NULL;
    }
  }

  return r;
}

int main(void) {
  ListNode *result = NULL;
  result = (ListNode *)malloc(sizeof(ListNode));
  ListNode *l1 = NULL;
  l1 = (ListNode *)malloc(sizeof(ListNode));
  l1->val = 0;
  // l1->next = (ListNode *) malloc(sizeof(ListNode));
  // l1->next->val = 4;
  // l1->next->next = (ListNode *) malloc(sizeof(ListNode));
  // l1->next->next->val = 3;

  ListNode *l2 = NULL;
  l2 = (ListNode *)malloc(sizeof(ListNode));
  l2->val = 5;
  // l2->next = (ListNode *) malloc(sizeof(ListNode));
  // l2->next->val = 6;
  // l2->next->next = (ListNode *) malloc(sizeof(ListNode));
  // l2->next->next->val = 4;
  // l2->next->next->next = (ListNode *) malloc(sizeof(ListNode));
  // l2->next->next->next->val = 1;

  // while (l1 != NULL) {
  //   printf("%d\n",l1->val);
  //   l1 = l1->next;
  // }

  // while (l2 != NULL) {
  //   printf("%d\n",l2->val);
  //   l2 = l2->next;
  // }

  result = addTwoNumbers(l1, l2);

  while (result != NULL) {
    printf("%d", result->val);
    if (result->next != NULL) {
      printf("->");
    }
    result = result->next;
  }

  return 0;
}
```

**Comment by Binaryify** [comment]
had you installed some extensions about C?
![image](https://user-images.githubusercontent.com/12221718/82545903-e4d1c900-9b89-11ea-8443-d7042770a7a7.png)

**Comment by cyphernull** [comment]
The Microsoft C/C++ extension;
![image](https://user-images.githubusercontent.com/23122353/82556896-39cb0a80-9b9d-11ea-8550-8032b1243a7b.png)

**Comment by Binaryify** [comment]
I can't reproduce it, did I miss something?
![image](https://user-images.githubusercontent.com/12221718/82574306-77d62780-9bb9-11ea-81be-ebf9ea631d05.png)

**Comment by cyphernull** [comment]
Does the OS make a difference? i‘m on Mac. And when I uninstalled the C/C++ extension, I got what you have above.

**Comment by Binaryify** [comment]
it reproduced on my mbp, will fixed that soon

**Comment by Binaryify** [comment]
it look like c/c++ extension issue
![image](https://user-images.githubusercontent.com/12221718/82632046-bc99a700-9c29-11ea-8721-112ce208cd8f.png)
![image](https://user-images.githubusercontent.com/12221718/82632057-c58a7880-9c29-11ea-9b76-7a6bd8e2cd31.png)
![image](https://user-images.githubusercontent.com/12221718/82632059-c7ecd280-9c29-11ea-9f58-d4ab1d0aff4d.png)
you could create a issue to https://github.com/microsoft/vscode-cpptools/issues
and set `"C_Cpp.enhancedColorization": "Disabled"` in your setting.json

**Comment by Z4RX** [comment]
@Binaryify [C/C++](https://github.com/Microsoft/vscode-cpptools) change tokens, [here](https://code.visualstudio.com/docs/cpp/colorization-cpp) is an article about it
