### ISSUE TITLE
Problem with markdown review

### ISSUE THREAD

**Issue by ugurcan-sonmez-95** [Binaryify/OneDark-Pro#398]
Hello. I use the "One Dark Pro" theme. I also use an extension named "Markdown Preview Github Styling". There was no problem until the last update of One Dark Pro. Now, when I use the markdown preview, the background turns dark instead of white and writings look untidy. I think there is a bug with markdown after the last update. I hope this problem can be fixed soon.

**Comment by Binaryify** [comment]
you can use v3.7.1 until this problem fixed

**Comment by ugurcan-sonmez-95** [comment]
> you can use v3.7.1 until this problem fixed

Thank you for answering.

**Comment by Binaryify** [comment]
still finding the way to add a toggle that, may take some days, markdown webview have some limit

**Comment by ugurcan-sonmez-95** [comment]
> still finding the way to add a toggle that, may take some days, markdown webview have some limit

No problem. I just wanted to make you informed about it. I will use v3.7.1 until it is fixed. :)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/84563307-1571e080-ad8d-11ea-9112-c3d3f61273e4.png)
![image](https://user-images.githubusercontent.com/12221718/84563313-1d318500-ad8d-11ea-81ff-e721ada0090d.png)
now you can toggle that in the vscode setting now

**Comment by ugurcan-sonmez-95** [comment]
I checked it and there is no problem with markdown anymore. Thank you for helping. :)
