### ISSUE TITLE
Remove underline and add color highlighting for links/url in markdown for better readability.

### ISSUE THREAD

**Issue by JerryGoyal** [Binaryify/OneDark-Pro#399]
How to enable syntax color highlighting and remove underline for links present in MD files?

Currently links and normal text both have same color. By removing underlines from links and changing its color will make it easier to spot and read.

![image](https://user-images.githubusercontent.com/7106086/84572896-c5117780-adba-11ea-8af4-ae236083a678.png)

something like this sublime highlighting:

![image](https://user-images.githubusercontent.com/7106086/84572919-fab66080-adba-11ea-9aa2-1f82ecb11d1e.png)

I inspected and found both have same scope so couldn't write any tokenColorCustomizations for links.

![image](https://user-images.githubusercontent.com/7106086/84572861-91cee880-adba-11ea-8d0a-0525b6983032.png)

**Comment by Binaryify** [comment]
can't change that cause the same scope

**Comment by JerryGoyal** [comment]
oh that's bad. I think I should raise an issue in vscode then.
