### ISSUE TITLE
Add credit to official Material Theme for Visual Studio Code

### ISSUE THREAD

**Issue by equinusocio** [Binaryify/OneDark-Pro#40]
You have to add credits to the official [Material Theme](https://github.com/equinusocio/vsc-material-theme) and specify that this is a unofficial porting of the original one. Open source doesn't mean "Grab works done by others and publish them with your name" ;)

**Comment by Binaryify** [comment]
Thanks for your notice
In fact it from 'One Dark theme' of Atom, no from 'Material Theme'
Will rename 'One Dark Pro'
