### ISSUE TITLE
Optimize color for panelSectionHeader.background

### ISSUE THREAD

**Issue by EHBaozi** [Binaryify/OneDark-Pro#400]
Recent versions of VSCode allows having sections in the side panel. By default the panel headers have a semi-transparent background, which doesn't really blend in with the rest of the theme, as shown here:

![image](https://user-images.githubusercontent.com/38034505/85075469-25872700-b1b6-11ea-9f15-508050bcf80e.png)

I don't know which color is the best. Maybe `#21252b`?

**Comment by Binaryify** [comment]
just release a new version, you can check it now

**Comment by EHBaozi** [comment]
Thanks!
