### ISSUE TITLE
Data types color problems in ruby

### ISSUE THREAD

**Issue by Z4RX** [Binaryify/OneDark-Pro#405]
Hello. There is a problem with ruby data types colorization. this example will show situaation:
![rb_colors_issue](https://user-images.githubusercontent.com/58516282/85652117-7913dc00-b6b2-11ea-85ea-8cd283e31ca8.png)
And an example from gruvbox-material
![rb](https://user-images.githubusercontent.com/58516282/85652207-b5473c80-b6b2-11ea-8532-e92f5ebda39b.png)
Source code:
`  def case_archiver(value)
    arch = ArchiveCase.new
    arch.id = value.id
    arch.client_id = value.client_id
    arch.gov_id = value.gov_id
    arch.category = value.category
    arch.side = value.side
    arch.opponent = value.opponent
    arch.category = value.category
    arch.judge = value.judge
    arch.description = value.description
    arch.start = value.start
    arch.end = value.end
    arch.status = value.status
    arch.bonus = value.bonus
    arch.sum = value.sum
    arch.save
  end`

**Comment by Binaryify** [comment]
I think that might vscode problem, you could create a issue in vscode' repo

**Comment by Z4RX** [comment]
Ok, thx!
