### ISSUE TITLE
*.ipynb doesn't look well when connected to remote server

### ISSUE THREAD

**Issue by 3288103265** [Binaryify/OneDark-Pro#406]
I like the style of one dark pro, but when I connect vscode to remote server, the style of *.ipynb is not as cool as shown in localhost. This difference make me uneasy :).
Remote *.ipynb file style:
![image](https://user-images.githubusercontent.com/34595906/86802109-405b0600-c0a7-11ea-9d76-6e0bc7862ef8.png)
Local *.ipynb file style:
![image](https://user-images.githubusercontent.com/34595906/86802015-2e796300-c0a7-11ea-95e0-c98fd7c678a7.png)

**Comment by Binaryify** [comment]
you should install this theme in remote vscode
