### ISSUE TITLE
displayName and label mismatch

### ISSUE THREAD

**Issue by Windos** [Binaryify/OneDark-Pro#41]
Given the recent name change I went to update my settings.json, and given that this installs with the display name "OneDark Pro" I naturally entered `"workbench.colorTheme": "OneDark Pro"`.

Unfortunately the display name and label for this theme doesn't currently match, and it wasn't until I used the command palette to activate the theme that I realised I actually needed to enter "One Dark pro"

From a users' perspective it would be great seeing these be the same to avoid confusion.

**Comment by Binaryify** [comment]
I improve it, thank for your advice ~
