### ISSUE TITLE
extension on VScode crashes

### ISSUE THREAD

**Issue by DeeliN-uno** [Binaryify/OneDark-Pro#411]
Today, VScode keeps prompting "Extension Host Terminated unexpectedly", and when I check the log, something went wrong when loading files for this extension. So I disables it, and reload Window, VScode works fine.

Then I want to reload this extension, but nothing happens the theme doesn't change.

Maybe the newest version has got a bug?

**Comment by Binaryify** [comment]
What operating system are you using

**Comment by DeeliN-uno** [comment]
Wierd, I reinstalled OneDark-Pro today, and now it works fine. I use Win10 1909

**Comment by DeeliN-uno** [comment]
There is something wrong with my network, and another "code time" extension seems to keep requesting net connection, after disable it, everything is fine now
