### ISSUE TITLE
JavaScript "console.log" highlighting incorrect

### ISSUE THREAD

**Issue by wgumenyuk** [Binaryify/OneDark-Pro#414]
How it currently is:
![1](https://user-images.githubusercontent.com/50965068/90515470-ffa0e300-e162-11ea-9bb0-32f1eb99d71f.PNG)

How it should be:
![2](https://user-images.githubusercontent.com/50965068/90515493-092a4b00-e163-11ea-88cc-f4233342ab58.PNG)

**Additional information**
- Semantic highlighting is disabled
- No JavaScript highlighting extentions installed
- Still occurs with all extenstions disabled

Is anyone else experiencing this?

**Comment by tmurph21** [comment]
Same issue here.

Changing the settings to `"editor.semanticHighlighting.enabled": "configuredByTheme"` or `true` makes it worse.

**Comment by SymonBlazejczakPXL** [comment]
I'm on 1.48.1. But now that I think about it, you probably have an extension that's messing with the JS syntax-highlighting. Try disabling / removing some. Let us know if you got it fixed.

**Comment by symonxdd** [comment]
I'm on 1.48.1. But now that I think about it, you probably have an extension that's messing with the JS syntax-highlighting. Try disabling / removing some. Let us know if you got it fixed.

**Comment by zyzski** [comment]
experiencing the same, even with this being the only module enabled. very similar to what happened when they added semantic highlighting

**Comment by wgumenyuk** [comment]
@symonxdd Even after a complete reinstall of VS Code (version 1.48.1) the issue still occurs. The only extenstion installed is this theme.

**Comment by symonxdd** [comment]
@wgumenyuk Can I ask where u got this screenshot from?
![image](https://user-images.githubusercontent.com/45405238/91179820-4d7b9500-e6e7-11ea-9dd2-ce1f698ba81d.png)

**Comment by wgumenyuk** [comment]
@symonxdd For this screenshot I activated semantic highlighting in the settings. This doesn't fix my issue though, as enabling this feature messes up many other highlights.

**Comment by symonxdd** [comment]
Could you give more examples of wrong highlights?

**Comment by wgumenyuk** [comment]
You can activate semantic highlighting by either opening VS Code's settings (File -> Preferences -> Settings) or changing `editor.semanticHighlighting.enabled` inside `settings.json` to `true`.

This then leads to broken syntax highlighting mentioned here:
- [TypeScript / JavaScript syntax highlighting changes after a few seconds](https://github.com/microsoft/vscode/issues/92308)
- [February 2020 update broke typescript and javascript syntax](https://github.com/dracula/visual-studio-code/issues/132)
   - This [comment](https://github.com/dracula/visual-studio-code/issues/132#issuecomment-597319290) mentions the broken highlighting of `console.log` as well

Semantic highlighting seems to be working inconsistent.
Please remember, that I don't use this feature normally and highlighting is still broken for me and the other participants regardless.

**Comment by symonxdd** [comment]
Thanks for clarifying the matter. I noticed that when opening vscode and navigating to a JS file I got the same problem as you, but not for long. It got fixed after a fraction of a second after showing the following message at the bottom of vscode:

> Initializing JS/TS language features

So I looked for an extension with that name and found following enabled, built-in extensions:

- **TypeScript and JavaScript Language Features** &
- **TypeScript Language Basics**

Can you make sure you have those installed and enabled?
It's easy to find by open the extensions sidebar and searching for **@builtin type** (with a small b!)
![image](https://user-images.githubusercontent.com/45405238/91239474-e0481e00-e73f-11ea-843f-98f89536a1b5.png)

**Comment by wgumenyuk** [comment]
Yes, I have both extensions enabled, and see a `Initializing JS/TS language features` notification on startup as well.

**Comment by symonxdd** [comment]
Strange. What you could try next is uninstalling vscode with a program like IObit Uninstaller. Which deletes all the residual files as well, if that doesn't help, re-installing your OS will probably do the job 😂

**Comment by wgumenyuk** [comment]
Haha, thanks for your help. I'll take a look at it tomorrow. :)

**Comment by symonxdd** [comment]
Did you get it fixed? If not, since when does it not work? From the beginning?

**Comment by wgumenyuk** [comment]
This issue seems to have occured in one of the latest updates. Out of curiosity I installed VS Code on my Ubuntu (20.04.1) PC and the highlighting is still bugged, even with the same settings. I assume this is some bug with VS Code, since other themes also have the same highlighting error.

**Comment by symonxdd** [comment]
Alright! Hopefully it's fixed fast.

**Comment by wgumenyuk** [comment]
Let's hope so! I'm going to close this issue, thank you very much for your help. :)
