### ISSUE TITLE
Question: custom colors

### ISSUE THREAD

**Issue by skotturi** [Binaryify/OneDark-Pro#43]
In Javascript, I'd like my local variables (declared with `let const var`) to be a different color than function parameters. I've looked through the .tmTheme source and am not exactly sure what I'm looking for. 

```
function(foo) {
   var bar = 'local variable';
   console.log(foo + bar);        // where foo & bar would be different colors, say bar is default red, and foo is maybe purple or something..
}
```

is it possible to override with some custom settings for this kind of thing or would I need to fork, change & install?

**Comment by skotturi** [comment]
Seems like a related request: https://github.com/Microsoft/vscode/issues/11556

Perhaps its not possible atm?

**Comment by Binaryify** [comment]
You can see https://binaryify.github.io/OneDark-Pro/#/?id=design

**Comment by Binaryify** [comment]
The 'foo' and the 'bar' has the same scope, so they can't has different color
![image](https://cloud.githubusercontent.com/assets/12221718/25731965/90b43b6a-317d-11e7-9a57-2c5969881eca.png)
![image](https://cloud.githubusercontent.com/assets/12221718/25731968/97a20b0a-317d-11e7-9e3e-3066303d4baa.png)

**Comment by skotturi** [comment]
Damn, this was suppose useful in WebStorm. Thanks for helping me understand the underlying constraint!

**Comment by jens1o** [comment]
You should ask in vscode's repository and ask wether they can improve the grammar, so it matches your case.
