### ISSUE TITLE
Markdown TODO display effect is not prominent

### ISSUE THREAD

**Issue by liuzhihangs** [Binaryify/OneDark-Pro#451]
```text
- [ ] Test
  - [ ] Test
- [x] Test
  - [x] Test

```
The left side is the current one, and the right side is the desired effect. 

Because the effect displayed now does not look very clear.

![image](https://user-images.githubusercontent.com/26057042/94237728-ddf50180-ff41-11ea-89b0-f7f0561b6d04.png)

**Comment by Binaryify** [comment]
which extension are you using

**Comment by liuzhihangs** [comment]
> which extension are you using

Markdown Preview Enhanced

@Binaryify

**Comment by Binaryify** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/12221718/94513477-5b29ba80-0251-11eb-9bbc-a34f049d796f.png)

**Comment by liuzhihangs** [comment]
@Binaryify 

Set the theme to one-dark

![image](https://user-images.githubusercontent.com/26057042/94514434-c07eab00-0253-11eb-9fa3-364185e7fbbc.png)

**Comment by Binaryify** [comment]
try cancel this
![image](https://user-images.githubusercontent.com/12221718/94529306-2840f000-026c-11eb-9767-6e0e01ffaa44.png)

**Comment by liuzhihangs** [comment]
@Binaryify 

What I mean is that OneDarkPro's markdown style is not very prominent for TODO display, and it is not intended to be cancelled.

**Comment by Binaryify** [comment]
still can't reproduce
![image](https://user-images.githubusercontent.com/12221718/94564237-59d0b000-029a-11eb-8f81-ef2492de24d0.png)
