### ISSUE TITLE
How to change python function-calls to italics

### ISSUE THREAD

**Issue by AndrewLaganaro** [Binaryify/OneDark-Pro#457]
I'm trying to change the python function declaration, the "def" into italics on this Vscode theme.
Currently the theme italics the keywords "import" and all the flow control keywords "if, else, return, continue" etc.

To try to get the functions also in italics I tried to use the
"keyword.declaration.function.python", however it is not working using this.
Does anyone know how to get around this?
I found some reference about the keyword namings on this site: https://www.sublimetext.com/docs/3/scope_naming.html
but even that didn't seem to help, as it still doesn't works at all.

I only have basic knowledge of CSS and I don't know if I'm going the right way to change this. I've tried a bunch of combinations and surely I Am doing something wrong...
![image](https://user-images.githubusercontent.com/45211616/94860481-80165d00-040c-11eb-90d1-6233272ddcfc.png)

I've created this one hoping it would work. It also didn't
![image](https://user-images.githubusercontent.com/45211616/94860542-991f0e00-040c-11eb-9395-b836cd8ae2b3.png)

![image](https://user-images.githubusercontent.com/45211616/94861138-6a556780-040d-11eb-9b88-54b4e334ca16.png)

Thanks in advance.

**Comment by Binaryify** [comment]
please read https://binaryify.github.io/OneDark-Pro/#/

**Comment by AndrewLaganaro** [comment]
Thanks, It totally Works!

I didn't know there was this page about the theme. So thanks for pointing It out!

**Comment by Binaryify** [comment]
glad to help you
