### ISSUE TITLE
Elixir highlighting change (adjust for ElixirLS fix)

### ISSUE THREAD

**Issue by matthew-myers-bose** [Binaryify/OneDark-Pro#464]
Hi, I just have a minor syntax highlighting change request.

I use the ElixirLS vscode extension for Elixir support. And they just fixed some highlighting:
> ElixirLS - v0.6.0: 3 October 2020
Highlight atoms as `constant.language.symbol.elixir` instead of `constant.other.symbol.elixir` (thanks Omri Gabay) [#142](https://github.com/elixir-lsp/vscode-elixir-ls/pull/142)

This ElixirLS change makes atoms show up as orange, rather than the light-cyan-ish color of operators that they were before.
I found your instructions to customize with `editor.tokenColorCustomizations`, (thanks) so it's OK for me right now, but it would be nice to have the default for Elixir look like it used to.

Here's my customization, in case it helps at all. I think #56B6C2 is the color that atoms used to be.

```json
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
        "textMateRules": [
            {
                "scope": [
                    "constant.language.symbol.elixir"
                ],
                "settings": {
                    "foreground": "#56B6C2"
                }
            }
        ]
    }
}
```

**Comment by Binaryify** [comment]
could you provide some code to show how it will change

**Comment by matthew-myers-bose** [comment]
![image](https://user-images.githubusercontent.com/56367938/95241778-81100b80-07cb-11eb-9a35-67d222da3cd2.png)

example code:
```elixir
defmodule Device do
  defstruct [:id, :type, :configuration]

  def copy_device(%Device{id: nil}) do
    {:error, "cannot copy invalid device"}
  end

  def copy_device(%Device{id: id} = device) do
    new_device = %Device{device | id: UUID.uuid4(), type: nil}

    result = %{status: :ok, is_copy: true, num_copies: 0}

    {:ok, new_device, result}
  end
end

```

**Comment by Binaryify** [comment]
I just release a new version, you can check if it work fine now

**Comment by matthew-myers-bose** [comment]
Works great! That was a fast response, thanks!
