### ISSUE TITLE
Terminal text is hard to read

### ISSUE THREAD

**Issue by novachief101** [Binaryify/OneDark-Pro#469]
The in-built VSCode terminal text colour is grey, (just to the point of slightly annoying) hard to read and similar to comments. Here is an image-

**One Dark Pro-**
![Screenshot (203)](https://user-images.githubusercontent.com/65995389/95607480-695daf00-0a79-11eb-8953-7ce7265b5136.png)
**Defaut VSCode theme-**
![Screenshot (204)](https://user-images.githubusercontent.com/65995389/95607500-7084bd00-0a79-11eb-8936-ed3d16859dad.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/95649671-4383e900-0b11-11eb-962e-443e34aa14c2.png)
it work fine in Mac
you can add this in your setting.json
```
"workbench.colorCustomizations": {
      "terminal.foreground": "#FFF",
},
```

**Comment by novachief101** [comment]
Thank you very much, no VSCode extension could be better than this!
