### ISSUE TITLE
How to set the variable color

### ISSUE THREAD

**Issue by stonedreamforest** [Binaryify/OneDark-Pro#47]
![1](https://cloud.githubusercontent.com/assets/16742566/25796055/a7e009f6-340a-11e7-9dc8-ead6a06016dd.png)

**Comment by Binaryify** [comment]
You  can see this DOCS https://binaryify.github.io/OneDark-Pro/#/?id=design

**Comment by stonedreamforest** [comment]
I can't find it

**Comment by Binaryify** [comment]
@stonedreamforest 
Python 的高亮不好处理,目前 vscode 对 python 支持的不是很好,变量和其他语法的 scoped 是相同的,会造成改了一处又影响全部,所以暂时不让 python 有更多的高亮

**Comment by stonedreamforest** [comment]
我想把变量部分颜色调暗， 这个其它语言好像都是一样的

**Comment by Binaryify** [comment]
@stonedreamforest 
你看下变量的作用域是什么,然后改下颜色就行
