### ISSUE TITLE
Incorrect highlighting of override and final C++ modifiers if both are used

### ISSUE THREAD

**Issue by r44083** [Binaryify/OneDark-Pro#472]
If both modifiers are used in a row, only the last of them is highlighted:

Only ```final``` is highlighted:
![image](https://user-images.githubusercontent.com/13915612/95676219-2e689200-0bc5-11eb-81db-f1baf180c320.png)
Only ```override``` is highlighted:
![image](https://user-images.githubusercontent.com/13915612/95676252-4b04ca00-0bc5-11eb-8bcb-0d3663983933.png)

Expected result: both modifiers should be highlighted.

**Comment by Binaryify** [comment]
it might be vscode's c++ extensions issues, other themes have same problem

**Comment by r44083** [comment]
I agree. I created separate issue to C/C++ extension project: https://github.com/microsoft/vscode-cpptools/issues/6345.
