### ISSUE TITLE
Operator Mono Italic Support?

### ISSUE THREAD

**Issue by brentluna** [Binaryify/OneDark-Pro#48]
Any chance to add support for italics on keywords and the like, similar to Dracula and Panda Syntax Themes?

Thanks and keep up the good work!

**Comment by Binaryify** [comment]
Can you provide some screenshot ?

**Comment by brentluna** [comment]
![screen shot 2017-05-09 at 10 58 09 am](https://cloud.githubusercontent.com/assets/7967287/25865077/8ee0c192-34a6-11e7-843c-55ec7caaec3d.png)
![screen shot 2017-05-09 at 10 57 47 am](https://cloud.githubusercontent.com/assets/7967287/25865078/8ee49d8a-34a6-11e7-9c3e-9c7f81058e64.png)

Here are the repos for those screenshots. I think Panda goes a bit overboard by italicizing  a bit too much, while Dracula could probably add a few more keywords to what is italic. 

https://github.com/tinkertrain/panda-syntax-vscode
https://github.com/dracula/visual-studio-code

**Comment by will-stone** [comment]
This request isn't really in line with Atom's One Dark theme, and may not be in favour of those that have come here in search of that.
@brentluna I'd suggest forking this theme if you'd like a variation of it.

**Comment by Binaryify** [comment]
@brentluna 
You can see this REPO
https://github.com/tonsky/FiraCode/wiki
I cry `brew tap caskroom/fonts` and `brew cask install font-fira-code`
and change `setting.json` like this
```
"editor.fontFamily": "Fira Code",
"editor.fontLigatures": true,
```
![image](https://cloud.githubusercontent.com/assets/12221718/25928745/7576ff9c-3630-11e7-8350-d36dfead8ad1.png)
and the result like this
![image](https://cloud.githubusercontent.com/assets/12221718/25928829/e826b50a-3630-11e7-854c-8aafe80fc4fa.png)

**Comment by DenisValcke** [comment]
I see this one is closed but I tried it and there are no italic keywords in both HTML or JS files.
Does this mean this is not going to get supported in this theme?
In "An Old Hope with italics":
<img width="228" alt="schermafbeelding 2017-05-18 om 12 41 56" src="https://cloud.githubusercontent.com/assets/12268407/26198728/7cdd1612-3bc7-11e7-812f-7330ea57abfb.png">

In One Dark Pro:
<img width="163" alt="schermafbeelding 2017-05-18 om 12 42 15" src="https://cloud.githubusercontent.com/assets/12268407/26198729/7ce3c91c-3bc7-11e7-9091-eab5e29e561d.png">

If this feature might come to this theme that would be awesome as it really increases legibility imo.

**Comment by Binaryify** [comment]
Oh I misunderstand you mean

**Comment by Binaryify** [comment]
Will add this feature

**Comment by jens1o** [comment]
well, I'm fine with the current situation :/

**Comment by Binaryify** [comment]
Will look like this
![image](https://cloud.githubusercontent.com/assets/12221718/26291928/957ef724-3ee4-11e7-9e3a-7357d6e7d160.png)

**Comment by jens1o** [comment]
Okay, I'm fine with it.

**Comment by Binaryify** [comment]
Done

**Comment by rafaelpimpa** [comment]
Any way to disable it?

**Comment by jens1o** [comment]
Well, unfortunately no. Maybe @Binaryify wants to create 2 versions of this(Extensions can ship more than one theme) whereas one is with italic and one isn't?

**Comment by Binaryify** [comment]
@rafaelpimpa 
You can see this
https://github.com/Binaryify/OneDark-Pro/issues/70
