### ISSUE TITLE
Syntax colour highlighting a pointer to a pointer in Go(lang) is off.

### ISSUE THREAD

**Issue by irisida** [Binaryify/OneDark-Pro#482]
To me the syntax highlighting is buggy in Go when you have a pointer to a pointer. I would expect the double dereferencing operator to share the same syntax highlighting colour. 

**To Reproduce**
1. install the extension
2. create a pointer to a pointer (as per attachment)

**Expected behavior**
Double dereferencing operator has unified syntax colour highlighting

**Screenshots & Example Code**
<img width="609" alt="Screenshot 2020-11-15 at 00 04 06" src="https://user-images.githubusercontent.com/20445648/99159689-b8c97780-26d6-11eb-91dc-acff3a078d71.png">

**Desktop (please complete the following information):**
 - OS: Mac [10.15.7]
 - VSCODE Version  [1.51.1]
 - Theme version [3.9.3]

**Additional context**
N/A

**Comment by Binaryify** [comment]
could you provide the code in your screenshot?

**Comment by irisida** [comment]
sure, apologies for not initially. 

`package main

import "fmt"

func main() {

	p := fmt.Printf

	val := 100.0
	p1 := &val

	pp1 := &p1

	p("Type: %T Address: %p Value: %v\n", val, &val, val)
	p("Type: %T Address: %p Value: %v\n", p1, &p1, *p1)
	p("Type: %T Address: %p Value: %v\n", pp1, &pp1, *pp1)

	**pp1 = 500.

	p("Type: %T Address: %p Value: %v\n", val, &val, val)
	p("Type: %T Address: %p Value: %v\n", p1, &p1, *p1)
	p("Type: %T Address: %p Value: %v\n", pp1, &pp1, *pp1)
}
`

**Comment by tristan957** [comment]
Hi @irisida and @Binaryify,

I am coming from https://github.com/jeff-hykin/better-go-syntax/issues/15. I believe this is a syntax issue if you look at the Textmate scopes. That repo is the VSCode upstream syntax repo for Go I believe. I think the One Dark Pro theme is not doing anything wrong here, and is only responding to what the syntax is telling it.

**Comment by Binaryify** [comment]
@tristan957 thank for the feedback

@irisida  you could follow this issue https://github.com/jeff-hykin/better-go-syntax/issues/15

**Comment by irisida** [comment]
Thanks for your reply. However, just for context....

The same code on other "one dark" alike themes, (atom, vivid etc) all handle the syntax highlighting as would be expected. As does most other installed themes, radical, synthwave84 etc... Of about 8-10 installed themes one dark pro is the only one to highlight the syntax in this manner.

**Comment by Binaryify** [comment]
@irisida oh, I just check that, and it's indeed a bug

**Comment by Binaryify** [comment]
is this right
![image](https://user-images.githubusercontent.com/12221718/99239837-977f9d00-2836-11eb-9d69-0ce3271d69dd.png)
@irisida

**Comment by irisida** [comment]
@Binaryify yes, that's the one.

**Comment by Binaryify** [comment]
just released a new version，you can check it now

**Comment by irisida** [comment]
Got it. Thank you! much appreciated. 
 
<img width="551" alt="Screenshot 2020-11-16 at 11 02 00" src="https://user-images.githubusercontent.com/20445648/99245304-443c2900-27fb-11eb-8ee6-7d17ea1ff96a.png">

**Comment by irisida** [comment]
moving to close issue

**Comment by irisida** [comment]
resolved. Many thanks. Corrected on 3.9.6

**Comment by tristan957** [comment]
Oh good to know that's it's a bug in both places.
