### ISSUE TITLE
Active linenumber colour highlighting property - and vim relative numbering highlights

### ISSUE THREAD

**Issue by irisida** [Binaryify/OneDark-Pro#487]
**Describe what you want**
I would like to have the ability to use/set the `"editorLineNumber.activeForeground": "#fffff"` property. This would be exceptionally useful for vim mode users with relative line numbering which is a key part of the workflow for many. 

The expected outcome would be that the current line and highlighting of the theme allows for default or user-selected highlight colour that differentiates from the other lines of the file and their respective line numbering.

**Additional context**
attached a screenshot showing the relative numbering setup and hopefully, it demonstrates why the highlighting would be useful. 

An even further incredible addition/extension to above would be to be able to highlight the tenth line either side with a different colour too. Or all multiples of ten thereafter, as an additional visual/cognitive easing. But it's probably most useful to people with a relative line numbering setup so may not be as mainstream as the first part of the request for the current line number highlight. 
![onedarkprolines](https://user-images.githubusercontent.com/20445648/99918640-57298e80-2d10-11eb-8a48-d692da5f8c37.png)

**Comment by r44083** [comment]
Looks like this commit cause the following line number coloring:

![Screenshot at 2020-11-25 10:20:43](https://user-images.githubusercontent.com/13915612/100200921-fe244b00-2f07-11eb-8f8f-f9cd9855795f.png)

I think that such coloring doesn't very fit for OneDarkPro theme, does it?

**Comment by solusmax** [comment]
#fffff instead of #fffff**f**

![image](https://user-images.githubusercontent.com/66680032/100202013-cc17e680-2f11-11eb-8612-3c202359763d.png)

**Comment by Binaryify** [comment]
will fix it soon~

**Comment by irisida** [comment]
Thanks. Not a deal-breaker at all, but it's a very useful addition for that mode/workflow. 

Much appreciated.

**Comment by solusmax** [comment]
The selected color is too bright and distracting:

![image](https://user-images.githubusercontent.com/66680032/100206349-4434db00-2f17-11eb-8a51-64a4cd601ffb.png)

I'll fix it in my User Settings, but I still think you should have used something like `#abb2bf`:

![image](https://user-images.githubusercontent.com/66680032/100205925-c4a70c00-2f16-11eb-864e-019155ee782a.png)

**Comment by r44083** [comment]
Maybe ```#999999``` ?

**Comment by Binaryify** [comment]
@r44083 i think #abb2bf is better

**Comment by irisida** [comment]
Definitely better to allow custom colour.

**Comment by Binaryify** [comment]
just release a new version~

**Comment by irisida** [comment]
updated to 3.9.11 

Still doesn't show up. I'm afraid. Also removed my initial override in case that was cancelling it. No joy thus far. Have restarted VSC twice. 
<img width="912" alt="Screenshot 2020-11-25 at 10 15 21" src="https://user-images.githubusercontent.com/20445648/100214157-6d4d6f80-2f07-11eb-9cf3-b786c6a28a5f.png">

**Comment by Binaryify** [comment]
@irisida did you set editor.renderLineHighlight to "all"

**Comment by irisida** [comment]
I hadn't no. I have now and hey presto!  It's even more fabulous than I'd hoped.

Thank you! (starred the repo. You people are all kinds of awesome)
