### ISSUE TITLE
Editor Theme setting not working

### ISSUE THREAD

**Issue by eduardocanellas** [Binaryify/OneDark-Pro#491]
**Describe the bug**
In version 3.9.11, the Editor Theme is being ignored on my environment. No matter which option I choose (vscode, ayu, justBlack...), the Editor Theme remains as the default One Dark Pro.

At least in version 3.9.10, this feature was working properly.

**To Reproduce**
1. Change the Editor Theme setting
2. Reload the Window
3. Check that nothing happens and the theme's still the same.

I downgraded my extension version to 3.9.0 and, in this version, the behavior is as expected.

**Expected behavior**
The Editor Theme to change to another one instead of just the default when I change the setting and reload the window.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20 Cinnamon
 - VSCODE Version: 1.51.1
 - Theme version: 3.9.11

**Additional context**
I had the impression that the editor theme setting was working on the first time that I changed the value. However, it doesn't work anymore.

Could anyone try it to check if it happens in other environments?

**Comment by eduardocanellas** [comment]
I checked the [commit from release 3.9.11](https://github.com/Binaryify/OneDark-Pro/commit/991bb3ddd05e089b67f5c99238023dfdcf6eca6c) and there's nothing that could cause such regression... Can anyone reproduce it?

**Comment by Binaryify** [comment]
try uninstall and re-install

**Comment by eduardocanellas** [comment]
> try uninstall and reinstall

It worked :100:. I should've tried it before instead of just changing versions, haha! Thank you.

**Comment by Binaryify** [comment]
I don't know why but it sometime happened in my mac, maybe vscode's issues
