### ISSUE TITLE
C# - Highlighting Error

### ISSUE THREAD

**Issue by NickITGuy** [Binaryify/OneDark-Pro#493]
**Describe the bug**
It seems certain parameters have no highlighting applied to them

**To Reproduce**
1. Download C# Extensions from Microsoft.
2. Open a C# file (Make sure to say yes if VSCode asks to add missing dependencies.

**Expected behavior**
I am hoping to get the parameter to be highlighted or colored correctly so its less jarring

**Screenshots & Example Code**
![Screenshot 2020-12-09 184828](https://user-images.githubusercontent.com/4210158/101603453-83067d00-3a4f-11eb-831d-079c21f4ac13.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64 Bit.
 - VSCODE Version  1.51.1
 - Theme version 3.9.11

**Additional context**
I will also provide a small snippet of test code to help reproduce the error

`using System;
using System.Collections.Generic;

namespace GradeBook
{
    public class Book
    {
        public Book(string name)
        {
            grades = new List<double>();
            this.name = name;
        }

        public void AddGrade(double grade)
        {
            grades.Add(grade);
        }

        public Statistics GetStatistics()
        {
            var result = new Statistics();
            result.Average = 0.0;
            result.High = double.MinValue;
            result.Low = double.MaxValue;

            foreach (var grade in grades)
            {
                result.Low = Math.Min(grade, result.Low);
                result.High = Math.Max(grade, result.High);
                result.Average += grade;
            }
            result.Average /= grades.Count;

            return result;
        }

        private List<double> grades;
        public string name;
    }
}`

**Comment by Binaryify** [comment]
what is your expected about the color

**Comment by NickITGuy** [comment]
I think either the same purple as before the lines or a red maybe? Just something that fits in with the current color scheme rather than a grey. :)

Thanks

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/102686150-a46e2280-4220-11eb-99e3-227e9984924c.png)
how about this

**Comment by Binaryify** [comment]
how about this
![image](https://user-images.githubusercontent.com/12221718/102686303-ae445580-4221-11eb-97d0-20be5bdf702f.png)

**Comment by NickITGuy** [comment]
wow it looks heaps better. :)

**Comment by Binaryify** [comment]
just release a new version, you can check it now

**Comment by NickITGuy** [comment]
Great! Thank you very much for the prompt fix. :)
