### ISSUE TITLE
Can't find the installation folder

### ISSUE THREAD

**Issue by Hypernut** [Binaryify/OneDark-Pro#499]
Although properly installed, it seems to me there is no folder for this theme in the extensions-folder, like for other themes and extensions. Where is it? :)

And sorry, It seems I cant add any other label than "bug" to this post.

**Comment by Binaryify** [comment]
for the history reason, the extensions-folder name is "zhuangtongfa.material-theme-version"
![image](https://user-images.githubusercontent.com/12221718/103496873-c26f9000-4e7a-11eb-85fb-386683c2dc3a.png)
