### ISSUE TITLE
One Dark Pro theme is either overriding or not specifying default markup textMateRules

### ISSUE THREAD

**Issue by smcenlly** [Binaryify/OneDark-Pro#502]
**Describe the bug**
One Dark Pro theme is either overriding or not specifying default markup `textMateRules` that are provided with VS Code default themes. This breaks syntax highlighting in extensions that use these rules.

**To Reproduce**
1. Clone [https://github.com/smcenlly/missing-textmate-tokens](https://github.com/smcenlly/missing-textmate-tokens) VS Code sample extension.
2. Open the repo and run `npm install`
3. Open the repo in VS Code and Start debugging (F5).
4. Create a new file (Ctrl + N).
5. Change its language to markup using the Change Language Mode command
6. Paste the contents below:

```
deleted

inserted

underline
```

7. Using any of the VS Code themes, you will see output similar to:
![Working Example](https://github.com/smcenlly/missing-textmate-tokens/raw/main/working.png)

**Expected behavior**
One Dark Pro should provide similar formatting (adjusted to its themes). Instead, no highlighting is displayed.

![image](https://user-images.githubusercontent.com/2074089/106074049-ee6af200-6156-11eb-902d-23c3e0174033.png)

**Comment by Binaryify** [comment]
v3.9.13 already fixed this
