### ISSUE TITLE
Cannot override some scopes

### ISSUE THREAD

**Issue by GBrachetta** [Binaryify/OneDark-Pro#503]
Maybe not a bug but I'm not able to override some of the color syntax

I'm trying to tweak some of the colors, for example:

```json


{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "name": "Javascript - Variable/object",
        "scope": [
          "variable.other.object.js"
        ],
        "settings": {
          "foreground": "#c7452e",
          "fontStyle": "bold italic"
        }
      }
    ]
  }
}
```

However, this is overridden by OneDark-Pro as you can see in the strike-thru lines at the end of this screenshot.

![Screenshot 2021-01-27 at 22 23 41](https://user-images.githubusercontent.com/57924268/106122146-a3ea7500-6158-11eb-8f0d-dc55734e4047.png)

Is there a way to, for example, alter the color of this particular item? Thank you!

**Desktop (please complete the following information):**
 - OS: MaCOS
 - VSCODE Version  [e.g. 1.52.1]
 - Theme version [e.g. 3.9.13]

**Comment by Binaryify** [comment]
please use 
```
"editor.semanticTokenColorCustomizations": {
    "rules": {
      "variable.defaultLibrary": {
        "foreground": "#c7452e"
      }
    }
  },
```
