### ISSUE TITLE
Ability to remove red underline?

### ISSUE THREAD

**Issue by sunjay** [Binaryify/OneDark-Pro#504]
First of all, thanks for maintaining this theme. Really helped me a lot when moving from Atom.

Ever since the latest update, I've noticed that all my identifiers are red with an underline. Was this the case before? Is there a way to turn off the underline?

Here's an example of how it currently looks:
	
![image](https://user-images.githubusercontent.com/530939/106561249-57a38a00-64f6-11eb-8768-a31b87fef435.png)

This is Rust code, so it probably uses the semantic highlighting features that were recently mentioned in some commits.

**Comment by Binaryify** [comment]
could you provide the code in your screenshots

**Comment by sunjay** [comment]
Yes. It's right here: https://github.com/sunjay/bst/blob/ddbad6f892b3675c680693c3aacd93ab3a4535ca/simple_bst/src/map.rs#L365-L377

It's also possible that since this is a language server issue. I use the rust-analyzer plugin and it probably emits some semantic highlighting stuff that may be causing this.

Let me know if I can provide you any more info to help diagnose this. :)

**Comment by Binaryify** [comment]
please set 
```json
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
      "textMateRules": [
        {
          "name": "Underline",
          "scope": "markup.underline",
          "settings": {
            "fontStyle": ""
          }
        },
      ],
    },
  },
```
in your setting.json before I reproduce this problem~

**Comment by sunjay** [comment]
Your solution worked! The underlines are gone. Yeah it's weird I don't know why they were there. Thanks for your help!
