### ISSUE TITLE
I cannot see anything in comments (diff mode with additions)

### ISSUE THREAD

**Issue by ikatyang** [Binaryify/OneDark-Pro#52]
![image](https://cloud.githubusercontent.com/assets/8341033/25860585/850c5fe6-3514-11e7-889a-9443f3fa8cfa.png)

**Comment by Binaryify** [comment]
You can see this issues https://github.com/Binaryify/OneDark-Pro/issues/38

**Comment by ikatyang** [comment]
```json
"workbench.colorCustomizations": {
  "diffEditor.insertedTextBackground": "#000000"
}
```
I found that it can be changed

![image](https://cloud.githubusercontent.com/assets/8341033/25879364/ce58415c-3563-11e7-8279-6e8637577316.png)

**Comment by ikatyang** [comment]
before
![image](https://cloud.githubusercontent.com/assets/8341033/25881482/c190be34-356f-11e7-809d-354aa5e92e86.png)

after
![image](https://cloud.githubusercontent.com/assets/8341033/25881452/959f20ea-356f-11e7-898f-5e32441b49c8.png)

```json
"workbench.colorCustomizations": {
  "diffEditor.insertedTextBackground": "#00809B33"
}
```

I'd like to send a PR for the result instead of my personal settings, since personal configs will be a global settings and applying to every theme.

Would you mind this change, or is there a better color? ( I am not good at selecting colors... )

**Comment by Binaryify** [comment]
I had try to bring this setting to the 'OneDark-Pro.json', however it can't work

**Comment by Binaryify** [comment]
Oh, I think I edit the old version file, now it work fine, thank ~

**Comment by Binaryify** [comment]
If you want to send a PR , just add it like this 
![image](https://cloud.githubusercontent.com/assets/12221718/25882489/5346525c-3576-11e7-8a96-91003f1fc8f0.png)
