### ISSUE TITLE
Update editor color for Flutter 2.0

### ISSUE THREAD

**Issue by andynvt** [Binaryify/OneDark-Pro#523]
Thank you so much One Dark Pro Team. Your theme is awesome.

I would like to request an update for Flutter 2.0.
One Dark Pro is perfect for Flutter below 2.0. Please see the attached images

Before

![Before](https://i.imgur.com/xgPlNpi.png)

After

![After](https://i.imgur.com/t5m83O7.png)

Thank you

**Comment by Binaryify** [comment]
vscode's dart support is not good
![image](https://user-images.githubusercontent.com/12221718/111905491-e65c6e00-8a86-11eb-92f6-c4aeabcd9c62.png)
![image](https://user-images.githubusercontent.com/12221718/111905500-f1af9980-8a86-11eb-88d6-d778294f6b21.png)
![image](https://user-images.githubusercontent.com/12221718/111905506-f5dbb700-8a86-11eb-942a-25f6634b2c33.png)
if I change that, so many color will change
![image](https://user-images.githubusercontent.com/12221718/111905527-13108580-8a87-11eb-8a66-515a633e2331.png)

**Comment by andynvt** [comment]
@Binaryify Thanks for your replying. If you cannot support it, can you show me how to change it to **Before** image that I posted?

**Comment by Binaryify** [comment]
did you install some extensions about dart?

**Comment by andynvt** [comment]
Yes. There are some
![image](https://user-images.githubusercontent.com/26719596/112005242-27bb4f00-8b55-11eb-8cee-96dc56286f9e.png)

**Comment by Binaryify** [comment]
I can't reproduce what you before,  did I miss something, in normal those should be light white color

**Comment by andynvt** [comment]
As I said, I upgraded to Flutter 2.x it automatically turns into red. In Flutter 1.xx, this is the best theme that I used and recommended to my colleagues

**Comment by Binaryify** [comment]
could you provide more information?
In my PC, it look normal
![image](https://user-images.githubusercontent.com/12221718/112165488-c1543080-8c29-11eb-9631-6dae00436779.png)
which system and vscode version are you using, and provide the scope of the code like this
![image](https://user-images.githubusercontent.com/12221718/112165868-18f29c00-8c2a-11eb-87bd-c2b56cd956cd.png)
![image](https://user-images.githubusercontent.com/12221718/112165918-23ad3100-8c2a-11eb-8153-9091162df200.png)

**Comment by Binaryify** [comment]
also you can try add this in your setting.json
```json
"editor.semanticHighlighting.enabled": false
```

**Comment by andynvt** [comment]
This is the scope 
![image](https://user-images.githubusercontent.com/26719596/112167339-f446f600-8c22-11eb-8f17-785d9f31292e.png)

After using
`"editor.semanticHighlighting.enabled": false`

![image](https://user-images.githubusercontent.com/26719596/112167652-3112ed00-8c23-11eb-9258-0a4c554a474a.png)


Your code works perfectly with what I need. Thank you again

**Comment by andynvt** [comment]
Love your theme so much. It was boring when working on another theme. Now, it backs. Thank you.

**Comment by Binaryify** [comment]
glad to hear that，also will figure out what affect  the highlight

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/113652679-d2d81680-96c6-11eb-87b4-c7c67b253c74.png)
I just improve the dart semantic highlighting, you can update the v3.10.10 and enable the semantic highlighting
```
"editor.semanticHighlighting.enabled": true
```
