### ISSUE TITLE
Javascript new Class function coloring seems off

### ISSUE THREAD

**Issue by haydencrain** [Binaryify/OneDark-Pro#525]
**Describe the bug**
The coloring for Class function constructors appears blue as opposed to yellow 

**To Reproduce**
1. Open a new file
2. Set language mode to "Javascript"
3. Paste the following snippet
```javascript
class Dog {}

const dog = new Dog();
```

**Expected behavior**
Class constructors should be appearing as Yellow, as opposed to blue.

**Screenshots & Example Code**

![Screen Shot 2021-03-29 at 1 54 37 pm](https://user-images.githubusercontent.com/21377034/112781414-7f4a4500-9096-11eb-817a-cf6b0ed74978.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version: 1.54.3
 - Theme version 3.9.15

**Additional context**
I also observed this happening for other Color themes, such as the Material theme (https://github.com/material-theme/vsc-community-material-theme/issues/19)

**Comment by Binaryify** [comment]
because they have same scope
![image](https://user-images.githubusercontent.com/12221718/113465382-1ed85080-9466-11eb-9e56-7ad214b9579c.png)
![image](https://user-images.githubusercontent.com/12221718/113465386-239d0480-9466-11eb-8386-a390d0620301.png)

**Comment by Binaryify** [comment]
but you could set "editor.semanticHighlighting.enabled" be true in your setting.json
![image](https://user-images.githubusercontent.com/12221718/113533859-90003b00-9601-11eb-8a08-9664f823f3ca.png)
![image](https://user-images.githubusercontent.com/12221718/113533869-98587600-9601-11eb-91f1-bb2be8b4af55.png)

**Comment by haydencrain** [comment]
Thanks for the response @Binaryify ! 

> because they have same scope, js syntax analyzer problem

Is there a chance that vscode could have updated the scope of class constructors recently? My understanding (just a theory) is that before Feb 6 (when I started observing this issue) they had a different scope, which is why it would appear yellow. I didn't get a chance to see what the scope of the class was before then though

Just to note, I've always had `"editor.semanticHighlighting.enabled": false,`.

**Comment by Binaryify** [comment]
I hadn't noticed the change， but I guess so, and I suggest you enable semanticHighlighting, it may not be perfect yet, but it is the direction of the future
