### ISSUE TITLE
Default theme sidebar is a little too flat that covers the focus indicator

### ISSUE THREAD

**Issue by dulltackle** [Binaryify/OneDark-Pro#527]
**Describe the bug**

Hello, the sidebar in version 3.10.1 seems a little too flat that makes the focus indicator invisible :(

* Before

    [![cue7Ox.png](https://z3.ax1x.com/2021/04/03/cue7Ox.png)](https://imgtu.com/i/cue7Ox)

* After

    [![cum9Xt.png](https://z3.ax1x.com/2021/04/03/cum9Xt.png)](https://imgtu.com/i/cum9Xt)

**Desktop (please complete the following information):**

- OS: Windows 10
- VSCODE Version: 1.55
- Theme version 3.10.1

**Comment by Binaryify** [comment]
will fix that soon

**Comment by Binaryify** [comment]
please update to version 3.10.2~

**Comment by dulltackle** [comment]
> please update to version 3.10.2~

I have updated, but seems no good :(

[![cul9Xj.png](https://z3.ax1x.com/2021/04/03/cul9Xj.png)](https://imgtu.com/i/cul9Xj)

**Comment by Binaryify** [comment]
wait a minute

**Comment by Binaryify** [comment]
please check 3.10.3

**Comment by Binaryify** [comment]
please check 3.10.4
