### ISSUE TITLE
Default theme sidebar looks like Flat theme

### ISSUE THREAD

**Issue by KevinRouchut** [Binaryify/OneDark-Pro#528]
**Describe the bug**
Default theme sidebar looks like Flat theme since version 3.10.0

**Screenshots**

![image](https://user-images.githubusercontent.com/8747883/113484784-70a2ca00-94aa-11eb-8020-52c8df416fda.png)

![image](https://user-images.githubusercontent.com/8747883/113484979-8369ce80-94ab-11eb-808b-26f38d437d10.png)

**Desktop**
 - OS: Arch Linux
 - VSCode version: 1.55.0
 - Theme version: 3.10.4

**Comment by xPaw** [comment]
Search results lost all the contrast as well.

**Comment by amitojsingh366** [comment]
please fix this...

**Comment by Binaryify** [comment]
@KevinRouchut @xPaw @amitojsingh366 
v3.10.5 had fixed that, please check if it work fine

**Comment by KevinRouchut** [comment]
> @KevinRouchut @xPaw @amitojsingh366
> v3.10.5 had fixed that, please check if it work fine

It looks good, thanks @Binaryify 👍🏻

**Comment by Fry98** [comment]
The sidebar is now dark again but all the text is still gray and pretty low-contrast. I'm pretty sure it used to be white, right?

**Comment by Binaryify** [comment]
@Fry98 yes, but it was too light before, will change to another color
before:
![image](https://user-images.githubusercontent.com/12221718/113495483-b43a1a00-9524-11eb-804c-fa97eb7074a4.png)
new:
![image](https://user-images.githubusercontent.com/12221718/113495496-c6b45380-9524-11eb-9fff-aa3ddf21ca6a.png)
how about this

**Comment by amitojsingh366** [comment]
> @Fry98 yes, but it was too light before, will change to another color
> before:
> ![image](https://user-images.githubusercontent.com/12221718/113495483-b43a1a00-9524-11eb-804c-fa97eb7074a4.png)
> current:
> ![image](https://user-images.githubusercontent.com/12221718/113495513-e3508b80-9524-11eb-977c-832da13e347d.png)
> 
> new:
> ![image](https://user-images.githubusercontent.com/12221718/113495496-c6b45380-9524-11eb-9fff-aa3ddf21ca6a.png)
> how about this

i personally prefer the 1st one

**Comment by Fry98** [comment]
@Binaryify I was personally fine with white but I guess this new color seems alright as well.

**Comment by Binaryify** [comment]
@Fry98 you can check v3.10.7, I believe you can accept new color

**Comment by Fry98** [comment]
@Binaryify This might just be me not being used to it yet but I have to say I still prefer the higher contrast of the white text, especially as I also use vivid colors and this doesn't really seem to fit in with that. Would you maybe consider it making it white for vivid and leaving it gray for normal? It's definitely a lot better than what it was before though.

**Comment by Binaryify** [comment]
@Fry98 
Everyone feels different, and each monitor and operating system display different colors, you can add this in your setting.json
```
 "workbench.colorCustomizations": {
    "sideBar.foreground": "#ffffff"
  },
```
