### ISSUE TITLE
gutter indicators

### ISSUE THREAD

**Issue by mcanepa** [Binaryify/OneDark-Pro#529]
This theme should alter [gutter indicators](https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators) as well

Here is what I've edited in settings.json to match Atom's colors

```
    "workbench.colorCustomizations": {
        "editorGutter.addedBackground": "#109868",
        "editorGutter.deletedBackground": "#9A353D",
        "editorGutter.modifiedBackground": "#948B60",
    }
```

or with a minor adjustment to match vs explorer colors

    "workbench.colorCustomizations": {
        "editorGutter.addedBackground": "#54C787",
        "editorGutter.deletedBackground": "#9A353D",
        "editorGutter.modifiedBackground": "#E0C987",
    }

**Comment by Binaryify** [comment]
I like the first
will update this soon~

**Comment by Binaryify** [comment]
v3.10.7 had add these~ thank for the advice

**Comment by mmykhaylov** [comment]
Will the gutters be also changed for the shadow theme? I kind of prefer the new variant, but the shadow theme is lighter on the eyes

**Comment by Binaryify** [comment]
@mmykhaylov sure

**Comment by foreignmeloman** [comment]
I don't see why the theme has to change the gutter colors. The changed line color looks like puke honestly.
For all of you who came here with the same discontent, add this to your `settings.json` to get the old colors back:

```json
    "workbench.colorCustomizations": {
        "[One Dark Pro]": {
            "editorGutter.addedBackground": "#587C0C",
            "editorGutter.deletedBackground": "#94151B",
            "editorGutter.modifiedBackground": "#0C7D9D",
        }
    },
```
