### ISSUE TITLE
color correction - PHP

### ISSUE THREAD

**Issue by mcanepa** [Binaryify/OneDark-Pro#533]
I've noticed some php inconsistencies between this theme and atom's. Here is a sample image

![Captura de pantalla de 2021-04-08 19-17-58](https://user-images.githubusercontent.com/25961439/114104499-5d746d80-98a1-11eb-9b4d-f6c490fcf8b8.png)

**Comment by Binaryify** [comment]
I don't think it's necessary to modify it. It could be two styles
But the begin I think can be red

**Comment by mcanepa** [comment]
I agree that it could be two styles. Not necessarily the same color by color

Do you think you could also change the namespace part?

**Comment by Binaryify** [comment]
@mcanepa yes
how about this
![image](https://user-images.githubusercontent.com/12221718/114254735-b2b89800-99e3-11eb-8e41-b1474b111cdc.png)

**Comment by mcanepa** [comment]
much much better! thank you

**Comment by Binaryify** [comment]
already release~

**Comment by andrerahardjo97** [comment]
Php end tag is not styled properly. Is this only on my machine? 🤔
If yes, is there is a json setting to force the change of the end tag color?
Thanks in advance, and sorry if my english is bad.

![2021-04-11_23-26-59](https://user-images.githubusercontent.com/20762999/114312656-90c33080-9b1d-11eb-8d73-0c424afa5be1.png)

**Comment by JordanPak** [comment]
@andrerahardjo97 Same issue here G

**Comment by machadomatt** [comment]
Same issue as @andrerahardjo97. I just did a quick change to "fix it" temporally for now:

```json
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
        "textMateRules": [{
            "scope": ["punctuation.section.embedded.begin.php"],
            "settings": {
                "foreground": "#d55fde"
            }
        }]
    }
},
```

**Comment by JordanPak** [comment]
Ah @machadomatt I think that's the "vivid" foreground color. `#c678dd` should work for the default if that's what you use @andrerahardjo97.

**Comment by JordanPak** [comment]
Also idk if this was intended so please ignore if so, but the namespace highlighting when instantiating an object looks different now too: 

![image](https://user-images.githubusercontent.com/7574199/114326851-b55ede80-9b04-11eb-8eda-797db700ec0c.png)

It's still all yellow when declaring the namespace and with `use`:

![image](https://user-images.githubusercontent.com/7574199/114326879-ca3b7200-9b04-11eb-8372-8c711bb6d549.png)

**Comment by mcanepa** [comment]
@JordanPak the namespace change was in fact intended, and both the "declaration" and the "use" are now just like Atom's

**Comment by Binaryify** [comment]
@JordanPak 
that is atom look like
![image](https://user-images.githubusercontent.com/12221718/114331082-d0b60200-9b75-11eb-9e2a-6561456f2e7e.png)
if you don't like it, you can add this in your setting.json
```
"editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
      "textMateRules": [
        {
          "name": "support.other.namespace.php",
          "scope": [
            "support.other.namespace.php"
          ],
          "settings": {
            "foreground": "#E5C07B"
          }
        }
      ]
    }
  },
```

**Comment by JordanPak** [comment]
Ah ok @mcanepa @Binaryify; thanks for clarifying. I like it.

**Comment by andrewhawkes** [comment]
The `<?php` and `?>` being different colours has really been throwing me off.
Is there any way I can change this back to how it was previously?

**Comment by Binaryify** [comment]
v3.10.13 should already fixed the different color error
if you want change the color to before
you can add this in your setting.json
```
  "editor.tokenColorCustomizations": {
    "[One Dark Pro]": {
      "textMateRules": [
        {
          "name": "punctuation.section.embedded.begin.php",
          "scope": [
            "punctuation.section.embedded.begin.php",
            "punctuation.section.embedded.end.php"
          ],
          "settings": {
            "foreground": "#c678dd"  // or #e06c75
          }
        }
      ]
    }
  },
```

**Comment by JordanPak** [comment]
Hey @Binaryify thanks for the quick end tag patch and maintaining this awesome theme. Much appreciated!

**Comment by Binaryify** [comment]
@JordanPak It was careless of me

**Comment by andrewhawkes** [comment]
@Binaryify thank you that's great!
