### ISSUE TITLE
Add secondary button styles

### ISSUE THREAD

**Issue by misolori** [Binaryify/OneDark-Pro#541]
VS Code will start using the secondary button style in custom dialogs. These are visible on Windows and on the web (i.e. Codespaces). To see this:

1. [Install Insiders 1.56](https://builds.code.visualstudio.com/builds/insider)
2. Set `"window.dialogStyle": "custom",` in your user settings
3. Try to close an unsaved file that will prompt the dialog below

![image](https://user-images.githubusercontent.com/35271042/116308817-d65a3d00-a75c-11eb-95db-52056d27fd1e.png)

Since this is a newer color token, you'll need to add a few tokens:

- `button.secondaryBackground`
- `button.secondaryForeground`
- `button.secondaryHoverBackground`

**Comment by Binaryify** [comment]
thank for the notice ~
