### ISSUE TITLE
Apply the theme in specific parts of the UI

### ISSUE THREAD

**Issue by AndreJesusBrito** [Binaryify/OneDark-Pro#543]
**Describe what you want**
So, Im a huge fan of Atom One Dark syntax highlighting, however I think I prefer to use the vscode default theme for the rest of the UI. I would like to combine them.

Here is a quick preview that I did with devtools of what it looks like:
![image](https://user-images.githubusercontent.com/35274086/116813985-74c81300-ab4e-11eb-8f66-27de0e6b1376.png)

I think one cool feature would be to let the user choose to apply the theme only for specific parts of the UI. The 3 first that come to my mind are the "general UI", the "editor tokens", and the "teminal". So for example, in my print above I would disable the theme for the general UI and for the teminal and just apply to tokens on the editor.

**Additional context**
To let the user choose I think 3 checkboxes in the config are a good way. Furthermore, it will complement the "One Dark Pro: Markdown Style" option.

**Comment by ImLuze** [comment]
@AndreJesusBrito  In the settings of One Dark Pro you change the Editor theme. You can choose `vscode` there to apply the default vscode theme to the editor, but keep the One Dark Pro syntax theme. Does this solve your issue?
![Screenshot 2021-05-06 at 11 21 21](https://user-images.githubusercontent.com/22794451/117274262-30de5200-ae5d-11eb-8412-690861339595.png)

**Comment by AndreJesusBrito** [comment]
@ImLuze yeah, thats it, thank you very much!
