### ISSUE TITLE
Some color issues

### ISSUE THREAD

**Issue by jackytse** [Binaryify/OneDark-Pro#55]
I use the OneDark-Pro v2.7.2, the "titleBar.activeBackground", the "tab.activeBackground" and the "editor.background" are the same, I think that is not good; the "statusBar.background" is not the visual studio classical blue, is there something wrong?

![qq20170510-093435](https://cloud.githubusercontent.com/assets/5107059/25879495/890426b0-3564-11e7-890d-3d37632b9f1c.png)

**Comment by Binaryify** [comment]
It was a new feature 
https://github.com/Binaryify/OneDark-Pro/pull/45
https://github.com/Binaryify/OneDark-Pro/pull/51
You can update to the latest version v2.7.3, and see if it had improve

**Comment by jackytse** [comment]
Thanks for your answer, I updated to the 2.7.3, but I don't like this update, because most components's color are the same. I don't think it is a better choice.

**Comment by Binaryify** [comment]
Everyone's aesthetic is different, so I provide this  DOCS to help everyone to DIY 
https://binaryify.github.io/OneDark-Pro

**Comment by jackytse** [comment]
I agree with you, everyone's aesthetic is different, you've done very well, thank you.
