### ISSUE TITLE
Slow loading of custom setting

### ISSUE THREAD

**Issue by TimilsinaBimal** [Binaryify/OneDark-Pro#551]
**Describe the bug**
I am using one dark pro in my vs code with some customizations for python color syntax. And, whenever I open any python file it takes 2-3 seconds to load the custom syntax color. Also when Commenting, it does not change the color immediately but takes a lot of time (more than 10 seconds for some files.)

**To Reproduce**
1. Apply One dark theme.
2. Use vivid color
3. Change the setting as follows:
```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "support.module",
                    "meta.function-call",
                    "entity.name.type.class",
                    "support.class",
                    "variable.other.property"
                ],
                "settings": {
                    "foreground": "#61afef"
                }
            },
            {
                "scope": [
                    "variable.parameter"
                ],
                "settings": {
                    "foreground": "#11B7BB",
                }
            },
            {
                "scope": [
                    "variable.other.property",
                    "entity.name.namespace"
                ],
                "settings": {
                    "foreground": "#ef596f"
                }
            },
            {
                "scope": [
                    // "source.python",
                    "meta.function.parameters.python",
                    "variable.other.readwrite",
                    "variable.parameter.function-call.python",
                    "meta.function-call.arguments",
                    "variable.parameter.function.language.python",
                    "meta.function-call.arguments.python",
                ],
                "settings": {
                    "foreground": "#abb2bf"
                }
            }
        ]
    }
```

4. Open any python file.
5. Try commenting multiple lines at once.

**Expected behavior**
It should load the theme immediately after I open the file. and It cannot take a long time to change color while commenting multiple lines.

**Screenshots & Example Code**
![image](https://user-images.githubusercontent.com/45899783/118348218-8fe04d00-b568-11eb-940f-fa31ba840988.png)
 Expected Behaviour

![image](https://user-images.githubusercontent.com/45899783/118348252-ab4b5800-b568-11eb-8134-4de5eae235c4.png)
Original Behaviour immediately after opening the file(up to 2-3 seconds).

***In case of commenting***
![image](https://user-images.githubusercontent.com/45899783/118348281-ef3e5d00-b568-11eb-9274-256ca6a57b5a.png)

Original Behavior   
![image](https://user-images.githubusercontent.com/45899783/118348285-f9f8f200-b568-11eb-9647-cfbb79dad1fa.png)
Expected behavior

**Desktop (please complete the following information):**
 - OS: Windows
 - VSCODE Version  [1.56.2]
 - Theme version [e.g. 3.10.14]

**Comment by Binaryify** [comment]
that is vscode feature, you can set this in your settings.json
```
"editor.semanticHighlighting.enabled": false,
```

**Comment by TimilsinaBimal** [comment]
That Worked! Thank you!
