### ISSUE TITLE
The atom or symbol type is displayed incorrectly

### ISSUE THREAD

**Issue by Hentioe** [Binaryify/OneDark-Pro#562]
For example, the value `:atom1` is a whole, and they start with `:`. Generally called atom (Elixir) or symbol (Ruby) type.

This is the default dark theme:

![image](https://user-images.githubusercontent.com/13946976/124403765-80ac9d00-dd6a-11eb-87cb-c7ee6761971c.png)

But in One Dark Pro, their colors are different, as if they are not a whole:

![image](https://user-images.githubusercontent.com/13946976/124403811-ba7da380-dd6a-11eb-82e3-8a6ed2fde5bf.png)

**Comment by Binaryify** [comment]
could provide the code
