### ISSUE TITLE
Checkbox in workspace trust not visible

### ISSUE THREAD

**Issue by septatrix** [Binaryify/OneDark-Pro#563]
**Describe the bug**
The checkbox in the workspace trust dialog has no perceivable outline. The check itself and focus outline are visible but in unchecked, unfocused state it is invisible.

**To Reproduce**
1. Open a folder which you have not yet granted trust (alternatively "Settings icon > Manage Workspace Trust" and revoke trust for a folder)

**Expected behavior**
The checkbox should be clearly visible

**Screenshots & Example Code**
![image](https://user-images.githubusercontent.com/24257556/125172070-c7115a00-e1b7-11eb-8810-247e77b58819.png)

**Desktop (please complete the following information):**
 - VSCODE Version: 1.57.1
 - Theme version: v3.10.14

**Comment by Binaryify** [comment]
already fixed in v3.10.15~

**Comment by septatrix** [comment]
Tested and works as expected
