### ISSUE TITLE
Feture: Add highlight for currently focused tab

### ISSUE THREAD

**Issue by Aukstkalnis** [Binaryify/OneDark-Pro#565]
**Describe what you want**
I would like to be able instantly spot currently focused tab (opened file). With current stile it is very hard to see which tab is focused.  Other themes have something like orange line above file name:
![image](https://user-images.githubusercontent.com/9738294/125309674-9d347080-e33a-11eb-8fc7-242c35e92d67.png)
This helps to instantly see where is currently focused tab. It would be nice to have something like this as well.

**Comment by Binaryify** [comment]
you can add this in your setting.json before I release new version
```
"workbench.colorCustomizations": {
    "tab.activeBorderTop": "#4d78cc",
    "tab.activeBorder": "#282c34",
  },
```

**Comment by Aukstkalnis** [comment]
Nice 👍 Thank you.

**Comment by Binaryify** [comment]
already support this, you can remove the setting.json code snippet I send you before, the color have a litter different

**Comment by NoahELE** [comment]
I think the orange color is a little bit weird with the color scheme. I think it would be great to make it blue. As orange is a warm color and the scheme consists of mainly cold colors.

**Comment by nifte** [comment]
Yeah, I'm not a fan of the active tab border. It should be blue instead of orange, and it should be an option in the settings menu that is disabled by default.

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/126108352-28d4d2a5-036d-4e60-8cd7-e9dd42eb86ab.png)
blue is not good idea, maybe light white?
![image](https://user-images.githubusercontent.com/12221718/126108457-492aecc6-029d-44a4-bedc-149a223f9854.png)

**Comment by NoahELE** [comment]
nah, I would still prefer blue.
Or a lighter blue gray, like this?
![image](https://user-images.githubusercontent.com/49080986/126108878-99a77b65-f76e-4559-a567-d4e001010333.png)

**Comment by Aukstkalnis** [comment]
Well, I was suggesting a feature, not a color :D The color came from Github theme. I just copied for reference :) 

@Binaryify thanks you for this feature. And good idea to place the line on the bottom of the tab :) It looks more solid :)

**Comment by Binaryify** [comment]
@NoahELE #90a4ae is okay
@Aukstkalnis yes, that's the problem, as more and more people use it, it's hard for me to keep everyone happy, so I will make a default color, then tell other how to config it

**Comment by nifte** [comment]
@Binaryify I think there are more people who prefer not to have any tab border at all, and I think the best solution is to have it as a toggleable option in the settings menu (disabled by default).

**Comment by Binaryify** [comment]
@nifte I prefer delete that, and tell people how to custom that in setting.json, toggleable option still need to custom the color, what do you think

**Comment by nifte** [comment]
Yeah, I'd say just remove it since the users who do want this feature can easily add it themselves with the settings.json lines you provided above.

**Comment by Aukstkalnis** [comment]
@Binaryify so I see you decided to remove this change... While @Binaryify thinks that unable to see which tab is currently focused is interesting feature and not a bug... That's interesting. Well, that's fine be me, but at least tell me how to modify tabs border to highlight bottom border because there is no setting "tab.activeBorderBottom".

Thanks.

**Comment by nifte** [comment]
@Aukstkalnis The setting you're looking for is just `tab.activeBorder`:

```json
"workbench.colorCustomizations": {
    "tab.activeBorder": "#ff0000"
}
```
