### ISSUE TITLE
Changing Background Colour and other colours

### ISSUE THREAD

**Issue by BigDaddy058** [Binaryify/OneDark-Pro#569]
I find the default color which One Dark Pro ships with a little uncomfortable 
Can you make it a bit darker 
Or is it not possible ?
I have made it darker locally IDK if it's appropriate or not 
But here is my Screenshot 
![Screenshot from 2021-07-21 10-25-40](https://user-images.githubusercontent.com/58597122/126431994-5bc40ce6-775e-4116-80ae-1afa56f61db4.png)

**Comment by Binaryify** [comment]
you should custom color in your setting.json, everyone's preference for colors is subjective

**Comment by BigDaddy058** [comment]
So I should just write the scopes and colour code in my setting.json and not inside the extension's json file?

**Comment by Binaryify** [comment]
just setting.json  is okay

**Comment by BigDaddy058** [comment]
Oh thanks
