### ISSUE TITLE
Problem setting theme after latest update

### ISSUE THREAD

**Issue by kathyrollo** [Binaryify/OneDark-Pro#57]
![one_dark_pro_problem](https://cloud.githubusercontent.com/assets/28589393/25887797/1ba5de7e-3596-11e7-90a9-d616c9da8220.png)
One Dark Pro: 2.7.3 | 2017.5.10

![vscode_portable](https://cloud.githubusercontent.com/assets/28589393/25887849/548e577a-3596-11e7-8010-23f4d5575f0e.png)
I'm using VSCode Portable.

**Comment by will-stone** [comment]
Try updating Code to 1.12

**Comment by will-stone** [comment]
@Binaryify might be worth bumping the VScode version in package.json/engines to ^1.12.0?

**Comment by kathyrollo** [comment]
@will-stone Confirmed working after updating VSCode to 1.12.0, thanks. Suggestion to bump version seconded.

**Comment by Binaryify** [comment]
@will-stone 
Done, will update tomorrow
