### ISSUE TITLE
Change the python word colors and making it look more colorful

### ISSUE THREAD

**Issue by realTristan** [Binaryify/OneDark-Pro#578]
- Currently, my python code looks like this
- ![image](https://user-images.githubusercontent.com/75189508/128578619-3935f771-0560-4c9e-b7a5-d2626d979d15.png)

- I want it to look like this
- ![image](https://user-images.githubusercontent.com/75189508/128578653-16d63269-d386-4211-955c-35491e2d8ac4.png)

- Where it's more colorful

**Comment by Binaryify** [comment]
please install Pylance

**Comment by IanLiuTW** [comment]
Hello,

I love the theme, but I have some issues as shown in the attached image.

- Is it possible to color the keywords  `async` and `await` in python (I have installed Pylance)?

- The `-> WeatherStatus` on line 22 makes the rest of the function not coloring some keywords correctly (`doc string` and `return`). I tried removing the `-> WeatherStatus` part and everything goes back to be perfectly fine.

Thank you.

![example](https://user-images.githubusercontent.com/567856/128711756-7224d802-b53f-4dbe-a8b1-af230d85fb66.png)

**Comment by Binaryify** [comment]
@IanLiuTW could you provide the code in your screenshot

**Comment by IanLiuTW** [comment]
@Binaryify Sure. I've made some changes but the results are the same. Thank you for the effort.

```python
import httpx


async def request_weather_stat(location: object) -> dict:
    """ Get weather status from https://weather.service """

    url = f"https://weather.service?" \
          f"city={location.city}" \
          f"&country={location.country}"
    if location.state:
        url += f"&state={location.state}"

    async with httpx.AsyncClient() as client:
        resp = await client.get(url)
        resp.raise_for_status()

    return parse_resp_to_weather_stat(resp.json())


def parse_resp_to_weather_stat(data: dict) -> object:
    """ Parse the json response from https://weather.service
        into a WeatherStatus object and return it.
    """

    location = data.get('location', {})
    weather = data.get('weather', {})
    forecast = data.get('forecast', {})

    return object(
        location=object(
            city=location.get("city", "N/A"),
            state=location.get("state", "N/A"),
            country=location.get("country", "N/A"),
        ),
        weather=weather.get("category", "N/A"),
        description=weather.get("description", "N/A"),
        temp=forecast.get("temp", 0.0),
        temp_feeling=forecast.get("feels_like", 0.0),
        temp_low=forecast.get("low", 0.0),
        temp_high=forecast.get("high", 0.0),
        humidity=forecast.get("humidity", 0.0),
    )
```

**Comment by Binaryify** [comment]
it look normal in my Windows's VSCode
![image](https://user-images.githubusercontent.com/12221718/129045191-84f08171-a397-4a7e-9f55-cb2dbc64c069.png)

**Comment by IanLiuTW** [comment]
I see... It's the "Python for VSCode" and I just read the reviews about it is apparently outdated.
My bad on this one. My code looks much better now. Thank you so much!

**Comment by EE-EBa** [comment]
my os is archlinux,i try many ways,finaly ,  i install vscode from yay ,not pacman .this work for me.  pylance maybe not support open source code.
