### ISSUE TITLE
Nothing changes when I try to change One Dark Pro's "Editor theme"

### ISSUE THREAD

**Issue by anthony930622** [Binaryify/OneDark-Pro#579]
I'm using Code-OSS 
![Screenshot_2021-08-08_10-58-23](https://user-images.githubusercontent.com/69449791/128619343-319fb460-330c-4b1a-be95-e633e20b5168.png)
Nothing really changes when I selected different editor themes.

**Comment by Binaryify** [comment]
you need to reload vscode window

**Comment by anthony930622** [comment]
> you need to reload vscode window

@Binaryify  That's the thing. I did. Several times. But nothing changes.

**Comment by anthony930622** [comment]
@Binaryify  Is this issue specific to vscode-oss? Because I can't reproduce the same issue on the vscode installed on my windows machine.

**Comment by Binaryify** [comment]
might be

**Comment by anthony930622** [comment]
Confirmed that this issue is specific to Code OSS. I just built the official Microsoft version from AUR and the editor theme setting worked.

**Comment by ElSamhaa** [comment]
Any plans to fix this on Code OSS?
