### ISSUE TITLE
Theme ruler

### ISSUE THREAD

**Issue by will-stone** [Binaryify/OneDark-Pro#59]
This has been requested and MS have confirmed a new config setting will be added: https://github.com/Microsoft/vscode/issues/26377

Leaving this issue to remind us to update it when Code is updated.

**Comment by Binaryify** [comment]
Good job

**Comment by Binaryify** [comment]
@will-stone 
It support now, what color do you think is better?

**Comment by will-stone** [comment]
@Binaryify Atom uses `rgba(171, 178, 191, 0.15)` converting the rgb to hex gives `#abb2bf`. Using [this Stackoverflow answer](https://stackoverflow.com/a/17239853) to get the correct alpha, gets you `#abb2bf26`. So I'd suggest using that to keep in line with Atom's One Dark Theme.
