### ISSUE TITLE
How to change background color of code blocks inside markdown file

### ISSUE THREAD

**Issue by GorvGoyl** [Binaryify/OneDark-Pro#597]
How can I change the background color of all code blocks inside markdown files. For both one liner (start with `) and multiline (starts with ```). 

Here's an example from Sublime text:

![image](https://user-images.githubusercontent.com/7106086/131342663-005d6b2f-a3fb-4d10-87b6-b0baba25d7ed.png)

**Comment by Binaryify** [comment]
vscode don't support that, so I can't add this feature
