### ISSUE TITLE
Idea: Break out the theming tutorial into it's own repo and website

### ISSUE THREAD

**Issue by will-stone** [Binaryify/OneDark-Pro#60]
It's great that you provided instructions on how to find scopes etc. and I learnt a lot about VSCode theming from it, however, this info applies to _all_ theming (not just for _this_ theme). Until MS improves their docs on this, maybe these instructions could be broken-out into their own website? Then other this theme and other theme makers could simply link to them. It could provide a central source for tips and knowledge. I like the idea of it opening with a simple tutorial, and walking people through to more advanced techniques and being able to read MS's docs with confidence. What do you reckon?

**Comment by Binaryify** [comment]
Good idea, but I don't have enough time

**Comment by will-stone** [comment]
Yeah, totally understand. I might just write it up on my website sometime.

**Comment by Binaryify** [comment]
@will-stone 
Of course you can
