### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by whippingdot** [Binaryify/OneDark-Pro#605]
# I want to have different versions of this theme, like a WAY darker dark, and maybe an 'Ocean' style

## Long Intro

I always come back to this theme because it has **no white** like almost anywhere in the code files. The variables are colorized, which almost no other theme has. _But_, I want more. A new theme called Starfall was released (check it out), which looks amazing, the color scheme and everything are mind-blowing 🤯 ! In Starfall, the reason I like it is that in Starfall Ocean it uses a very dark blue as the background color which makes the editor look super nice! I personally think dark blues look better than grey, so...

## Coming to the point

My hope is that you can add more options to the theme styles. Right now you have One Dark Pro (the default), flat (which I don't like), and dark (which is darker, but still a very light grey so if you could make it more darker that would be nice). Maybe you could make the dark darker, or add a darker dark style...or the one I really want is an Ocean variant, which uses a lot of blue. If you could implement one of these it would be nice...thanks!

### Screenshot of Starfall Ocean

![image](https://user-images.githubusercontent.com/64354499/132801026-79a99f92-e895-4fd4-b479-dacad3352cdd.png)

### Screenshot of One Dark Pro Dark

![image](https://user-images.githubusercontent.com/64354499/132800997-9590cbf6-7c17-4aba-a035-6ff9e9a2f47d.png)

Oh BTW another request - maybe add an option in your theme to allow users to choose the color of the variables and also remove the option to use nord themes or whatever in settings to slow down the startup time?

**Comment by Binaryify** [comment]
v3.12.0 support Ocean theme and dynamically loading themes files, also Add variables colors settings
could you try https://github.com/Binaryify/OneDark-Pro/blob/feedback/onedarkpro-3.12.0.vsix before I publish it to the vscode's marketplace?
I need some feedback

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/133925294-5f30e607-2ea7-4562-90ec-caa162cadb27.png)
![image](https://user-images.githubusercontent.com/12221718/133925304-809f430d-6743-42fb-b609-c4e805d1a81a.png)

you can use this to install the vsix

**Comment by whippingdot** [comment]
@Binaryify hey, I downloaded it and added it. Where can I try the ocean theme? Also did you use the color scheme of that (like create your own custom version of it) or did you just use the same CSS as theirs?

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/133930532-a2695a96-f953-4c5d-925b-6d50a2be2dc5.png)
check this

**Comment by Binaryify** [comment]
also you need to apply the default theme 
![image](https://user-images.githubusercontent.com/12221718/133930580-d1a0368c-fc1b-4853-a1da-ea89fdfc9c13.png)

**Comment by whippingdot** [comment]
No yea I manually reloaded the vs code and I see the ocean theme option

I clicked on the option yet it still isn't changing the color scheme 
![image](https://user-images.githubusercontent.com/64354499/133930614-fa5e2fd7-0a94-4b70-b759-0da68b5858f5.png)

**Comment by whippingdot** [comment]
Oh wait @Binaryify I just saw the comment saying you have to change the default theme to one dark pro too - it is working now

Thanks!

BTW could you call this 'One Dark Pro Ocean' and add it as one of the default options too? That might attract more people to that specific option and they could stick with the theme

**Comment by whippingdot** [comment]
Also this would make it so the default theme wont have to be one dark pro and you won't have to go deep in to the settings to make ocean work. Just add it in the 'Preferences: Color Themes' list of themes in vs code

**Comment by Binaryify** [comment]
maybe I should also move other built in theme to the vscode theme list, what do you think

**Comment by whippingdot** [comment]
yeah...but something I mentioned in the first comment of this issue thread was that I think the other built in themes should be removed - don't they take up unnecessary space?

**Comment by Binaryify** [comment]
yes, that need  take up unnecessary space, so I add dynamic loading themes file feature in this version, actually some people like use other editor theme but like OneDark's code highlight, I don't know should I remove that built-in themes and tell theme how to combine other editor theme they like ? or keep them and add Ocean theme and more

**Comment by whippingdot** [comment]
Ok, so first yes I admit I like OneDark's syntax highlighting more than other themes. If dynamic loading theme files saves space on the PC, then leave the built-in themes otherwise remove them. If it does save space, then also try thinking of creative names for each theme, like 'One Dark Pro Ocean' instead of 'One Dark Pro Starfall Ocean'.

BTW if you do remove the other built-in themes and add the tutorial on how to combine themes, try to keep it upfront or open a file that tells them how to when installing the theme, so people are aware that that is an option.

P.S. An unnecessary question but are you British or American - do you know English well?

**Comment by whippingdot** [comment]
Oh BTW I found a glitch with the Ocean theme, there are no hover effects. I think in starfall ocean there are no hover effects too but it would be better if you edited the theme to have hover effects when you hover over things like these
![image](https://user-images.githubusercontent.com/64354499/133932720-bb3c4a3e-409a-42bc-892d-fc3fcbe974f6.png)

**Comment by Binaryify** [comment]
i'm a chinese, so my english is just so so
actually I don't suggest make many other editor themes in this theme, it look like I stole other author's theme and also I don't have time to maintain those theme
this it why I didn't let those themes show in theme list

vscode also can easy to custom theme
first switch the theme what you like
then press "ctrl+shift+p", input theme and choose "generate color theme from current setting" option
![2f5094cd95b36401bec3ce6d6756609](https://user-images.githubusercontent.com/12221718/133968067-2e1fdd6c-4157-405b-afc5-dc1ee57a6e4d.png)
then copy the colors code snippet
![40aa679b9dcc158a14d23c0261927bd](https://user-images.githubusercontent.com/12221718/133968265-967db47b-09cd-4b4b-9b70-63e97da7d3ca.png)
then open the settions.json
add or edit the `workbench.colorCustomizations"`, put the colors code snippet to it
![image](https://user-images.githubusercontent.com/12221718/133968370-44b038d0-7993-4943-9894-99ea82aaa211.png)
press `ctrl + s` then switch the `One Dark Pro` theme and you will find your editor theme already become the theme what you just copy and it keep the One Dark Pro's code highlight

**Comment by Binaryify** [comment]
> Ok, so first yes I admit I like OneDark's syntax highlighting more than other themes. If dynamic loading theme files saves space on the PC, then leave the built-in themes otherwise remove them. If it does save space, then also try thinking of creative names for each theme, like 'One Dark Pro Ocean' instead of 'One Dark Pro Starfall Ocean'.
> 
> BTW if you do remove the other built-in themes and add the tutorial on how to combine themes, try to keep it upfront or open a file that tells them how to when installing the theme, so people are aware that that is an option.
> 
> P.S. An unnecessary question but are you British or American - do you know English well?

I suggest you create a issue in Starfall Ocean GitHub repo, this helps maintain the theme

**Comment by opqpop** [comment]
Hi, I just upgraded and my One Dark Pro looks completely different from before, what settings can I pick to get it back to how it looked the previous version? 

My previous version had a much darker background than the previous version

Was it "VS Code" editor theme? This one seems to match the previous one closest but it still doesn't feel right. 

Also, the current default editor theme "One Dark Pro" is completely different, it has a lighter background which I don't want.

![image](https://user-images.githubusercontent.com/5566843/134594799-b26c5604-c198-4931-89c1-ae557a08ff6c.png)

**Comment by Binaryify** [comment]
@opqpop 
![image](https://user-images.githubusercontent.com/12221718/134605228-c9a03e29-99cc-4f9d-bcbd-457eb05a8e97.png)
you can click this to install old version, and could you provide the screenshots what you think is different

**Comment by opqpop** [comment]
Ah thank you, after looking at it more in detail, it seems VSCode theme was indeed the one I was using, so no need to downgrade anymore. Sorry for the thrash.

**Comment by Binaryify** [comment]
@opqpop ah, it's fine, thanks for your support~
