### ISSUE TITLE
Bold & Italics not working

### ISSUE THREAD

**Issue by whippingdot** [Binaryify/OneDark-Pro#606]
**Describe the bug**
I think I remember when I first used the theme there used to be bold highlighting for function names and italics for comments or something like that right? For the last few months I haven't seen any bold or italic highlighting in my C++ code, or Python code I think, and I was wondering if you could see if it was an error in the theme or if something was wrong on my end and you knew how to fix it. Thanks for the help BTW!

**To Reproduce**
1. Enable Bold on some Scopes
2. Enable Italic on some Scopes
3. Watch and see that there is no bold or italic anywhere (I don't even know what vivid colors does but that also might not be working)

**Expected behavior**
I expect to see bold colors in function names and in other places, and italic code in some places like comments or something else too (whatever is supposed to happen normally)

**Screenshots & Example Code**
![image](https://user-images.githubusercontent.com/64354499/132801611-66ed37ec-c30c-4491-93e7-b6a61cb00ae6.png)
![image](https://user-images.githubusercontent.com/64354499/132801626-afc3aa6a-094f-42cb-946c-3ba14106387e.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - VSCODE Version [1.61.0-insiders]
 - Theme version [3.11.4]

**Comment by Binaryify** [comment]
One Dark Pro Flat/One Dark Pro Darker didn't support set bold& italics before
v3.12.0 support that
could you try https://github.com/Binaryify/OneDark-Pro/blob/feedback/onedarkpro-3.12.0.vsix before I publish it to the vscode's marketplace?
I need some feedback

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/133925294-5f30e607-2ea7-4562-90ec-caa162cadb27.png)
![image](https://user-images.githubusercontent.com/12221718/133925304-809f430d-6743-42fb-b609-c4e805d1a81a.png)

you can use this to install the vsix

**Comment by whippingdot** [comment]
installed it, reloaded editor multiple times, yet I don't seem to have bold or anything still.

**Comment by whippingdot** [comment]
No wait it works now, the bold is very hard to see so I didn't notice. NOICE!

BTW it is hard to see for me cause i have a small font size lol.

**Comment by Binaryify** [comment]
@whippingdot this extension had a data reference problem, it make setting  change sometime don't work, it should be normal after v3.13.0

**Comment by whippingdot** [comment]
Kk

Sent from my iPad

On Sep 30, 2021, at 7:44 AM, binaryify ***@***.***> wrote:

﻿

@whippingdot<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwhippingdot&data=04%7C01%7C%7C702f83b78b8a46a91d2108d983b817ed%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637685648960983726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XWZ7%2F8ZPy1Amvrj5woLijy%2FimjPsH6iT%2BqsB%2FQpvpVA%3D&reserved=0> this extension had a data reference problem, it make setting change sometime don't work, it should be normal after v3.13.0
