### ISSUE TITLE
Javascript red coloring everywhere

### ISSUE THREAD

**Issue by rafamel** [Binaryify/OneDark-Pro#61]
The current styling on Javascript is too overwhelming as compared to the original Atom One Dark syntax. The red takes over everything pretty easily.

**This is OneDark Pro:**
![OneDark Pro](http://image.prntscr.com/image/2d81df5ce68043c597f8050cdb80c177.png)

**This is Atom's original One Dark:**
![Atom's original One Dark](http://image.prntscr.com/image/b2f293b2f8b445e185526870435c9e6e.png)

Is this an issue or is it by design?

**Comment by Binaryify** [comment]
By design

**Comment by offirgolan** [comment]
I have to agree with @rafamel. Literally everything is red. 

<img width="775" alt="screen shot 2017-05-12 at 5 28 15 pm" src="https://cloud.githubusercontent.com/assets/575938/25983361/7d22d4ba-3738-11e7-8f82-efe85ca4e345.png">
<img width="540" alt="screen shot 2017-05-12 at 5 28 35 pm" src="https://cloud.githubusercontent.com/assets/575938/25983362/7d262a3e-3738-11e7-8dfd-2193ab927e1f.png">

I absolutely love this theme but find the JS syntax to be unreadable.

**Comment by Binaryify** [comment]
Everyone's aesthetic is different, so I provide this DOCS to help everyone to DIY
https://binaryify.github.io/OneDark-Pro

**Comment by will-stone** [comment]
@binaryify the whole point of this theme is to mimic One Dark. Surely we can try to change this?

**Comment by Binaryify** [comment]
@will-stone 
Of course you can

**Comment by will-stone** [comment]
After fixing all the workbench theme, providing a new logo, and correcting all the documentation, I kinda feel like I'm taking over. I've also checked out the JS theme vs Atom's and it is quite drastically different to yours. I'm going to fork the theme and maintain my own. Thanks for helping me get into world of theming.

**Comment by offirgolan** [comment]
@will-stone please link to it when you get a chance 😄

**Comment by will-stone** [comment]
@offirgolan I decided that this theme should really be the home of the One Dark clone and don't want to step on Binaryify's efforts. Therefore, please make any requests for changes to this theme here. I chose a simpler, darker look, which I prefer. I am also experimenting with deprioritising punctuation (you'll have to install to see what I mean there). Anyway, you can find the theme here: http://wstone.io/plastic/

**Comment by offirgolan** [comment]
@will-stone I think that is fair. Thank you for the update and I'll give `plastic` a shot!
