### ISSUE TITLE
Hints color for class

### ISSUE THREAD

**Issue by hugomarshall** [Binaryify/OneDark-Pro#610]
How can i change the color for class in hint ?
Looks how is showing in Visual Studio 2019:
![image](https://user-images.githubusercontent.com/4738928/134386016-21d4f1d0-15a0-44f6-a024-daf20efeefb6.png)

**Comment by Binaryify** [comment]
are you using this extension?
https://marketplace.visualstudio.com/items?itemName=adrianwilczynski.one-dark-pro
