### ISSUE TITLE
3.11.4 upgrade to 3.12.1 custom background color changes

### ISSUE THREAD

**Issue by GavinKing1995** [Binaryify/OneDark-Pro#613]
**Describe the bug**
3.11.4 upgrade to 3.12.1 custom background color changes

**To Reproduce**
1. Change custom background color
2. upgrade to 3.12.1 

**Expected behavior**
No changes to custom colors

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - VSCODE Version  [e.g. 1.60.2]
 - Theme version [e.g. 3.11.4]

**Additional context**

**Comment by Binaryify** [comment]
could you provide your settings code

**Comment by GavinKing1995** [comment]
Find the reason, other values set by Editor Theme before the upgrade, changed to One Dark Pro after the upgrade

**Comment by Binaryify** [comment]
@GavinKing1995 yes, it need reset

**Comment by Binaryify** [comment]
@GavinKing1995  just v3.12.1 have breaking change
