### ISSUE TITLE
Expand selection to quotes

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#63]
With Alt+Shift+Right Arrow or Left Arrow, VS Code has this nice expand selection feature.

For some reason it doesn't it doesn't expands to quotes properly. Ideally it should not select quotes into expansion but it does if the quotes have same color (see GIF).

I don't know how Dracula fixes this issue without changing color of the quotes, what I know is that he fixed it after I reported this to him (Dracula VS Code theme maintainer).

Please fix this expand selection to not to include quotes in your theme.

![drac](https://cloud.githubusercontent.com/assets/26769888/26022034/52c62d8c-37b7-11e7-8a67-7e4020dc05e3.gif)

**Comment by jens1o** [comment]
I like it the way it is. I wouldn't like that this changes....

**Comment by ajitid** [comment]
But if change creates consistency, then why not!

**Comment by Binaryify** [comment]
I think I had been fix it, please update and check it, thx ~

**Comment by ajitid** [comment]
No, updated the theme but didn't found it to be fixed

**Comment by Binaryify** [comment]
Can you provide your system info and your VS Code info

**Comment by ajitid** [comment]
VS Code: 1.12.1
OS: Windows 10

**Comment by Binaryify** [comment]
It work fine in my MacBook, I will check it in my colleagues  Windows 10 computer tomorrow

**Comment by ajitid** [comment]
![drac](https://cloud.githubusercontent.com/assets/26769888/26034840/85e372cc-38e0-11e7-832f-048e06144ebb.gif)
See in first string, quotes aren't selected, which is the right behavior, in the string below, quotes are selected, which is wrong.

**Comment by Binaryify** [comment]
It looks like the same color causes the problem

**Comment by ajitid** [comment]
Maybe that's the only solution

**Comment by Binaryify** [comment]
How is it now?

**Comment by ajitid** [comment]
It's working now, thanks!
