### ISSUE TITLE
Activity Bar Badge

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#64]
Please change activity bar's badge foreground and background color and command palette color to make it go well with the theme.

**Comment by jens1o** [comment]
That's already supported.

**Comment by ajitid** [comment]
That's supported but that isn't implemented in this theme

**Comment by ajitid** [comment]
Here's my take on it with theme's own colors:
    "workbench.colorCustomizations": {
      "activityBarBadge.foreground": "#1D1F23",
      "activityBarBadge.background": "#C5C5C5"
    }

![capture](https://cloud.githubusercontent.com/assets/26769888/26023734/9e13f1ba-37e0-11e7-8a12-ffab2af7a754.PNG)

**Comment by jens1o** [comment]
Ah. sorry, I didn't read `badge`.

**Comment by ajitid** [comment]
Here is my take using theme's own color theme:
"workbench.colorCustomizations": {
        "activityBarBadge.background": "#CB81DA",
        "activityBarBadge.foreground": "#1D1F23"
 }

And it looks like this:
![capture](https://cloud.githubusercontent.com/assets/26769888/26030012/524607dc-3862-11e7-8672-21d1577ef941.PNG)

Background color is taken from theme's logo.
Foreground color is taken from input box.

**Comment by Binaryify** [comment]
Could you give me more details

**Comment by ajitid** [comment]
Activity bar badges aren't colored by your theme and so takes default theme colors (blue). Same goes with command palette highlighted characters in the list items (when searched) and keyboard shortcuts that list. Both now have blue color rather than a color which goes well with the theme. Please change that.

**Comment by Binaryify** [comment]
Please update and check it

**Comment by ajitid** [comment]
Thanks color is changed now.
