### ISSUE TITLE
Editor Theme automatically changing to it's default theme

### ISSUE THREAD

**Issue by bijink** [Binaryify/OneDark-Pro#641]
Issue Type: <b>Performance Issue</b>

Sometimes reopening vs code the one dark pro editor theme automatically changing to one dark pro default editor theme.

I personally using 'Just Black' as the editor Theme in my vs code.
But sometimes I open vs code, the editor theme looks like the default editor theme of one dark Pro ('one dark Pro'). But in extensions settings, it shows the theme is in 'Just Black'.

Note: I think this issue is not only followed by extension updates.

Extension version: 3.13.2
VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:11:02.929Z)
OS version: Linux x64 5.11.0-37-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 1651)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|3.72GB (0.28GB free)|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Binaryify** [comment]
you can check https://github.com/Binaryify/OneDark-Pro/issues/637
