### ISSUE TITLE
Selection and selection matches highlight color

### ISSUE THREAD

**Issue by imwebson** [Binaryify/OneDark-Pro#65]
Selection and selection matches highlight color is too light and  too shallow, maybe a little deeper will be better~

**Comment by Binaryify** [comment]
Could you give me more details

**Comment by ajitid** [comment]
@imwebson is talking about these selection highlights which are barely visible:
![capture](https://cloud.githubusercontent.com/assets/26769888/26114616/5c648caa-3a7b-11e7-898e-57a349b08750.PNG)
![captur2e](https://cloud.githubusercontent.com/assets/26769888/26114615/5c3633a0-3a7b-11e7-89ef-d539ff605bfb.PNG)

**Comment by JiGuangYuan** [comment]
I think selection matches highlight color maybe deeper，Still a bit unclear ...
![tim 20170527171020](https://cloud.githubusercontent.com/assets/22188316/26520141/7b033f08-42ff-11e7-820b-8019b83cabec.png)

**Comment by jens1o** [comment]
You can still change it in your user settings, personally, I had reversed the effects.

Go to your User Settings, and enter: 
```json
"workbench.colorCustomizations": {
     "editor.lineHighlightBackground": "#2C313A"
},
```
