### ISSUE TITLE
Highlighting on react fragment short syntax

### ISSUE THREAD

**Issue by clarkdo** [Binaryify/OneDark-Pro#651]
**Describe the bug**

The highlighting style for React Fragment short syntax is incorrect

**To Reproduce**
1. Use below code 
2. Enable One Dark Pro color theme
3. The Highlighting style is correct

**Expected behavior**

The Highlighting style is shown same as other tag which has name

**Screenshots & Example Code**

```jsx
export const Foo = () => {
  return (
    <>
      <td>Foo</td>
      <td>Foo</td>
    </>
  );
};

export const Bar = () => {
  return (
    <>
      <td>Hello</td>
      <td>World</td>
    </>
  );
};
```

![image](https://user-images.githubusercontent.com/4312154/140536405-1730ed4a-5956-456d-8c79-5de4754661be.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version 1.58.1 
 - Theme version 3.11.3

**Comment by Binaryify** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/12221718/140672792-1f43f577-1060-4d05-a65e-9f5cd11cc531.png)
are you using other extensions

**Comment by clarkdo** [comment]
Sorry, I found the issue is from [vscode-babel-coloring](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring), closing this now.
