### ISSUE TITLE
Improve Parameter hint highlight

### ISSUE THREAD

**Issue by tjx666** [Binaryify/OneDark-Pro#656]
**Describe what you want**
A clear and concise description of what you want.

For now, distinction between current parameter with others is not much.

![image](https://user-images.githubusercontent.com/41773861/143479630-2d01aafb-d0f6-4057-ba22-b30a24d3c5c9.png)

This can be setting by https://code.visualstudio.com/updates/v1_62#_parameter-hint-highlight

**Comment by Binaryify** [comment]
plz check v3.13.5~

**Comment by tjx666** [comment]
nice work. @Binaryify 

![image](https://user-images.githubusercontent.com/41773861/143680606-07f511ba-48fa-4985-b07e-bf9030c82392.png)
