### ISSUE TITLE
Are C++ variables supposed to be white now?

### ISSUE THREAD

**Issue by Fry98** [Binaryify/OneDark-Pro#658]
I know there've been some changes made to the C/C++ coloring in recent commits but are variables really supposed to be white since version 3.13.4? Variables in all other languages are highlighted as red, aren't they? It seems especially inconsistent considering that function parameters are still red which leads me to believe this might be a bug. Can't be entirely sure though.

#### Version 3.13.3 and before:
![image](https://user-images.githubusercontent.com/31852506/143729005-f76d77bc-262f-4472-8a7f-d72b7a8fb6bc.png)

#### Version 3.13.4 and after:
![image](https://user-images.githubusercontent.com/31852506/143729009-cde6be41-3374-488d-902e-ce041b0dc556.png)

**Comment by Danny2003** [comment]
It must be a BUG!!!

**Comment by Binaryify** [comment]
@Fry98 @Danny2003 
Should C/C++/C# variables be red?

**Comment by Danny2003** [comment]
@Binaryify 
Personally, I have adapted to red C++ variables in the previous versions of this theme.
And I believe most users have got used to red C++ variables.
Another reason for red C++ variables is that in other languages such as Javascript, variables are still red.
So this is at least not coherent.
Therefore I consider it as a bug and I wish people who develop this version can see this comment and change the colour.
Thanks!!!

**Comment by Binaryify** [comment]
discussion link

**Comment by Danny2003** [comment]
@Binaryify Thanks! The colour is red now!
