### ISSUE TITLE
Block cursor contrast with text is poor

### ISSUE THREAD

**Issue by silesky** [Binaryify/OneDark-Pro#66]
![image](https://cloud.githubusercontent.com/assets/5115498/26076211/9379a904-397d-11e7-95a4-fd26cbe1fd1a.png)

This issue makes it difficult to use this theme with a Vim Plugin.
edit: VSCode recently added this option as a workaround:

```
"workbench.colorCustomizations": {
  "editorCursor.foreground": "#fff000", // e.g highlight cusor color
  "editorCursor.background": "#000000" // e.g highlight text color
  },
```

However, it might be a good idea to modify the defaults so users don't run into this issue.

**Comment by Binaryify** [comment]
You are right, but I will set "editorCursor.foreground" to be #f8f8f0

**Comment by kaosmos** [comment]
I second the `#f8f8f0` color for the , also I'd like to have more contrast in the current line highlight color, i.e. the editor.lineHighlightBackground.
I propose `"editor.lineHighlightBackground": "#383E4A"`

**Comment by Binaryify** [comment]
@silesky 
@kaosmos 
I improve it

**Comment by kaosmos** [comment]
Wow it was fast :)
DO you think is possible to improve the contrast also in the Command Palette?

**Comment by kaosmos** [comment]
I found the color customization for the Command Palette, actually it is the background color for every highlighted list element:

"list.focusBackground": "#383E4A"

![onedarkpro__commandpalette](https://cloud.githubusercontent.com/assets/138006/26194866/274ceebe-3bba-11e7-83da-546e567bfea8.png)

**Comment by Binaryify** [comment]
Done

**Comment by kaosmos** [comment]
Cool, I think this issue could be closed
