### ISSUE TITLE
Add an option not to highlight variable references but only declarations/definitions

### ISSUE THREAD

**Issue by 0liu** [Binaryify/OneDark-Pro#662]
**Describe what you want**
In VSCode this theme highlights variable references in the same color (coral red) as variable declarations/definitions. In some cases, such as when variables are referenced many times in a code block, the visual effect is a large area of red on screen and it's not easy to tell the definitions out of references. Another case is when assigning local variables to keyword arguments in Python, in which both argument names and values are in red and look basically the same, unless `Italic` options is turned on.

My request is to have an option that disables highlighting variable references, so definitions are in red and references are in plain white color. In this way the definitions/declarations easily stand out at first glance. It would be great to keep function calls blue unchanged.

**Additional context**
The attached screenshot compares the highlighting effects between Emacs and VSCode with one dark pro themes. This [SO post](https://emacs.stackexchange.com/questions/16750/better-syntax-higlighting-for-member-variables-and-function-calls-in-cpp-mode) shows an Atom screenshot. It looks local variables are not highlighted in Atom either, just obj members are highlighted. As the first answer points out, "The purpose of syntax highlighting in text editors is to make important code structures stand out." IMHO, variable declarations/definitions are more important than their uses, so they should be made stand out of their references. But for highlighting function calls, this one dark pro theme in VSCode make them blue and it definitely looks better than the Emacs one.

<img width="1915" alt="Screenshot_20211207" src="https://user-images.githubusercontent.com/4315932/145115718-d31c38e9-1ca6-45b9-a2e9-e2ca992e9844.png">

**Comment by Binaryify** [comment]
could you provide some code

**Comment by skilkis** [comment]
@0liu for the time being you could add the following in `settings.json`:

```json
  "editor.semanticTokenColorCustomizations": {
    "[One Dark Pro Flat]": {
      "rules": {
        "variable:python": "#ABB2BF", 
        "property:python": "#ABB2BF",
        "module:python": "#ABB2BF",
      }
    }
  },
```

**Comment by skilkis** [comment]
@0liu it's possible to differentiate between module constants as well with the following rule, but not between global and local variables 😞

```json
  "variable.readonly:python": "#D19A66"
```
To customize the semantic token colors further you can use the VS Code command: `Developer: Inspect Editor Tokens and Scopes` which will bring up a window with token information you can then use to customize the color.

![image](https://user-images.githubusercontent.com/29230371/168845224-1a636d6d-c24a-4e7a-b7d3-3305a369ff6c.png)

Using the above, I had made a configuration for myself that I've included below. Feel free to adapt / extend it! Happy hacking 😄 

```json
  "editor.semanticTokenColorCustomizations": {
    "[One Dark Pro Flat]": {
      "rules": {
        "variable:python": "#ABB2BF",
        "variable.readonly:python": "#D19A66",
        "property:python": "#ABB2BF",
        "module:python": "#ABB2BF",
        "*.builtin:python": "#56B6C2",
        "intrinsic:python": "#e06c75",
        "module.decorator:python": "#61AFEF",
        "property.decorator:python": "#61AFEF"
      }
    }
  },
```

**Comment by 0liu** [comment]
@skilkis Thank you for the guide! With the following settings, I got exactly what I want:
```json
    "editor.semanticTokenColorCustomizations": {
        "[One Dark Pro Flat]": {
          "rules": {
            "variable:python": "#ABB2BF",
            "variable.declaration": "#e06c75",
            "property:python": "#ABB2BF"
          }
        }
      }
```
