### ISSUE TITLE
PHP 8 named arguments color

### ISSUE THREAD

**Issue by asolux** [Binaryify/OneDark-Pro#663]
There are a mish mash coloring for the [PHP 8 named arguments](https://wiki.php.net/rfc/named_params).

Screenshot:
![Unbenannt-1](https://user-images.githubusercontent.com/31314283/145473473-709442c4-f2ed-41f0-9cff-48d25bc85bb2.png)

For reproduction:
```php
<?php

sample('string', param: 1);
figure(sprintf('pattern %d', 1), param: 1);
type(Class::func(), param: 1);
throw new \Exception(sprintf('pattern %d', 1), param: 1);
type(
    Class::func(), 
    param: 1
);
throw new \Exception(
    "Error Processing Request",
    param: 1,
    option: 0
);
Class::func('string', mode: 0);
type(Class::func(), param: 1);
```

Screenshot of the code above:
![Code_78RC6Ix1z4](https://user-images.githubusercontent.com/31314283/145475212-071b7156-e6a0-4687-ab39-480f6aa5a2d9.png)

Thank you for your great work!

**Comment by Binaryify** [comment]
is this what you want 
![image](https://user-images.githubusercontent.com/12221718/145708251-7fe439c1-a48a-46f7-8311-c6b4729367dd.png)

**Comment by asolux** [comment]
You forgot the colons. 😀😉
I am not familiar with the color themes. But as far as I have seen the "php 8 named arguments" cannot be identified. The orange colored ones are constants? Am I correct? I personally would like it in gray - or I would change it to gray. However, if they cannot be identified, that is not possible. (?)

![Code_BKI3L5isj4](https://user-images.githubusercontent.com/31314283/145713611-c253530b-7e91-4302-b153-d07bbb919869.png)
![Code_BlsWgpf2LM](https://user-images.githubusercontent.com/31314283/145713615-f786b062-b012-467b-a51e-17e54eba5cdc.png)
![Code_un8zvoln8m](https://user-images.githubusercontent.com/31314283/145713620-b36949cb-2911-4bdb-8fcc-d58c8f363802.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/145810101-fd08c0f3-38ce-494e-8b11-9bb9803a2e14.png)
how about this

**Comment by asolux** [comment]
Looks good! 🙂 How can I do that?

**Comment by asolux** [comment]
Great! Seems to be working fine. However, I still added the `entity.name.goto-label.php` key.
If I notice anything else, I'll get in touch again.
Thanks!
