### ISSUE TITLE
PHP 8 enum

### ISSUE THREAD

**Issue by tianyiw2013** [Binaryify/OneDark-Pro#666]
**Describe the bug**
- `enum` keyword without coloring.
- `case keyword ` coloring incorrect

**To Reproduce**
```php
<?php
// enum keyword without coloring.
enum SettingItemType: string
{
    case STRING = 'STRING';  // Maybe it's because string is a language keyword

    case STRING__ = 'STRING'; // Normal color
}
```

**Expected behavior**
- `enum` should display colors like `class`.
- `case XXX` constants should have a uniform color

**Screenshots & Example Code**
![aaa](https://user-images.githubusercontent.com/4644588/145676743-66f54cd5-9d80-4268-b961-5cf22cf6ea93.png)

**Desktop (please complete the following information):**
 - OS: win10
 - VSCODE Version 1.63.0
 - Theme version v3.13.6

**Additional context**

**Comment by Binaryify** [comment]
that might be vscode's php extension issues
![image](https://user-images.githubusercontent.com/12221718/145708546-159a899f-66a4-48bb-a4c2-a76b6479cd10.png)
![image](https://user-images.githubusercontent.com/12221718/145708551-8b29037d-3263-4454-9412-3de5f0a285f8.png)
![image](https://user-images.githubusercontent.com/12221718/145708553-59d0c716-46d9-4e19-984d-e961297eb47c.png)
![image](https://user-images.githubusercontent.com/12221718/145708556-529dd653-5db6-4875-a9c9-e036b99f8b90.png)

**Comment by tianyiw2013** [comment]
I got it!
