### ISSUE TITLE
Python docstrings

### ISSUE THREAD

**Issue by GBrachetta** [Binaryify/OneDark-Pro#667]
Until recently I could differentiate between python docstrings and normal strings within the code.
I'm not sure if a change in VSCode on in your extension changed this behaviour.

I want to have docstrings in the same colour as comments, like so:

<img width="586" alt="Screenshot 2021-12-15 at 23 36 37" src="https://user-images.githubusercontent.com/57924268/146275618-3d69415f-2149-4eee-b60a-0283a5318ada.png">

but now the opening and closing quotes of **normal** strings also get the same tokenisation:

<img width="370" alt="Screenshot 2021-12-15 at 23 45 33" src="https://user-images.githubusercontent.com/57924268/146276622-529921e6-0534-4031-8ab9-0de72f70b45d.png">

(please see the quotes with a mismatch colour: I would like them to be green (same as the string is) while the ones on the docstring remain grey).

This used to be my textMate rule for that scope:

```json
{
  "name": "Python - Docstrings",
  "scope": [
    "string.quoted.docstring.multi.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.begin.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.end.python",
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#7c7a7a"
  }
},
```

But it's not working anymore.

Am I missing anything or is this a change on VSCode's site or your extension?

Thanks!

**Comment by Binaryify** [comment]
could you provide some code

**Comment by GBrachetta** [comment]
Sure.

In the following dummy code:

```
def my_function():
    """
    This is my docstring.
    """

    # This is my comment

    my_variable = "This is my variable"
```

- The docstring and the comment should have the same color, like so:

<img width="321" alt="Screenshot 2021-12-16 at 09 58 12" src="https://user-images.githubusercontent.com/57924268/146340140-727a0d74-5031-436b-a54f-0f7177a0e0cb.png">

- The string in the variable should be different, like so:

<img width="440" alt="Screenshot 2021-12-16 at 09 59 45" src="https://user-images.githubusercontent.com/57924268/146340354-f7b77e34-fcfd-4bc4-ac45-79d53b7dfbdd.png">

However, with the rules in place, this is the result:

<img width="470" alt="Screenshot 2021-12-16 at 10 00 42" src="https://user-images.githubusercontent.com/57924268/146340552-fd7837c3-3d3c-402e-9517-120ebfe4be3c.png">

The quotes around `This is my variable` are the same grey colour as the ones in the docstring.

This was not the beheavior before, and the following textMate rule took care of it:

```json
{
  "name": "Python - Docstrings",
  "scope": [
    "string.quoted.docstring.multi.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.begin.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.end.python",
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#7c7a7a"
  }
},
```

But now this rule seems not to have any effect anymore.

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/146349206-371cfb89-d009-4bb4-9cb4-a088eb55bbe2.png)
can't reproduce, did you install some python extensions

**Comment by GBrachetta** [comment]
Well, what I'm actually looking for is to have the docstring (lines 2-4) coloured `grey`, same as line 6.

It was possible before with 

```json
{
  "name": "Python - Docstrings",
  "scope": [
    "string.quoted.docstring.multi.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.begin.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.end.python",
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#7c7a7a"
  }
},
```

But now this rule has **no effect anymore**.

The closest I can get to it now is with the following rule:

```json
{
  "name": "Python - Docstrings",
  "scope": [
    "string.quoted.double.block.python",
    "punctuation.definition.string.end.python",
    "punctuation.definition.string.begin.python"
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#7c7a7a"
  }
},
```

But this colours `grey` **also the quotes in normal strings, not just docstrings**.

The python extension I have installed currently is ms-python.python (default one by Microsoft).

**Comment by Binaryify** [comment]
are you really using One Dark Pro theme, I can't reproduce in my VS Code

**Comment by GBrachetta** [comment]
Yes, that's One Dark Pro, but this happens regardless of the theme (i.e. it's the same on any theme).

So do you manage to have different colors for docstrings and normal strings?

Do you mind sharing a screenshot to make sure we're on the same page?

**Comment by Binaryify** [comment]
in my vscode, they have same color
![image](https://user-images.githubusercontent.com/12221718/146361279-70a64893-a597-4be9-860a-2984cc128d52.png)
you could also try install pylance extension

**Comment by GBrachetta** [comment]
Yes, exactly. I want the docstring (lines 2-4) to have a **different** color from the string in line 8.

As I tried to explain, this was possible before with:

```json
{
  "name": "Python - Docstrings",
  "scope": [
    "string.quoted.docstring.multi.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.begin.python",
    "string.quoted.docstring.multi.python punctuation.definition.string.end.python",
  ],
  "settings": {
    "fontStyle": "italic",
    "foreground": "#7c7a7a"
  }
},
```

**Comment by GBrachetta** [comment]
And yes, Pylance is installed.

**Comment by Binaryify** [comment]
oh, I misunderstood your meaning
if they have same scope, they have same color, so if you want them have different color, they must have different scope
you can create a issue to pylance repo

**Comment by GBrachetta** [comment]
I don't think it's a Pylance issue.

Here's a screenshot with the default `Dark+ (default dark)` theme:

![Screenshot 2021-12-16 at 12 36 40](https://user-images.githubusercontent.com/57924268/146365090-76d9c3fc-bbdd-4ca9-9cd7-80a9dd85e933.png)

`Docstrings are correctly colored`.

And here's a screenshot with `One Dark Pro`:

![Screenshot 2021-12-16 at 12 37 07](https://user-images.githubusercontent.com/57924268/146365173-c5c2f92c-9c7e-414b-bc90-a7dcbe480bdf.png)

`The quotes on the docstring (line 2 and line 4) are incorrectly colored`

This is with the following rules:

```json
"editor.tokenColorCustomizations": {
    "textMateRules": [
        {
            "name": "Docstrings Python",
            "scope": [
                "string.quoted.double.block.python",
                "string.quoted.docstring.multi.python"
            ],
            "settings": {
                "foreground": "#7c7a7a",
                "fontStyle": "bold"
            }
        }
    ]
}
```


So the quotes **in the docstring** are correct with other themes, but not with One Dark Pro

**Comment by Binaryify** [comment]
ok, I will check that

**Comment by Binaryify** [comment]
please check v3.13.7, and give me some feedback if you can~

**Comment by GBrachetta** [comment]
Yes, this is it!
Absolutely brilliant, thanks so much for fixing this and so quickly! 💯
