### ISSUE TITLE
Support for assembly syntax

### ISSUE THREAD

**Issue by jgcodes2020** [Binaryify/OneDark-Pro#668]
**Describe what you want**
I use [this extension](https://marketplace.visualstudio.com/items?itemName=13xforever.language-x86-64-assembly) for syntax highlighting of assembly. This extension seems to choose not to highlight too much without language specifics, so it doesn't highlight this code well.

**Additional context**
Picture with One Monokai:
![image](https://user-images.githubusercontent.com/35639051/147183903-c27603db-63c9-4698-97f3-076970df3d04.png)

Picture with current One Dark Pro (Darker):
![image](https://user-images.githubusercontent.com/35639051/147183950-fd0bebcf-d22c-4f19-9157-91ca497c420c.png)

**Comment by Binaryify** [comment]
could you provide some code

**Comment by Binaryify** [comment]
![code](https://user-images.githubusercontent.com/12221718/147400688-fa9c6b7a-8ad0-4017-aed2-98973090c43c.png)
how about this

**Comment by jgcodes2020** [comment]
this is what i was thinking

**Comment by Binaryify** [comment]
plz check v3.13.8~

**Comment by jgcodes2020** [comment]
seems good. I'll close the issue now.
