### ISSUE TITLE
the stripe is too bright

### ISSUE THREAD

**Issue by kidsamort** [Binaryify/OneDark-Pro#670]
I use the one dark pro flat theme precisely because it has minimal borders, but since the recent update, the terminal window has changed and I've been waiting for half a year, it constantly distracts me, could you tell me how to make the bright stripe I marked less noticeable and disturbing like the others
![image](https://user-images.githubusercontent.com/77036519/147845559-5aad223d-41c7-47f8-aae8-089f5a59cf5f.png)

**Comment by Binaryify** [comment]
you can add this in your setting.json before I release next version
```
"workbench.colorCustomizations": {
    "terminal.border": "#21252b"
  },
```

**Comment by Binaryify** [comment]
you can check v3.13.9 now~

**Comment by kidsamort** [comment]
> вы можете проверить v3.13.9 сейчас ~

thanks for such a quick revision, happy new year))

**Comment by njbbaer** [comment]
@Binaryify I'd like you to reconsider the new color you chose for this. I'm a user of OneDark Pro Darker and it's almost impossible for me to see where one terminal begins and another ends. I've overridden it back in my own settings.

I agree the old border stood out too much, but the new one should be a light gray not dark. I think would be good if it just matched `panel.border`.

**Comment by Binaryify** [comment]
@njbbaer you mean set terminal.border to  `#3e4452` or panel.border to `#3e4452`

**Comment by kidsamort** [comment]
"workbench.colorCustomizations": {
    "terminal.border": "#21252b"
  },
  I'll probably stay with these settings because I don't need light frames, I already know my ide so i use "one dark pro flat"

**Comment by kidsamort** [comment]
![image](https://user-images.githubusercontent.com/77036519/148047377-c7dc4eb2-5e0d-4112-9970-e29ea7610654.png)
maybe I'm used to it, but for me it's intuitively clear where it ends

**Comment by Binaryify** [comment]
maybe should let user custom it, it's hard to have consensus

**Comment by kidsamort** [comment]
> maybe should let user custom it, it's hard to have consensus @njbbaer @kidsamort

do what that guy wants I think it will be better for everyone and I will stay with the settings

**Comment by njbbaer** [comment]
@kidsamort The terminals are easier to distinguish when placed horizontally like that, but hard to see when stacked vertically.

![Screenshot from 2022-01-04 17-50-13](https://user-images.githubusercontent.com/5005914/148147930-ca1982a5-862f-4477-b0bf-f06726c7d57c.png)

@Binaryify This is what I have in my settings. I set `terminal.border` to match `panel.border` which is much clearer to my eyes.
```
"workbench.colorCustomizations": {
    "terminal.border": "#3e4452"
},
```
Obviously if you don't decide to change it I'll just keep these custom settings. But I assume anyone who stacks their terminals vertically like I do would want the border to stand out, at least a little bit.

![Screenshot from 2022-01-04 17-52-54](https://user-images.githubusercontent.com/5005914/148148197-fc05f92f-0555-4282-b87f-a2c7a778efcf.png)

**Comment by Binaryify** [comment]
consider set `terminal.border` and `panel.border` to "#3e4452"
what do you think 
@kidsamort  @njbbaer

**Comment by njbbaer** [comment]
Looks great, thank you! ⭐
