### ISSUE TITLE
Vivid not working after last update 

### ISSUE THREAD

**Issue by kossa** [Binaryify/OneDark-Pro#671]
**Describe the bug**
Vivid not working after latest update

**To Reproduce**
1. Install new vs code
2. Install One dark pro
3. Active "One Dark Pro Flat"
4. Active vivid
5. Restart vs code

**Expected behavior**
Vivid active with great colors

**Screenshots & Example Code**

![image](https://user-images.githubusercontent.com/1175584/147920453-c1dc8d45-27b0-4cb0-a693-6bc64b0a4254.png)
The left side is the current version, the right side is the old version(from clipboard) 

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version 1.63.2
 - Theme version v3.13.9

**Comment by Binaryify** [comment]
try close all vscode window then try again

**Comment by kossa** [comment]
Still the same issue

**Comment by Binaryify** [comment]
try re-install

**Comment by kossa** [comment]
Removed and Reinstalled the theme, the same issue

**Comment by kossa** [comment]
I think my issue is related to vscode, which does not follow the color profile

**Comment by kossa** [comment]
Issue was with` "disable-color-correct-rendering": true` more info here : https://github.com/microsoft/vscode/issues/84154#issuecomment-552344530
