### ISSUE TITLE
Turn on vivid colors

### ISSUE THREAD

**Issue by kossa** [Binaryify/OneDark-Pro#676]
**Describe the bug**
I cannot activate vivid, even I reinstalling the Theme

**Screenshots & Example Code**

![image](https://user-images.githubusercontent.com/1175584/149760024-4c4c3efd-b5c0-46ae-9903-be25f1e0c404.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version: 1.63.2 
 - Theme version 3.13.13

**Comment by Binaryify** [comment]
will rollback version now

**Comment by kossa** [comment]
Alright

![image](https://user-images.githubusercontent.com/1175584/149774904-9824da3e-19a8-4087-b5f2-56f5fe39da10.png)

![image](https://user-images.githubusercontent.com/1175584/149774926-cac8a587-347e-44d2-8258-6a1d13feab38.png)

**Comment by Binaryify** [comment]
plz update to v3.13.15~

**Comment by kossa** [comment]
Yes fixed with v3.13.15
