### ISSUE TITLE
Add Support for C# XML documentation highlight

### ISSUE THREAD

**Issue by Hangary** [Binaryify/OneDark-Pro#679]
**Describe what you want**

Currently, C# XML documentation would be treated as plain comments and not be highlighted. 

Current bahavior:
![image](https://user-images.githubusercontent.com/37897741/149900950-eb6dc507-f9c9-4e00-be07-fbad7442be8b.png)

Desired behavior:
![image](https://user-images.githubusercontent.com/37897741/149900854-8811c863-5235-4e13-9995-2a486b28a1d9.png)

**Additional context**

This can be easily achieved by adding following rules:
```JSON
"[One Dark Pro]": {
        "textMateRules": [
            {
                    "scope": "comment.documentation",
                    "settings": {
                        "foreground": "#608B4E",
                    }
                },
                {
                    "scope": "comment.documentation.attribute",
                    "settings": {
                        "foreground": "#C8C8C8",
                    }
                },
                {
                    "scope": "comment.documentation.cdata",
                    "settings": {
                        "foreground": "#E9D585",
                    }
                },
                {
                    "scope": "comment.documentation.delimiter",
                    "settings": {
                        "foreground": "#808080",
                    }
                },
                {
                    "scope": "comment.documentation.name",
                    "settings": {
                        "foreground": "#569CD6",
                    }
                },
      ]
    }
```

Reference: https://github.com/OmniSharp/omnisharp-vscode/issues/3816

**Comment by Binaryify** [comment]
could you provide some code

**Comment by e-potashkin** [comment]
Example from One Dark Pro in JetBrains Rider

<img width="392" alt="Screenshot 2022-02-15 at 08 29 01" src="https://user-images.githubusercontent.com/14278977/154005237-8204038e-86aa-4c1b-9b7a-c67fef62cec6.png">

**Comment by Binaryify** [comment]
it's look like this now
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12221718/154018891-819cdee9-ccd6-4fd0-bad9-b692a5fb7eb2.png">

**Comment by Hangary** [comment]
It looks it has been done. Thank you!
