### ISSUE TITLE
Inconsistency in javascript Object methods

### ISSUE THREAD

**Issue by lerran80** [Binaryify/OneDark-Pro#68]
In the javascript code:
const a = [...Object.keys(b)]
const c = Object.keys(b)

"Object" has different colors in each line:
![screen shot 2017-05-16 at 11 46 46](https://cloud.githubusercontent.com/assets/22422447/26112142/6644f0f0-3a2d-11e7-8962-28b2c9fb730a.png)

**Comment by Binaryify** [comment]
It look like you don't apply my theme

**Comment by lerran80** [comment]
Oops, that is right. The problem seems to be I cannot load your theme in VS code v 1.12.2.

**Comment by Binaryify** [comment]
You can uninstall and reinstall it

**Comment by Binaryify** [comment]
It's a little hard to change them to the same color, it will affect other code

**Comment by lerran80** [comment]
Makes sense, I see the same issue with other themes. And also in other situations, like key names in maps, their colors are not always consistent for any theme I tested. Is this something that the VS Code dev team could fix?

**Comment by lerran80** [comment]
BTW: I tried uninstalling and reinstalling, restarting, disabling and re-enabling. Nothing works. I just can't load your theme.

**Comment by Binaryify** [comment]
Does you apply it ?
![image](https://cloud.githubusercontent.com/assets/12221718/26186192/5fd4a86e-3bc2-11e7-90f0-d4946679f7fc.png)

**Comment by lerran80** [comment]
Nope. I was just enabling it and expected this would be sufficient for VS Code to understand I wanted it applied. Totally forgot this step. Thanks!
