### ISSUE TITLE
Terminal Text Color Does Not Show on MacOS

### ISSUE THREAD

**Issue by Blossme233** [Binaryify/OneDark-Pro#680]
**Describe the bug**
The text color did not change in the terminal: zsh, bash, R and so on.

**To Reproduce**
1. Download One Dark Pro from extension
2. Select One Dark Pro as prefered theme
3. Text color of theme did not change

**Expected behavior**
Text color in terminal

**Screenshots & Example Code**
![image](https://user-images.githubusercontent.com/57247579/150241149-09b8de5e-af0c-4be1-9351-c2cccf674cb1.png)
![image](https://user-images.githubusercontent.com/57247579/150241162-f3cdc9d1-a162-48bc-ada4-c08824c1881d.png)

**Desktop (please complete the following information):**
 - OS: [Monterey 12.1]
 - VSCODE Version  [1.63.2]
 - Theme version [3.13.16]

**Comment by Binaryify** [comment]
I think it might be vscode's issue, switch to other theme also show this problem

**Comment by zhihuat** [comment]
Have the same problem:(

**Comment by andrewcincotta** [comment]
I would like to bump this issue, I am still having problems changing the terminal colors/theme
