### ISSUE TITLE
different formatting for 'IN' ?

### ISSUE THREAD

**Issue by br4n5** [Binaryify/OneDark-Pro#681]
There is a inconsistency on how ‘IN’ is formatted in the Python’s IF and FOR functions.
While the ‘IN’ in IF is, say, correctly formatted the same does not happen in the ‘IN’ in IF function.
The cobalt I use apparently works correctly:
You can check a comparison of the screenshots I have done:
https://imgur.com/ra1vicl
https://imgur.com/zHFm2tl
https://imgur.com/GkNk6At

**Comment by Binaryify** [comment]
plz check v3.13.17~
