### ISSUE TITLE
Change markdown preview font size, didn't work in this theme

### ISSUE THREAD

**Issue by comradeWong** [Binaryify/OneDark-Pro#682]
**Describe the bug**
When I used the theme to browse the Markdown file, I wanted to change the font size, but the settings didn't work.
(in VSCode)

**To Reproduce**
1. open vscode settings
2. find "markdown>preview>Font Size" and change it
3. not working in vscode

**Expected behavior**
"markdown>preview>Font Size" can be worked in the theme

**Desktop (please complete the following information):**
 - OS:  Win 11
 - VSCODE Version 1.63.2
 - Theme version v3.13.16

**Comment by Binaryify** [comment]
plz check v3.13.17~

**Comment by comradeWong** [comment]
thx~

**Comment by comradeWong** [comment]
> plz check v3.13.17~

thx~
