### ISSUE TITLE
How to change back setInterval back to similar to this 56B6C2? 

### ISSUE THREAD

**Issue by MariuzM** [Binaryify/OneDark-Pro#684]
The latest update for JavaScript (TypeScript) has made `setInterval` blue like a normal function, but i like the way it looked originally i think it's similar to #56B6C2. How do i change this back? 

`setTimeout` still looks ok, so why change `setInterval` ?

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/152087653-a2141523-6e59-4937-8b4f-e834dbdb79a9.png)
can't reproduce

**Comment by MariuzM** [comment]
Hm so strange
![Screen Shot 2022-02-02 at 13 05 44](https://user-images.githubusercontent.com/36937039/152101635-37c0070e-1140-4e50-8e4d-8fe149e4dcda.png)

**Comment by MariuzM** [comment]
maybe issue with vscode semanticHighlighting

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/152105214-a1d44e72-fb46-4b98-ba11-5a89614bb5b6.png)
did you install some js/ts extensions
