### ISSUE TITLE
Increase the background color of active menu item in dropdown

### ISSUE THREAD

**Issue by vikrantnegi** [Binaryify/OneDark-Pro#69]
When changing the project from the shortcut "cmd+p" the drop-down color and the active menu background color (see screenshot) is not quite contrasting causing difficulty in opening intended projects.

Is there an option to change the background color of the active menu so that I can see clearly which option is currently I'm on?

Thanks.

![screen shot 2017-05-18 at 13 01 38](https://cloud.githubusercontent.com/assets/3294287/26191150/515aa1be-3bca-11e7-8ea1-5468da4f52ba.png)

**Comment by Binaryify** [comment]
You can see this https://code.visualstudio.com/docs/getstarted/theme-color-reference before I improve it

**Comment by vikrantnegi** [comment]
Great but I could not find the solution for my problems there.

**Comment by Binaryify** [comment]
Done

**Comment by vikrantnegi** [comment]
Thank you very much.
