### ISSUE TITLE
key word italic font support

### ISSUE THREAD

**Issue by JzKUO** [Binaryify/OneDark-Pro#70]
It's still awesome theme. But better if the support italic or bold font to key word.

such as this following pic:
![image](https://cloud.githubusercontent.com/assets/17445719/26198886/68db0bbe-3bfa-11e7-9fca-5e0752e416cf.png)

![image](https://cloud.githubusercontent.com/assets/17445719/26199278/fcd1acfa-3bfb-11e7-9dff-432c7f6e8ffb.png)

**Comment by DenisValcke** [comment]
I think you are trying to achieve the same as in [https://github.com/Binaryify/OneDark-Pro/issues/48](this issue)?

**Comment by Binaryify** [comment]
Done

**Comment by jens1o** [comment]
@Binaryify Should I update the php syntax, so variable are getting italic, too?

**Comment by Binaryify** [comment]
@jens1o 
It's up to you

**Comment by jens1o** [comment]
Hmm, I'll check in which ways it fits.

**Comment by dapullar** [comment]
This makes me sad, can this be optional?

**Comment by Binaryify** [comment]
@dapullar 
Temporarily no, but you can DIY this theme with this DOCS https://binaryify.github.io/OneDark-Pro/#/
