### ISSUE TITLE
Incorrect badge title names in main README.md

### ISSUE THREAD

**Issue by ashwin2125** [Binaryify/OneDark-Pro#700]
**Describe the bug**
The badge in README.md has "Preview in VSCode" as the  title for all the badges, instead of their respective appropriate badge names.

**To Reproduce**
1. On Project Repository - Home directory, open [README.md](https://github.com/Binaryify/OneDark-Pro/#readme)'s raw file.
2. In the line 4, we can see that all badges have same title.
3. Practically, this won't cause any error - however it is nice to have a clean and logical code in README.md

**Screenshots & Example Code**

![image](https://user-images.githubusercontent.com/47941624/158090908-cb58dd5c-4fbb-428b-8efd-c78ff1c732ca.png)

**Comment by Binaryify** [comment]
thank for the help~
