### ISSUE TITLE
Add separate tokenization in JS imports to differentiate function imports against others

### ISSUE THREAD

**Issue by GBrachetta** [Binaryify/OneDark-Pro#709]
**Describe what you want**
It would be great if you could add a different token in imports if they are functions/components or just normal constants (objects, for example).

**Additional context**
Currently this is how it looks by default:

![Screenshot 2022-04-02 at 13 10 24](https://user-images.githubusercontent.com/57924268/161380638-24b01408-11d2-48b5-914b-682fcdbe0972.png)

But `COLORS`, `SHADOWS` and `SIZES` are objects:

![Screenshot 2022-04-02 at 13 11 18](https://user-images.githubusercontent.com/57924268/161380644-d31969f6-dfa0-44af-88f1-ea1516c06214.png)

And the others are functions (components in this case):

![Screenshot 2022-04-02 at 13 11 33](https://user-images.githubusercontent.com/57924268/161380652-86ca3772-5ac6-4d0d-9ec8-f558641052be.png)

It would be great to be able to tell them apart and have **the chance to assign them a different color**, the same way the extension [Babel JavaScript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) shows them, see below:

![Screenshot 2022-04-02 at 13 13 32](https://user-images.githubusercontent.com/57924268/161380672-4edbe58b-f684-452b-b727-7d857822acb9.png)

However I prefer **not to install that Babel extension** and use only **your theme** because `Babel JavaScript` doesn't allow to personalize those colors.

Maybe if you add that different token to the type of import, we would be able to do it.

**Comment by Binaryify** [comment]
a theme should't change the code scopes, and that's vscode's js language server‘s job or other kind extension's job
I think you should create an issue to vscode's repo

**Comment by GBrachetta** [comment]
Ah! I thought it would be more straightforward to be able to differentiate between the two types and give them a different identifier so they could be colorized differently. 😞
