### ISSUE TITLE
Comments color

### ISSUE THREAD

**Issue by zprjk** [Binaryify/OneDark-Pro#713]
**Describe the bug**
The Comments color seems off put in `One Dark Pro` Theme.  It wasn't like this before. Picking `One Dark Pro Darker` the colouring goes back like before (more grayish). 

https://user-images.githubusercontent.com/9919760/164414975-18c58544-9f58-4caa-863b-3af1e48075c8.mp4

<img width="630" alt="image" src="https://user-images.githubusercontent.com/9919760/164415201-798f78cb-257f-46ef-8918-1fdd8dfe7258.png">

<img width="626" alt="image" src="https://user-images.githubusercontent.com/9919760/164415547-9fa341a5-7d9b-4179-9a6e-7b783139e56c.png">

**Expected behavior**
I expected the comments colouring more grayish.

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version: v1.66.2
 - Theme version: v3.13.22

**Comment by zprjk** [comment]
I've being using the `One Dark Pro` theme since my first extension installation. If this not a bug can I override the color? 

Many Thanks.

**Comment by Binaryify** [comment]
it is a bug, will fix it soon

**Comment by Binaryify** [comment]
plz check  v3.13.23 later

**Comment by zprjk** [comment]
Fixed. Thx !
