### ISSUE TITLE
关于 one dark pro darker 的斜体注释

### ISSUE THREAD

**Issue by zhiyiYo** [Binaryify/OneDark-Pro#714]
有什么办法可以把 one dark pro darker 的注释字体换成斜体字吗，normal 看的有点不舒服

**Comment by Binaryify** [comment]
昨天有个版本有问题，斜体会不生效，你现在再看看
<img width="967" alt="image" src="https://user-images.githubusercontent.com/12221718/164580119-094b5d81-6222-40bc-8521-db8618aee4dc.png">

**Comment by zhiyiYo** [comment]
我刚才更新了插件，目前版本为 v3.13.24，但是使用 one dark pro darker 主题后注释仍然不是斜体的
![image](https://user-images.githubusercontent.com/65096819/164588046-c5dc7a62-16be-4354-9656-4319e92a8601.png)

**Comment by zhiyiYo** [comment]
我把设置斜体的选项关闭又打开之后，斜体又恢复正常😇
![image](https://user-images.githubusercontent.com/65096819/164589967-40d0fed9-8d44-413d-8057-add366a41c34.png)
