### ISSUE TITLE
Can you make the active tab more prominent?

### ISSUE THREAD

**Issue by zeroxia** [Binaryify/OneDark-Pro#723]
Most of dark themes just keep the tab bar as dark as possible, and I find myself often very hard to identify which tab is active among several tabs.

The difficulty of discriminating the active one from others is not that obvious in the screenshot, but it is really obscure when you are on a high-resolution monitor.

![active tab not prominent](https://i.imgur.com/ElHSUMJ.png)

**Comment by Binaryify** [comment]
you can add this in your setting.json
```json
 "workbench.colorCustomizations": {
    "tab.activeBorder": "#fff"
  },
```

**Comment by zeroxia** [comment]
> 

Thanks, this does help a lot.
Now the tab has a white line at the bottom.
Just curious, why isn't there a rectangular white box around the box?

**Comment by Binaryify** [comment]
the first time I use this, it's make me confuse too
also you can try `"tab.activeBorderTop": "#fff"`, I think it's not a good design

**Comment by zeroxia** [comment]
> the first time I use this, it's make me confuse too also you can try `"tab.activeBorderTop": "#fff"`, I think it's not a good design

Great! This is even better, I reckon these are not present:

```json
{
        "tab.activeBorderLeft": "#ffffff",
        "tab.activeBorderRight": "#ffffff"
}
```

**Comment by Binaryify** [comment]
yep

**Comment by zeroxia** [comment]
There is some discussion on customization of the active tab bar:

https://stackoverflow.com/questions/59121072/is-there-a-way-of-making-the-active-tab-border-highlighted-on-top-instead-of-at

I'm currently setting it like this, it looks ugly, but it's more useful for me to know which tab is the active one...
```json
    "workbench.colorCustomizations": {
        // "tab.activeBorder": "#ffffff",
        // "tab.activeBorderTop": "#ffffff",
        // "tab.activeForeground": "#000000",
        // "tab.inactiveForeground": "#888888",
        "tab.activeBackground": "#051ca2"
    },
```
