### ISSUE TITLE
Improve One dark pro flat by including these to the theme json file

### ISSUE THREAD

**Issue by Tetrax-10** [Binaryify/OneDark-Pro#726]
in some places, the theme is not flat. so I used to include these properties in my settings.json file. I have no idea how to make and modify using a pull request. so anyone who loves this theme make a pull request with changing these properties.

"scrollbar.shadow": "#282c34",
"sideBar.border": "#282c34",
"tab.activeBorder": "#b4b4b4",
"statusBar.debuggingBackground": "#282C34",
"statusBar.debuggingBorder": "#282C34",
"statusBar.debuggingForeground": "#969aa4",
"statusBar.noFolderBackground": "#282c34",
"statusBarItem.warningBackground": "#282c34",
"statusBarItem.warningForeground": "#b78853",
"statusBarItem.remoteForeground": "#969aa4",
"statusBar.border": "#282c34",
"focusBorder": "#282c34",

**Comment by Binaryify** [comment]
could you provide some screenshots to show the different of the before and after

**Comment by Tetrax-10** [comment]
[one dark pro flat fix images.zip](https://github.com/Binaryify/OneDark-Pro/files/8622615/one.dark.pro.flat.fix.images.zip)

I have Grouped them clearly one by one.

**Comment by Binaryify** [comment]
great~
In my opinion, I will keep the old sideBar.border color, they still need to be distinguished

**Comment by Binaryify** [comment]
just release a new version, you can check it now~

**Comment by Tetrax-10** [comment]
perfect!
