### ISSUE TITLE
Colorized Bracket Pairs support

### ISSUE THREAD

**Issue by mciesin** [Binaryify/OneDark-Pro#728]
**Describe what you want**
Starting from version 1.67.0, Colorized Bracket Pairs are enabled by default in VS Code. Colors which are used for that feature still have default values and they look off when using One Dark Pro theme.

**Additional context**
<img width="149" alt="Bracket Pairs" src="https://user-images.githubusercontent.com/3732286/167120268-681ad773-cdbf-4723-9fb1-fa2e69cde59f.png">

**Comment by julian-poidevin** [comment]
I just updated to 1.67.0 also and went right away here to request the support, default settings are not very beautiful.

**Comment by Binaryify** [comment]
I have no idea to how to make it look good, and I just close the Colorized Bracket Pairs  after the vscode updated, do you have any idea?

**Comment by mciesin** [comment]
@Binaryify As far as I can tell by looking over [here](https://github.com/microsoft/vscode/blob/70e50659a1b95bf355660b47389272ae4bbe008d/src/vs/editor/common/core/editorColorRegistry.ts#L57), there are only three levels of nesting implemented with defaults currently. I would replace the default shades of yellow, pink and blue with the colors that are defined as `chalky`, `purple` and `malibu` in this project, by using `editorBracketHighlight.foreground1`, `editorBracketHighlight.foreground2` and `editorBracketHighlight.foreground3`.

IMO, it would make the overall look and feel much more pleasant for people willing to stay with colorized bracket pairs.

**Comment by mciesin** [comment]
You can check these values out (or some of you - leave it as a workaround) by overriding the theme's configuration in your VS Code's config file.

```json
"workbench.colorCustomizations": {
  "[One Dark Pro]": {
    "editorBracketHighlight.foreground1": "#e5c07b",
    "editorBracketHighlight.foreground2": "#c678dd",
    "editorBracketHighlight.foreground3": "#61afef"
  }
}
```

**Comment by Binaryify** [comment]
yes, I know, I just don't know how to choose the best color

**Comment by mrpunkin** [comment]
@mciesin I went ahead and just used your values in my config for now and it's world's better already. Thanks.

**Comment by mrpunkin** [comment]
Actually I went ahead and used the following instead after some further tweaking.

```settings.json
"workbench.colorCustomizations": {
  "[One Dark Pro]": {
    "editorBracketHighlight.foreground1": "#d19a66",
    "editorBracketHighlight.foreground2": "#c678dd",
    "editorBracketHighlight.foreground3": "#56b6c2"
  }
}
```

**Comment by julian-poidevin** [comment]
@mrpunkin I like your settings a lot, why don't you submit your settings as a pull request as default parameters for the theme ?

**Comment by mrpunkin** [comment]
> @mrpunkin I like your settings a lot, why don't you submit your settings as a pull request as default parameters for the theme ?

I'm not familiar enough with the theme syntax for VSCode to know where those should live if they aren't simply setting overrides.

**Comment by Binaryify** [comment]
@mrpunkin it look great, I will update that

**Comment by Binaryify** [comment]
just release a new version, you can check it now~
@mrpunkin @julian-poidevin

**Comment by Binaryify** [comment]
In fact, I don't like the foreground2 color, how about set it to #abb2bf

**Comment by Tetrax-10** [comment]
> In fact, I don't like the foreground2 color, how about set it to #abb2bf

These are the colors I use why don't you try these.
purple is a bracket's standard color why change it. It looks nice
I added `#abb2bf` to foreground 6

```json
"workbench.colorCustomizations": {
    "[One Dark Pro Flat]": {
        "editorBracketHighlight.foreground1": "#E5C07B",
        "editorBracketHighlight.foreground2": "#da70d6",
        "editorBracketHighlight.foreground3": "#87cefa",
        "editorBracketHighlight.foreground4": "#f08080",
        "editorBracketHighlight.foreground5": "#00d18f",
        "editorBracketHighlight.foreground6": "#abb2bf",
    }
}
```
![gg](https://user-images.githubusercontent.com/75513645/167259697-4d982455-1a54-4a66-a418-e41b8978d9fc.png)

**Comment by Binaryify** [comment]
@Tetrax-10 I prefer let user custom that in their setting.json, I just pinned this issue to let people easy to find this setting

**Comment by DavidGoldman** [comment]
Is there a reason you don't want the above to be the default? I think it certainly looks better than the VS Code default, and users could easily change it if they want - I think it makes sense to include in theme just to have a better default behavior.

**Comment by julian-poidevin** [comment]
> Is there a reason you don't want the above to be the default? I think it certainly looks better than the VS Code default (when using this theme), and users could easily change it if they want - I think it makes sense to include in the theme just to have a better default behavior.

I totally agree ! This should be part of the default.

**Comment by Visual-Dawg** [comment]
@Tetrax-10  May I ask how you achieve this beautiful font style? Is this Jetbrains Mono? Have you adjusted the spacing? What are the values? :D

Also yes, this above should be part of the defaults
