### ISSUE TITLE
Visual Studio version shows bright line below tabs

### ISSUE THREAD

**Issue by fgimian** [Binaryify/OneDark-Pro#736]
**Describe what you want**
I believe a new problem occurred recently as part of one of the Visual Studio 2022 updates and now we have a bright line just below the tab list which looks very much out of place.

**Additional context**
![image](https://user-images.githubusercontent.com/1811813/169295040-386a9b33-c0a9-40cf-a7ab-870a08774523.png)

**Comment by Binaryify** [comment]
plz check v1.3.2

**Comment by fgimian** [comment]
Thank you so much for the reply @Binaryify, I just installed v1.3.2 but sadly still see the white line below my tab bar...

![image](https://user-images.githubusercontent.com/1811813/172044414-702eacd1-9061-4d38-ad5f-d26f4ed39882.png)

Any ideas?
Fotis

**Comment by Binaryify** [comment]
it is have some problem, I might need create an issue in the https://github.com/microsoft/theme-converter-for-vs

**Comment by fgimian** [comment]
> it is have some problem, I might need create an issue in the https://github.com/microsoft/theme-converter-for-vs

Perhaps yeah, I have seen this issue on a few themes, but not on others, so it may be something that's triggering it in specific themes.

**Comment by Binaryify** [comment]
I also saw that problem in official theme
![image](https://user-images.githubusercontent.com/12221718/172044630-d6e27cd2-d912-4ee4-8bed-dda28949d36a.png)

**Comment by fgimian** [comment]
> I also saw that problem in official theme ![image](https://user-images.githubusercontent.com/12221718/172044630-d6e27cd2-d912-4ee4-8bed-dda28949d36a.png)

That's true, though I have a feeling that may be intentional.  I personally really struggle to look at the default Dark theme, it actually hurts my eyes.  It has a lot of contrast everywhere so I honestly think in that particular case, it was intentional.

The older [One Dark Pro theme](https://marketplace.visualstudio.com/items?itemName=adrianwilczynski.one-dark-pro) seems to avoid this problem which is what I'm using at the moment.  But that theme has been abandoned by the author and there are many other problems with it.

The complexity of theme design in Visual Studio has resulted in virtually no 3rd party theme that is 100% right sadly. 😢

**Comment by Binaryify** [comment]
indeed
I just create an issue and you can follow this
https://github.com/microsoft/theme-converter-for-vs/issues/145

**Comment by fgimian** [comment]
> indeed I just create an issue and you can follow this [microsoft/theme-converter-for-vs#145](https://github.com/microsoft/theme-converter-for-vs/issues/145)

Thank you so much for your help, really appreciate it! 🤗

**Comment by fgimian** [comment]
Thanks so much @Binaryify, I can confirm that v1.3.3 has resolved the issue. 🥰

Really appreciate your help with this!!  I'll close this issue now.

Cheers
Fotis
