### ISSUE TITLE
Rendered whitespaces are hard to see

### ISSUE THREAD

**Issue by asd142513** [Binaryify/OneDark-Pro#741]
**Describe what you want**
Setting `editor.renderWhitespace` option renders whitespaces but it's too close to the background color to see. Its color should be changed to another proper color.
![before](https://user-images.githubusercontent.com/62266626/172897277-d822e929-fc32-41d1-aaec-c355db0cb805.png)

**Additional context**
I tried `"workbench.colorCustomizations": { "editorWhitespace.foreground": "#007F7F" }`. I hope some other nice color to be default!
![after](https://user-images.githubusercontent.com/62266626/172897296-33ecc0c0-9fad-4b80-af5b-1e70837139db.png)

**Comment by asd142513** [comment]
Selected ones are almost impossible to see

**Comment by Binaryify** [comment]
how about #ffffff1d
![image](https://user-images.githubusercontent.com/12221718/173186503-8e36242c-e412-4a2a-a580-5b2a95d8743f.png)

**Comment by asd142513** [comment]
it's much easier to see than before. i think it's good!

**Comment by Binaryify** [comment]
you can check the latest version~

**Comment by Binaryify** [comment]
you cen check latest version
