### ISSUE TITLE
Font used in screenshots

### ISSUE THREAD

**Issue by deepindersinghbti** [Binaryify/OneDark-Pro#744]
Please tell the name of the font used in the screenshots. One of them can be seen [here](https://cdn.jsdelivr.net/gh/binaryify/onedark-pro/screenshots/italic.png).

**Comment by Binaryify** [comment]
JetBrains Mono

**Comment by Binaryify** [comment]
https://www.jetbrains.com/lp/mono/

**Comment by deepindersinghbti** [comment]
Thank you very much for such a quick response and especially for the link!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
