### ISSUE TITLE
Label bar focus status and blur status two display definition problems

### ISSUE THREAD

**Issue by SCWR** [Binaryify/OneDark-Pro#746]
**Describe what you want**
When I work, it is easy to open a lot of files, which will cause a lot of labels in the label bar. But due to the clarity of the label bar, it is difficult for me to tell which file I currently open.

**Additional context**

`One Dark Pro`
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/8925282/173727847-6fe91fce-9977-4c4c-ab5f-346cf5b18395.png">

`One Dark Pro Darker`
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/8925282/173728832-6c870b07-6411-429c-aa30-4103702bca60.png">

`One Dark Pro Flat`
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/8925282/173727572-0736ec69-4459-4d9d-99e8-442cdb9adba2.png">

`One Dark Pro Mix`
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/8925282/173728933-76c41d37-2df1-4ddb-9800-18dcc29ae19a.png">

when `git` join in

`One Dark Pro`
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/8925282/173729246-9d520d6c-fa71-4bfb-954b-c37795c44f0d.png">

`One Dark Pro Darker`
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/8925282/173729216-53eeb1cf-a5dd-4b06-a4f5-d5a38f976873.png">

`One Dark Pro Flat`
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/8925282/173729326-33536935-c31a-4d2b-98c9-647495102e6f.png">

`One Dark Pro Mix`
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/8925282/173729111-e4ed43c5-5e3a-4b08-ac52-990ebd420fa5.png">

Only the `One Dark Pro Flat` theme can clearly see which file is now, but I like `One Dark Pro` theme, so can the clarity be more obvious.
Thank you for your efforts.

**Comment by Binaryify** [comment]
do you have some idea
add a border to the bottom or change the active tab's background

**Comment by SCWR** [comment]
我们中文交流吧 大佬
我觉得都行，简单的跟 `One Dark Pro Flat` 一致就行，因为对我而言，主题内容我习惯了好久，这次的痛点主要是在多文件及别的插件干扰下，比较难以一眼分辨出我现在在那个文件下。
`One Dark Pro Flat` 已经能达到目的。
具体其他更多的优化可能需要看看你的时间，当然我也愿意贡献，就是上下文我可能需要时间去了解

**Comment by Binaryify** [comment]
嗯，加了

**Comment by SCWR** [comment]
好的 等你发包更新

**Comment by nifte** [comment]
@Binaryify This was already resolved in #565. Can we revert this?
