### ISSUE TITLE
debugToolBar.background becomes red in Mix theme

### ISSUE THREAD

**Issue by FredZeng** [Binaryify/OneDark-Pro#747]
**Describe the bug**

**To Reproduce**
1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots & Example Code**
![image](https://user-images.githubusercontent.com/17154608/173803142-a6efc63d-c535-45c0-b25b-7dd30d80f2af.png)
![image](https://user-images.githubusercontent.com/17154608/173803481-362cae23-949a-483d-8669-97ba6052f247.png)

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18363
 - VSCODE Version  1.68.0
 - Theme version 3.14.3

**Additional context**

**Comment by Binaryify** [comment]
thank for the feedback and the PR~
