### ISSUE TITLE
2 constants not parsed in PHP

### ISSUE THREAD

**Issue by Machou** [Binaryify/OneDark-Pro#756]
**Describe the bug**
When i write `date(DATE_RFC1123, $date);` in PHP, DATE_RFC1123 is colored.

But when i write `DATE_RFC7231` & `DATE_RFC3339_EXTENDED`, she's not colored.

**Screenshots & Example Code**
![Image](https://i.ibb.co/QfMkVcY/code.png "Example")

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro. **21H2** *19044.1865*
 - VSCODE Version: 1.69.2
 - Theme: **One Dark Pro** 3.15.2

**Comment by Binaryify** [comment]
plz provide the code

**Comment by Binaryify** [comment]
you can follow this
https://github.com/microsoft/vscode/issues/157470

**Comment by Machou** [comment]
Ok thanks
