### ISSUE TITLE
Customizing color of comparsion operators doesn't take effect

### ISSUE THREAD

**Issue by safarli** [Binaryify/OneDark-Pro#760]
**Describe the bug**
Customizing "keyword.operator.logical" doesn't work.

**To Reproduce**
1. Open settings.json
2. Add:
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": "keyword.operator.logical",
        "settings": {
          "foreground": "#ff00ff",
          "fontStyle": "bold"
        }
      }
    ]
  }
```
**Expected behavior**
Expected color change, but it doesn't change. Tried this customization with other themes and they worked.

**Screenshots & Example Code**

**Desktop**
 - OS: Windows 10 Pro 64 bit
 - VSCODE Version: 1.71.0
 - Theme version v3.15.4

**Additional context**

**Comment by safarli** [comment]
I've also checked it in Vscode Insiders v1.72.0 fresh install, it didn't work either.

**Comment by safarli** [comment]
I've tested following settings and they are working:
- `keyword.operator.arithmetic`
- `keyword.operator.assignment`

**Comment by Binaryify** [comment]
plz try customizing semanticTokenColorCustomizations like this~
![image](https://user-images.githubusercontent.com/12221718/188457646-cd0eaf6f-2cfa-44da-823e-f3a9385fb5c7.png)

**Comment by safarli** [comment]
> plz try customizing semanticTokenColorCustomizations like this~ ![image](https://user-images.githubusercontent.com/12221718/188457646-cd0eaf6f-2cfa-44da-823e-f3a9385fb5c7.png)

It didn't work either. I tried these:

```json
"editor.semanticTokenColorCustomizations": {
    "enabled": true,
    "rules": {
      "keyword.operator.logical:javascript": {
        "foreground": "#ff0000"
      },
      "keyword.operator.logical:typescript": {
        "foreground": "#ff0000"
      },
      "keyword.operator:typescript": {
        "foreground": "#ff0000"
      },
      "keyword.operator:javascript": {
        "foreground": "#ff0000"
      }
    }
  }
```

**Comment by safarli** [comment]
> plz try customizing semanticTokenColorCustomizations like this~ ![image](https://user-images.githubusercontent.com/12221718/188457646-cd0eaf6f-2cfa-44da-823e-f3a9385fb5c7.png)

### Even tried most of them, but no luck. It didn't work either.

![kod (1)](https://user-images.githubusercontent.com/65605198/188475584-77c84641-70bf-4aca-86fa-74aa6fd9878f.png)

**Comment by Binaryify** [comment]
could you provide some code

**Comment by safarli** [comment]
> could you provide some code

Can you test it yourself, only how to customize those *comparison* opeartors please?, ignore what I've done

**Comment by safarli** [comment]
> could you provide some code

I've fresh installation of VS Code Insiders version, no other extensions installed except 'One Dark Pro'. Below are **settings.json** settings:

```json
{
    "workbench.colorTheme": "One Dark Pro",
    "editor.semanticTokenColorCustomizations": {
        "rules": {
            "operator": {
                "foreground": "#ff0000"
            },
            "keyword": {
                "foreground": "#ff0000"
            }
        }
    },
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "keyword",
                    "storage",
                    "keyword.control",
                    "keyword.control.from",
                    "keyword.control.flow",
                    "keyword.operator.new",
                    "keyword.control.import",
                    "keyword.control.export",
                    "keyword.control.default",
                    "keyword.control.trycatch",
                    "keyword.control.conditional",
                    "storage.type",
                    "storage.type.class",
                    "storage.modifier.tsx",
                    "storage.type.function",
                    "storage.modifier.async",
                    "variable.language",
                    "variable.language.this",
                    "variable.language.super",
                    "meta.class",
                    "meta.var.expr",
                    "constant.language.null",
                    "support.type.primitive",
                    "entity.name.method.js",
                    "entity.other.attribute-name",
                    "punctuation.definition.comment",
                    "text.html.basic entity.other.attribute-name",
                    "tag.decorator.js entity.name.tag.js",
                    "tag.decorator.js punctuation.definition.tag.js",
                    "source.js constant.other.object.key.js string.unquoted.label.js"
                ],
                "settings": {
                    "foreground": "#FF0000",
                    "fontStyle": "bold"
                }
            }
        ]
    }
}
```
---

Again, no luck, everything changes except comparison operators.

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/188828802-e4ed3c01-b5c6-4f68-929c-1f201d176aa8.png)
had you check the code scope

**Comment by safarli** [comment]
> ![image](https://user-images.githubusercontent.com/12221718/188828802-e4ed3c01-b5c6-4f68-929c-1f201d176aa8.png) had you check the code scope

Oh, thanks, I found the keys for it, they are `keyword.operator.comparison` & `keyword.operator.relational`. But, suprisingly they don't show up on intellisense/quick suggestions (suprisingly). Also, more general `keyword.operator` doesn't have effect on it (But in other color themes it works as intended. In this theme, it's probably due to overriding issues).

**Comment by safarli** [comment]
I think issue can be closed.
