### ISSUE TITLE
Extension Host crashes repeatedly

### ISSUE THREAD

**Issue by shuxter** [Binaryify/OneDark-Pro#775]
Type: <b>Bug</b>

Use VSCode normally and the extension host keeps crashing for javascript files.

Extension version: 3.15.8
VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 8, 7|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id 644083b2-7154-4712-85e2-4628159173c8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
pythonb192cf:30669361
funwalk2:30682974

```

</details>

**Comment by eurobob** [comment]
Also having this issue over and over again

**Comment by Binaryify** [comment]
have not idea now, this extension only watch config change and compile new theme json files, but you can try one dark pro lite, it only include theme json files

**Comment by Binaryify** [comment]
<img width="2301" alt="image" src="https://user-images.githubusercontent.com/12221718/225183193-9a164ece-6823-467e-8eac-d99f15a76e57.png">
