### ISSUE TITLE
Request for Variable Color Customization

### ISSUE THREAD

**Issue by sergiopani** [Binaryify/OneDark-Pro#777]
I do have a suggestion for improvement that I believe could benefit many users.

As someone who spends a considerable amount of time coding, I find that the red color of the variables in your theme can be overwhelming when there are many of them on the screen. It can be distracting and make it difficult to focus on the code. Therefore, I would like to request if it would be possible to add an option in Visual Studio Code to change the color of the variables in the One Dark Pro theme.

I understand that this may not be a priority for many users, but I believe it could greatly enhance the experience for those who find the red color of the variables to be too intense.

**Comment by Binaryify** [comment]
plz check this 
https://binaryify.github.io/OneDark-Pro/#/?id=highlight-color-custom
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/12221718/224621631-8ccac4cd-7d6d-47a3-b29c-b8c220c2cf2a.png">
don't forget reload vscode window
