### ISSUE TITLE
VScode is lagging

### ISSUE THREAD

**Issue by sheikh-abdul-ali** [Binaryify/OneDark-Pro#782]
Type: <b>Bug</b>

using bisect.

Extension version: 3.15.8
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id eefa9d9e-5552-4c37-a996-ec6e88ebec6d|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
vscrpc:30673769
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by Binaryify** [comment]
try One Dark Pro Lite
https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.One-dark-pro

**Comment by sheikh-abdul-ali** [comment]
> try One Dark Pro Lite https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.One-dark-pro

What is the difference?

**Comment by Binaryify** [comment]
@sheikh-abdul-ali
One Dark Pro have full extension support, can customize some configurations and when config change, it will recompile theme file json
One Dark Pro Lite only load themes files json
