### ISSUE TITLE
log.tmLanguage.json, diff severity levels

### ISSUE THREAD

**Issue by CoffeeChaton** [Binaryify/OneDark-Pro#784]
**Describe what you want**

| levels      | desired color                        | textmate scopes |
| :---------- | :----------------------------------- | :-------------- |
| `[info]`    | green (now)                          | log.info        |
| `[warning]` | yellow or dark red                   | log.warning     |
| `[error]`   | red or bright red, not like `[info]` | log.error       |

**Additional context**
![Y](https://github.com/Binaryify/OneDark-Pro/assets/63182963/5672d646-e9f8-45be-a1ba-0132c2b7b1e6)

[vscode log.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/log/syntaxes/log.tmLanguage.json)

`vscode.window.createOutputChannel('', { log: true });`

extensions: One Dark Pro Lite
Color Themes: One Dark Pro

**Comment by Binaryify** [comment]
how to reproduce

**Comment by CoffeeChaton** [comment]
> how to reproduce

```TypeScript
// extension.ts

export function activate(context: vscode.ExtensionContext): void {
    const logExp: vscode.LogOutputChannel = vscode.window.createOutputChannel('exp', { log: true });
    logExp.info('log msg');
    logExp.warn('warn msg');
    logExp.error('error msg');
}
```
![error](https://github.com/Binaryify/OneDark-Pro/assets/63182963/03d1a769-1630-484b-9846-9f2dc19175c8)
![warning](https://github.com/Binaryify/OneDark-Pro/assets/63182963/2a3a35db-6188-4158-9e80-0e4e5ed23584)
![info](https://github.com/Binaryify/OneDark-Pro/assets/63182963/7949e581-5a0f-4232-bd3e-baf1e184aa45)

**Comment by CoffeeChaton** [comment]
Thanks, super fast update!
