### ISSUE TITLE
 two different colors for the equal sign.

### ISSUE THREAD

**Issue by Xinyu-Sheng** [Binaryify/OneDark-Pro#791]
**Describe the bug**
In the display of a C++ file, there are two different colors for the equal sign.

**Screenshots & Example Code**
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/6009a358-2924-4c4d-98e7-7f201de5f0f9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VSCODE Version  1.79.2
 - Theme version 3.15.18

**Comment by Binaryify** [comment]
could you provide more code
![image](https://github.com/Binaryify/OneDark-Pro/assets/12221718/c465ae98-294e-4658-975d-eff61e6d604e)

**Comment by Xinyu-Sheng** [comment]
the code comes from ROS2
[Writing a simple publisher and subscriber (C++)Writing a simple publisher and subscriber (C++)](http://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Cpp-Publisher-And-Subscriber.html)
```
#include <chrono>
#include <functional>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

using namespace std::chrono_literals;

/* This example creates a subclass of Node and uses std::bind() to register a
* member function as a callback from the timer. */

class MinimalPublisher : public rclcpp::Node
{
  public:
    MinimalPublisher()
    : Node("minimal_publisher"), count_(0)
    {
      publisher_ = this->create_publisher<std_msgs::msg::String>("topic", 10);
      timer_ = this->create_wall_timer(
      500ms, std::bind(&MinimalPublisher::timer_callback, this));
    }

  private:
    void timer_callback()
    {
      auto message = std_msgs::msg::String();
      message.data = "Hello, world! " + std::to_string(count_++);
      RCLCPP_INFO(this->get_logger(), "Publishing: '%s'", message.data.c_str());
      publisher_->publish(message);
    }
    rclcpp::TimerBase::SharedPtr timer_;
    rclcpp::Publisher<std_msgs::msg::String>::SharedPtr publisher_;
    size_t count_;
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<MinimalPublisher>());
  rclcpp::shutdown();
  return 0;
}
```

**Comment by Binaryify** [comment]
can't reproduce in vscode 1.80.0
![image](https://github.com/Binaryify/OneDark-Pro/assets/12221718/73e607e5-c082-4725-a300-ae42955fa90a)

**Comment by Xinyu-Sheng** [comment]
Perhaps you should try using a computer with ROS2 installed, which includes the necessary header files that can be located. The following image is taken in vscode 1.80.0
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/6ed57dd8-44a3-49dc-a541-2dc410f1a879)

**Comment by Binaryify** [comment]
could you use this command to show the code's scope
![image](https://github.com/Binaryify/OneDark-Pro/assets/12221718/e1db5c73-b3e2-4a39-84d7-5ba1e46ee097)
![image](https://github.com/Binaryify/OneDark-Pro/assets/12221718/4cac1eeb-36d9-45f0-9661-1fbbbcba7984)
![image](https://github.com/Binaryify/OneDark-Pro/assets/12221718/0d10307c-da00-48d5-b093-2117a60c82fb)

**Comment by Xinyu-Sheng** [comment]
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/c10bb979-fbc1-4d2f-beac-d5f58f68e3c1)
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/a3fc9003-88e5-400a-beff-44003be9f324)

**Comment by Binaryify** [comment]
plz try v3.16.0

**Comment by Xinyu-Sheng** [comment]
Problem solved! Thanks for your effort!
