### ISSUE TITLE
Fully Disable Bold Fonts from the Editor Window

### ISSUE THREAD

**Issue by ldts** [Binaryify/OneDark-Pro#793]
I'd love to be able to disable all bold fonts from the editor window: when you suffer from astigmatism it just makes everything blurry whenever bold fonts are enabled.

One of the reasons I keep on going back to SlickEdit is that it allows me to do that - so no bold fonts on black background.

**Comment by ldts** [comment]
The TERMINAL has better readability than the editor window which defeats the purpose of the editor....

![image](https://github.com/Binaryify/OneDark-Pro/assets/10456021/faefec86-df74-4159-b3f7-3ead9f8b6c88)

**Comment by zhylmzr** [comment]
You can add config in `settings.json` to disable bold font:
```
"oneDarkPro.bold": false,
```

**Comment by ldts** [comment]
sure but it is not that. I also updated to code-insiders (using electron 25) and still didnt make a difference

why can the editor view have the same font crispiness than the folders or terminal view? do you think that would be possible


![image](https://github.com/Binaryify/OneDark-Pro/assets/10456021/0bcdf6f1-ce55-4dc7-b00c-1c4810bf87c2)

**Comment by zhylmzr** [comment]
Sorry for not noticing your image before, but your theme doesn't look like `OneDark Pro`.
You may need to look in the theme docs to how to disable bold.

**Comment by ldts** [comment]
hi @zhylmzr um yes this is OneDark Pro with the "retro" look. I am using Liberation Mono - other fonts I find them hard to work with.

What I am trying to figure out is why the editor window fonts are not as crisp as the terminal or the explorer views. I wonder if font rendering is a problem in VSCode rather than the extension.

**Comment by zhylmzr** [comment]
Comparing the text of your editor and the terminal, it seems that you have added additional letter space,  try:

```
"editor.letterSpacing": 0,
```

**Comment by ldts** [comment]
thanks a lot for your persistence on supporting me on this self-inflicted issue!. yes it seems this was the problem (I had set it to 1 when I was testing fonts and it seems I forgot about it).
