### ISSUE TITLE
In some circumstances, functions are not clearly separated from the code content

### ISSUE THREAD

**Issue by Xinyu-Sheng** [Binaryify/OneDark-Pro#794]
After enables this function
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/8a80e923-fc0c-4151-ac2a-9f9ae94650ac)

In some circumstances, functions are not clearly separated from the code content and may be misrecognized as the full content, potentially missing some lines.
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/c2ebeb43-fdb4-448b-9105-ff90cfd4036d)

Other themes have a clear separation between function name and code content.
![image](https://github.com/Binaryify/OneDark-Pro/assets/74916624/b7e9eb90-e2c6-4e75-b4e4-f3914aa4e545)

Would this visual effect be likely to be enhanced?

**Comment by Binaryify** [comment]
this is vscode's issue, theme is only responsible for coloring the code
