### ISSUE TITLE
please add line separator

### ISSUE THREAD

**Issue by haidarabdillah** [Binaryify/OneDark-Pro#796]
**Describe what you want**
i want to see the line separator between editor, terminal and folder bar, so we know how to resize the the editor

**Additional context**
![image](https://github.com/Binaryify/OneDark-Pro/assets/113880800/da284ed1-24a3-4cd2-a55f-5a81bce75080)

**Comment by Binaryify** [comment]
https://github.com/JoelCrosby/OneDarkDarker
