### ISSUE TITLE
Set active status for top right icons

### ISSUE THREAD

**Issue by kossa** [Binaryify/OneDark-Pro#805]
**Describe the bug**
When we enable collapse unchanged regions we dont get active status

**To Reproduce**
1. Click on Toggle Collapse Unchanged Regions
2. The background of the icon is not changing(cannot know if it's active or no)
3. Do the same with White space difference

**Expected behavior**
The background of thee icon should changed to know if it's active or no
Like this other themes
![image](https://github.com/Binaryify/OneDark-Pro/assets/1175584/85d75858-1303-41ac-8157-02d1aacd97f6)

<img width="363" alt="image" src="https://github.com/Binaryify/OneDark-Pro/assets/1175584/46580785-9c2a-42c5-89a2-989b48205829">

**Screenshots & Example Code**
<img width="424" alt="image" src="https://github.com/Binaryify/OneDark-Pro/assets/1175584/e0c4040d-1e2b-4ce6-ab5c-08f27cf14f11">

**Desktop (please complete the following information):**
 - OS: Mac
 - VSCODE Version  1.83.1
 - Theme version v3.16.2

**Comment by kossa** [comment]
Any update for this @Binaryify ?

**Comment by Binaryify** [comment]
sorry for I didn't read this issue before
how about this
![image](https://github.com/user-attachments/assets/e4433054-41ae-4f35-b855-f7c741d89a40)

**Comment by kossa** [comment]
Excellent

**Comment by Binaryify** [comment]
plz check v3.17.5~

**Comment by kossa** [comment]
Alright it works fine, really it help a lot, always I have to click twice to see wich one is selected, thank you @Binaryify 

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/f68d8e1d-105f-4a82-8a94-74ace6c39a1a">
