### ISSUE TITLE
Can we install this theme for monaco editor ?

### ISSUE THREAD

**Issue by ManUtopiK** [Binaryify/OneDark-Pro#813]
**Describe the bug**

I try to install the the in monaco-editor.
I exported the https://github.com/Binaryify/OneDark-Pro/blob/master/themes/OneDark-Pro.json and define it with :
`monaco.editor.defineTheme('one-dark-pro', oneDarkPro)`
But I think I'm going wrong. This file doesn't look like a theme like [this example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0#XQAAAAIpAwAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw2_RKcnmJTiNUtu5Yj0D6Gs0MBQaKsfYDizyTgFcvIJCLb0TgTVKA3hWkzTeGC6sY4F9ZD38Vf-oD9Kou5bpzeFP16YxpwZPLMuFYTXrbUCCDqM8vhwKReXz1lgKwc3q7GyrzWbipcH7ev-G4EsQeV_Y_xizVKUfIIX5g68TOTz8ezFZnueqPUHsZq547M1to1lv9pc4NjSmqce7EJ2RclkpncGLjuo1cDSWSF9O6Mra9QNisp2au67S0Bj7eUMBetWmJK4kAUDIem2y-PAOv4s_LlgXn3Ofu4nt_4m3zLVR5MUyKUeCF7_lBUJ-D5YA5DOrY1A_qTJoErP0hT4wChq31sbHEmKhYSUJ0qtOTImN_jnQepfq0udxME35IBfLXUoSvDnYP831b_LbMokoXHoymv3NUJ7vaHNHPBvRKF6pE48vG0Rp8GW0LKeTKWYM_EsIwYEqtHZf_i1YKgNOp4EGpEP4x0wqvlIhe26qngYYfQXPfHkkegOMHRRxsLX6-AGNzdn9BIyfaIESh-60kCIU6S-FJT4ecqF__Kj_wAA).

Is there a way to use this theme to monaco-editor ?
**Additional context**
"monaco-editor": "^0.47.0"

**Comment by ManUtopiK** [comment]
@GavinGoGaming
Awesome, thanks a lot !
Where did you find this code ?

**Comment by GavinGoGaming** [comment]
> @GavinGoGaming Awesome, thanks a lot ! Where did you find this code ?

@ManUtopiK I used https://vsctim.vercel.app/ with a decent amount of tweaking it to make it work right

**Comment by ManUtopiK** [comment]
Great tool ! Bookmarked. Thanks !
