### ISSUE TITLE
Colors are not being applied as per theme

### ISSUE THREAD

**Issue by lucasheverton** [Binaryify/OneDark-Pro#823]
**Describe the bug**

**To Reproduce**

1. installed the extension but I wanted these colors here as shown in the image

![image](https://github.com/user-attachments/assets/ecd08c8e-20e0-451e-ad00-ca2e6018bdd9)

2. After the reload, the colors were not applied and were left like this:

![image](https://github.com/user-attachments/assets/10915dae-e56a-41ff-898d-1ed4d7828b22)

My settings.json:

![image](https://github.com/user-attachments/assets/03b13702-0cae-41e8-a31e-9e7a1b8ba073)

![image](https://github.com/user-attachments/assets/6ccc1c21-445b-4ef4-a62c-8b81805f1362)

![image](https://github.com/user-attachments/assets/40a15daf-0821-4089-9059-9a852d291876)

**Comment by Binaryify** [comment]
Have you installed the Vue - Official extension
