### ISSUE TITLE
`<<` Causes Syntax Highlighting Problems

### ISSUE THREAD

**Issue by StrangeRanger** [Binaryify/OneDark-Pro#826]
**Describe the bug**

For some reason, the following line in my Bash code causes the syntax highlighting of OneDark-Pro to miss-highlight the code: `echo "$(( (octet1 << 24) + (octet2 << 16) + (octet3 << 8) + octet4 ))"`

![Screenshot 2024-09-01 at 10 00 11 AM](https://github.com/user-attachments/assets/7ba589e6-21a8-4ac3-b38a-27611676c46d)

After some experimentation, I found that I could reproduce the same problem with `<<)`. 

![Screenshot 2024-09-01 at 10 28 35 AM](https://github.com/user-attachments/assets/bc3f8a30-7af7-4478-91b7-4a29bfd32c38)

To be more specific, this only happens when using `<<`. Using `<`, `<<<`, or any other form of redirect does not reproduce the same problem. So something like `echo "$((ip_int >> 24 & 255)).$((ip_int >> 16 & 255)).$((ip_int >> 8 & 255)).$((ip_int & 255))"`, which is in the screenshot, does not cause any problems.

**To Reproduce**

I've included all the information about how to reproduce it above.

**Expected behavior**

When using `<<`, I expect the syntax highlighting to work as expected rather than highlighting almost everything green.

**Desktop (please complete the following information):**
 - OS: macOS 14.6.1
 - VSCODE Version: 1.92.2 (Universal)
 - Theme version v3.17.2

**Comment by Binaryify** [comment]
other themes have same problem, I think it's vscode's problem

**Comment by StrangeRanger** [comment]
I see what you mean. I'll go ahead and make an issue on VSCode's repository. Will you close this issue then, or keep it open for a while longer?

**Comment by StrangeRanger** [comment]
Issue has been made at https://github.com/microsoft/vscode/issues/228637

**Comment by Binaryify** [comment]
should I close this issue

**Comment by StrangeRanger** [comment]
Yes, you're good to close this issue.

**Comment by Binaryify** [comment]
okay
