### ISSUE TITLE
arrow coloring errors in C++ trailing return types and concept definitions

### ISSUE THREAD

**Issue by Arteiimis** [Binaryify/OneDark-Pro#828]
**Describe the bug**
arrow coloring errors in C++ trailing return types and concept definitions

**Expected behavior**
render in same color

**Screenshots & Example Code**
![image](https://github.com/user-attachments/assets/986f9d5d-5f91-4349-b8a8-a7fb79613e22)

**Desktop (please complete the following information):**
 - OS: Win
 - VSCODE Version  1.93.0
 - Theme version 3.17.2

**Comment by Binaryify** [comment]
could you provide the code which in your screenshot

**Comment by Arteiimis** [comment]
> could you provide the code which in your screenshot

```cpp
#include <concepts>

template <class T>
concept has_func = requires(T t) {
    { t.func() } -> std::same_as<void>;
};

int main(int argc, char* argv[]) { }
```
The original example is in a library with other dependencies in the code. The example above is just as reproducible.

**Comment by Binaryify** [comment]
pls check the latest version
