### ISSUE TITLE
</style> loses color when using :deep() selector in style tag

### ISSUE THREAD

**Issue by EricWangQvQ** [Binaryify/OneDark-Pro#830]
**Describe the bug**
When using the :deep() selector with vue3 syntax inside a style tag in a vue file, “</style>” color is lost.
<img width="268" alt="image" src="https://github.com/user-attachments/assets/05854441-252a-48fd-994d-c24302e21efa">

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - VSCODE Version  [e.g. 1.93.1 (Universal)]
 - Theme version [e.g. v3.17.5]

**Comment by Binaryify** [comment]
this seem like vscode's issue
