### ISSUE TITLE
Improvements on color of variable types

### ISSUE THREAD

**Issue by jose-a-sa** [Binaryify/OneDark-Pro#86]
In One Dark Pro, I get different colors for `real_t` when is a function argument or when declaring a variable/function. It would be nice to get something like Monokai theme. It would be nice to get diferente coloring for variable types and language keywords (`if`, `else`, `return`, ...) and some italics to take advantage of font like Operator Mono

![2017-05-31 1 _li](https://cloud.githubusercontent.com/assets/13206784/26625610/9353addc-45ec-11e7-8825-27e1f0f5d8f9.jpg)

![2017-05-31_li 3](https://cloud.githubusercontent.com/assets/13206784/26625611/9353fbb6-45ec-11e7-9b66-fd1ffe5b6bce.jpg)

**Comment by Binaryify** [comment]
what language

**Comment by jose-a-sa** [comment]
Its pure C code

**Comment by Binaryify** [comment]
Can you provide some code ?

**Comment by jose-a-sa** [comment]
```
typedef long double real_t;

real_t Yslm(int s, int l, int m, real_t x)
{
    if (l < MAX(abs(s), abs(m)))
        GSL_ERROR("\nYslm function s,l,m input error.\n", GSL_EDOM);
    
    real_t sum = 0.0L;
    int r;

    for (r = 0; r <= l - s; r++)
        sum += binomial(l - s, r) * binomial(l + s, r + s - m) * powl(-1.0, l - r - s + m) * powl((1.0 + x) / (1.0 - x), r + (s - m) / 2.0);

    return sqrtl((factorial(l + m) * factorial(l - m) * (2 * l + 1)) / (factorial(l + s) * factorial(l - s) * 4.0 * PI)) * powl((1.0 - x) / 2.0, 1.0 * l) * sum;
}
```

Sry for the delay

**Comment by Binaryify** [comment]
Please update and check it, thx ~
