### ISSUE TITLE
 JS/TS object-literal key have the same highlight color

### ISSUE THREAD

**Issue by slieo** [Binaryify/OneDark-Pro#87]
After update to 2.8.3, JS/TS object-literal key's color changes to green, and it's same as the value's color, please fixed it.

**Comment by Binaryify** [comment]
What color do you think it should be

**Comment by slieo** [comment]
Just make a distinction between key & value, they are the same color now...Before 2.8.3, the key's color is yellow

**Comment by slieo** [comment]
<a href="http://imgur.com/ljrrKBj"><img src="http://i.imgur.com/ljrrKBj.png" title="source: imgur.com" /></a>

**Comment by Binaryify** [comment]
How about this
![image](https://cloud.githubusercontent.com/assets/12221718/26715998/52d6a68c-47aa-11e7-9bf5-4604f525a27f.png)
![image](https://cloud.githubusercontent.com/assets/12221718/26716003/5756eb7c-47aa-11e7-9303-50433ff0ff15.png)

**Comment by jens1o** [comment]
I also was fine with the previous color, this annoys me, too. I would like to see the changes being reversed.

**Comment by Binaryify** [comment]
before this, it was red, it maybe make some confusing

**Comment by jens1o** [comment]
But now, having a key and then an integer or boolean as the key we don't get any difference.

**Comment by slieo** [comment]
It's OK, I just want a different color between them, I suggest the second color above picture(yellow?)， and the integer's color, you can set it purple

**Comment by Binaryify** [comment]
How about this
@slieo @jens1o 
![image](https://cloud.githubusercontent.com/assets/12221718/26717060/82f2f5b0-47ae-11e7-8a06-e6620759745e.png)

**Comment by jens1o** [comment]
sorry, but what me really annoys is still not how I would like it:

![image](https://cloud.githubusercontent.com/assets/11234139/26717155/a21ebe38-477c-11e7-94a6-5bd526f6bf0e.png)
I would like to see a difference between a key and a value.

**Comment by slieo** [comment]
Good! but integer & boolean, could you just try purple?

**Comment by Binaryify** [comment]
I think that would be bad @slieo @jens1o ,they have same scope
![image](https://cloud.githubusercontent.com/assets/12221718/26717329/9c0e5926-47af-11e7-9901-e404153d597d.png)
![image](https://cloud.githubusercontent.com/assets/12221718/26717361/b3cbdafc-47af-11e7-8c64-59fcf23203e9.png)
![image](https://cloud.githubusercontent.com/assets/12221718/26717367/b8e7a3cc-47af-11e7-846b-27a66a170745.png)

**Comment by jens1o** [comment]
😭

**Comment by Binaryify** [comment]
@slieo @jens1o 
![image](https://cloud.githubusercontent.com/assets/12221718/26717648/bc700b0a-47b0-11e7-86d9-901a645ee55f.png)
Maybe Atom is right?

**Comment by slieo** [comment]
It's a tough choice

**Comment by jens1o** [comment]
Yep, @slieo's right.

**Comment by Binaryify** [comment]
![image](https://cloud.githubusercontent.com/assets/12221718/26718027/1ebab5e8-47b2-11e7-9e43-bd80b250be52.png)
How about this, left is VS Code, right is Atom

**Comment by jens1o** [comment]
I'm fine with this. Thanks for your effort. :)

**Comment by Binaryify** [comment]
@slieo 
How about you

**Comment by slieo** [comment]
this can't solve my problem, when the values are all string, just like this
<a href="http://imgur.com/fKYSoaP"><img src="http://i.imgur.com/fKYSoaP.png" title="source: imgur.com" /></a>

**Comment by Binaryify** [comment]
You are right, but I don't know what color is better

**Comment by slieo** [comment]
OK, thanks, Em...I want back to 2.8.2, but I don't konw how to operate...

**Comment by Binaryify** [comment]
But in 2.8.2, it was red, like this 
![image](https://cloud.githubusercontent.com/assets/12221718/26719143/f36352a2-47b5-11e7-88f2-b71b7972c67a.png)

**Comment by slieo** [comment]
I think red is good

**Comment by jens1o** [comment]
Yeah, I also think it was best, but I didn't want to make you sad, because I like your effort.

**Comment by Binaryify** [comment]
@slieo @jens1o 
Will rollback to 2.8.2

**Comment by jens1o** [comment]
Thanks!

**Comment by iddan** [comment]
Maybe keys should be white like in Atom unless they are strings?
