### ISSUE TITLE
Font color become black

### ISSUE THREAD

**Issue by baloneymath** [Binaryify/OneDark-Pro#88]
Hi~ I' have a problem that the font color become black and it's terrible
How can I fix the issue?
Thanks
![image](https://cloud.githubusercontent.com/assets/9354643/26764232/d7602688-4928-11e7-9335-6d8b839973fb.png)

**Comment by Binaryify** [comment]
What language ?

**Comment by jens1o** [comment]
Looks like Perl...

**Comment by baloneymath** [comment]
It's cpp, but it's also black in other languages

**Comment by Binaryify** [comment]
Can you provide some code ?

**Comment by baloneymath** [comment]
What do you need to solve this problem?

**Comment by jens1o** [comment]
Example code(but please not a screenshot, but written down in code block using.

**Comment by baloneymath** [comment]
Sample:
```
#include <iostream>
#include <string>  
#include <cassert>  
using namespace std;  
int main(int argc, char** argv) {  
	assert(argc == 2);
	string fileName = argv[1];
	vector<int> ss(1000, 0);
	iota(ss.begin(), ss.end(), 0);
	for (int i : ss) cerr << i << endl;
	return 0;
}
```

**Comment by jens1o** [comment]
can't reproduce:
![image](https://cloud.githubusercontent.com/assets/11234139/26776805/164ae628-49db-11e7-8fd4-3fdcefcfaa75.png)

Do you have any extensions installed? Maybe they modify some grammar.

**Comment by baloneymath** [comment]
I've tried closing all the other extensions, but it still didn't help

**Comment by Binaryify** [comment]
@baloneymath 
You can try reinstall it
