### ISSUE TITLE
Any plans to make OneLight-Pro also?

### ISSUE THREAD

**Issue by ravshansbox** [Binaryify/OneDark-Pro#94]

**Comment by Binaryify** [comment]
Yes, but no so fast

**Comment by akamud** [comment]
Take a look at [this theme](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onelight) in the marketplace. It is maintained by me and it's also [open source](https://github.com/akamud/vscode-theme-onelight).

**Comment by khanh-bes** [comment]
The project has been abandoned for a really long time now, by any chances that you planned to make a light version, @Binaryify , thank you.
