### ISSUE TITLE
Separate color for links

### ISSUE THREAD

**Issue by NickolasGame** [Binaryify/OneDark-Pro#95]
nake an separate color for links (http , https, cdn etc) like in Atom One Dark

**Comment by Binaryify** [comment]
Can you provide some screenshot

**Comment by NickolasGame** [comment]
Yes, that is color links in One Dark Pro just like in regular values(meta, charset, src, etc).
I recommend to color all types of links: links to other sites, widgets, and of course cdn resources, thats means all what starting from http , https, http/2.

Heres like atom colors links in One Dark:
(homepage link)
![package json e__bootstrap atom 13 06 2017 9_34_57](https://user-images.githubusercontent.com/21085814/27071046-09f9e316-5024-11e7-9218-b01b75968e6f.png)

And current colors of links in One Dark Pro:
(also homepage link)
![package json bootstrap visual studio code 13 06 2017 9_30_48](https://user-images.githubusercontent.com/21085814/27071109-453f573a-5024-11e7-8685-c8acb96761ee.png)

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/27124105-8a054eca-5122-11e7-8f37-3eed5f7dc2f7.png)
![image](https://user-images.githubusercontent.com/12221718/27124106-8a49548a-5122-11e7-8fa3-5a50fda15684.png)
They have same scope in VS Code, so it can't support now, but when VS Code support it, I will update it

**Comment by NickolasGame** [comment]
Understand you. Will it good if i will open an issue?(TO vscode)

**Comment by Binaryify** [comment]
Maybe
