### ISSUE TITLE
Change color of warning/error squiggles

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#96]
https://github.com/Microsoft/vscode/pull/27053

**Comment by ajitid** [comment]
Current colors are quite popping and do not match with the theme

**Comment by Binaryify** [comment]
Can you provide some screenshot?

**Comment by ajitid** [comment]
![capture](https://user-images.githubusercontent.com/26769888/27249558-168b4a1a-5336-11e7-80bd-b11790e7242c.PNG)
I am asking to change this red squiggle color of error. Same for warning's squiggle color.

**Comment by Binaryify** [comment]
What color do you think is better ?

**Comment by ajitid** [comment]
Same colors which are in Aron's One Dark theme

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/27250239-db2e3c04-535b-11e7-84d8-d46c4d5ad028.png)

How about it ?

**Comment by ajitid** [comment]
This is better.

**Comment by ajitid** [comment]
Warning squiggles have acceptable color, but if you think it also needs a change then change it too.

**Comment by ajitid** [comment]
Maybe orange. Maybe.

**Comment by Binaryify** [comment]
![image](https://user-images.githubusercontent.com/12221718/27250482-bcc53148-5363-11e7-8799-974bc60980b2.png)
I think orange isn't a good choice

**Comment by ajitid** [comment]
Okay then choose the color you prefer for warning, just ensure that it goes well with the theme.

**Comment by Binaryify** [comment]
Will update when I resolve this issue
https://github.com/Binaryify/OneDark-Pro/issues/59

**Comment by Binaryify** [comment]
Done ~
Please update and check it, thx ~
