### ISSUE TITLE
Markdown bold and italics and for headings

### ISSUE THREAD

**Issue by ajitid** [Binaryify/OneDark-Pro#97]
When writing markdown, bold and italic words can actually be made bold and italic. Please do that.

**Comment by Binaryify** [comment]
Will make italic words be italic, but fontStyle doesn't support 'bold'

**Comment by ajitid** [comment]
No, it does.

Nord
![screenshot 107](https://user-images.githubusercontent.com/26769888/27063873-e559f5c6-5011-11e7-8fc4-5ef87361602b.png)

Dracula
![screenshot 109](https://user-images.githubusercontent.com/26769888/27063883-ec421b7a-5011-11e7-8076-0be6b8272029.png)

OneDark Pro
![screenshot 108](https://user-images.githubusercontent.com/26769888/27063893-f41683f4-5011-11e7-9c7b-1f6e6f4f54f5.png)

**Comment by ajitid** [comment]
Maybe this is the setting for bold (pulled from Dracula):

```
		{
			"name": "Bold markup",
			"scope": [
				"markup.bold"
			],
			"settings": {
				"fontStyle": "bold",
				"foreground": "#FFB86C"
			}
		},
```

**Comment by ajitid** [comment]
Please make headings bold too.

**Comment by Binaryify** [comment]
It doesn't a option 
![image](https://user-images.githubusercontent.com/12221718/27064086-0a5db9f0-5028-11e7-8484-14c19709460c.png)

**Comment by ajitid** [comment]
![screenshot 110](https://user-images.githubusercontent.com/26769888/27064209-d17c2590-5013-11e7-985a-00f3ed599183.png)
I can't understand why it isn't showing in yours, but it shows in Dracula theme

**Comment by Binaryify** [comment]
Oh my mistake, I think it not a option and it support bold actually, will update it

**Comment by ajitid** [comment]
Thanks, make headings bold too.

**Comment by Binaryify** [comment]
ok

**Comment by Binaryify** [comment]
Please update and check it
