### ISSUE TITLE
Differenciate keys from variables

### ISSUE THREAD

**Issue by iddan** [Binaryify/OneDark-Pro#98]
So much red makes it hard to identify keys
*screenshot*
![screen shot 2017-06-13 at 12 22 07](https://user-images.githubusercontent.com/12671072/27075609-5833e91e-5033-11e7-99de-b6186a339971.png)
*code*
```JavaScript
EntityLinkField.propTypes = {
  sourceId: React.PropTypes.string,
  targetType: React.PropTypes.string,
  relationType: React.PropTypes.string,
  stateLinks: React.PropTypes.arrayOf(React.PropTypes.object),
  localLinks: React.PropTypes.arrayOf(React.PropTypes.object)
};
```

**Comment by Binaryify** [comment]
You can see this issues https://github.com/Binaryify/OneDark-Pro/issues/87
