### ISSUE TITLE
Colorize TODO/FIXME comments

### ISSUE THREAD

**Issue by SuperGeekJake** [Binaryify/OneDark-Pro#99]
As seen on line 20 of this screenshot.

![](https://i.github-camo.com/f15ae70a5e4f1078889fba95bcfdfdec75306a28/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d726f64616c67616172642f61746f6d2d746f646f2d73686f772f6d61737465722f73637265656e73686f74732f707265766965772e706e67)

**Comment by Binaryify** [comment]
You should install this extensions
https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight
![image](https://user-images.githubusercontent.com/12221718/27111749-d1378b52-50e4-11e7-8d27-d04803fcfdfd.png)
